### ISSUE TITLE
Product info retrieval support

### ISSUE THREAD

**Issue by darekxan** [bizz84/SwiftyStoreKit#1]
Does the library support retrieving of product info in any way?

**Comment by bizz84** [comment]
It does, through the [InAppProductQueryRequest](https://github.com/bizz84/SwiftyStoreKit/blob/master/SwiftyStoreKit/InAppProductQueryRequest.swift) class, however this has not been exposed in the public interface.

InAppProductQueryRequest takes a set of product IDs as input, and returns an array of [SKProduct] in the completion block. This is used internally by the main SwiftyStoreKit class.

Would you like for this to be exposes? What is your use case?

**Comment by darekxan** [comment]
My case is:
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/ShowUI.html#//apple_ref/doc/uid/TP40008267-CH3-SW5

Paragraph: Retrieving Product Information.

I believe product information including price should be shown to the user, before he decides to initiate the payment.

**Comment by bizz84** [comment]
Sounds reasonable. InAppProductQueryRequest is what you need as it will give you an array of [SKProduct](https://developer.apple.com/library/prerelease/ios/documentation/StoreKit/Reference/SKProduct_Reference/index.html)s.

All is needed is to make the class public along with its ```startQuery``` method. Can't promise I'll find time to do it in the next few days - if you need it quick please just fork the library and change the visibility modifiers.

**Comment by darekxan** [comment]
I've created quick pull request, it is still under testing.

I've tried to follow coding conventions.

One problem inconvenience this may cause is users might need to import StoreKit manually when using SKProduct.

I believe wrapping it might be good idea.

**Comment by bizz84** [comment]
@darekxan Thanks for the PR, merged with minor code formatting changes.

I also updated the README to document the new functionality and updated the pod version to 0.1.1.
