### ISSUE TITLE
completeTransactions leak

### ISSUE THREAD

**Issue by aguila9** [bizz84/SwiftyStoreKit#110]
### Platform

- [X] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [X] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [X] Sandbox
- [ ] Production

### Version
0.6

### Issue summary

Hi, thanks for your great work.

I implemented "completeIAPTransactions()" inside the AppDelegate, as you suggest. I'm using the same code that you use in your demo app. Instruments is showing a small leak.

_NativeDictionaryStorageImpl<String, InAppProductPurchaseRequest>
_NativeDictionaryStorageOwner<String, InAppProductPurchaseRequest>

![chordleak](https://cloud.githubusercontent.com/assets/9258564/20467558/2453fa84-af58-11e6-869f-226c006b1558.jpeg)

Are you aware of this? or is the problem on my side?

Thanks for your help.

**Comment by delucamike** [comment]
I am experiencing the same leak.  Looking forward to a potential solution.

**Comment by bizz84** [comment]
`InAppProductPurchaseRequest` will be removed here: https://github.com/bizz84/SwiftyStoreKit/pull/131

Once the PR is merged, would be good to test for similar leaks.

**Comment by bizz84** [comment]
@aguila9 could you retest this on version 0.7.0? If this issue is not updated in a few weeks I will close it.

**Comment by bizz84** [comment]
Tracking memory leaks on this other issue: https://github.com/bizz84/SwiftyStoreKit/issues/120

The one you refer to should no longer happen as `InAppProductPurchaseRequest` was removed on version 0.7.0.

Closing this issue.
