### ISSUE TITLE
User cannot purchase multiple consumables

### ISSUE THREAD

**Issue by KiranPanesar** [bizz84/SwiftyStoreKit#111]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [x] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x] Production

### Version
2.3.2

### Related issues
n/a

### Issue summary
Some of our users can only purchase one of each consumable in-app purchase. When the user tries again, they confirm the purchase and then get shown the following message:
```
This In-App purchase has already been bought. It will be restored for free.
```

The purchase does not complete successfully, so the user doesn't get the perk (which is good since they didn't pay for it).

### What did you expect to happen
The purchase should complete successfully, user should be charged and success handler should fire.

### What happened instead
User got the following error message:
```
This In-App purchase has already been bought. It will be restored for free.
```
with the subtitle:

```
It will restored for free.
```

**Comment by bizz84** [comment]
@KiranPanesar apologies for the late reply.

Could you double check that you're definitely using a _consumable_ IAP? This message is typically presented for _non-consumable_ IAPs:
```
This In-App purchase has already been bought. It will be restored for free.
```

**Comment by KiranPanesar** [comment]
Hey @bizz84, this issue was resolved by me switching to the latest version of SwiftyStoreKit a couple months ago. Closing this issue now 👍

**Comment by gencaysahinn** [comment]
> Hey @bizz84, this issue was resolved by me switching to the latest version of SwiftyStoreKit a couple months ago. Closing this issue now 👍

I have still same issue in v0.13.3
