### ISSUE TITLE
Methods updated but not documented?

### ISSUE THREAD

**Issue by dantaylorseo** [bizz84/SwiftyStoreKit#112]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [ ] Production

### Version
0.5.4

### Issue summary
I am literally on the first step. I am trying to implement the code you have in the demo app into my AppDelegate and I am getting an error. 

`Extra argument atomically in call`

for 

`SwiftyStoreKit.completeTransactions(atomically: true) { products in`

It looks like you have changed the method without updating the documentation or the demo app?

### What did you expect to happen
App to work as documented

### What happened instead
As above

**Comment by mateo-kozomara** [comment]
Im having the exact same issue. Also when i purchase i get back result purchase failed. Does this library still work?

**Comment by dantaylorseo** [comment]
Run pod update should sort things out. 

Sent from my mobile device. 

Dan Taylor

**Comment by mateo-kozomara** [comment]
perfect, thanks
