### ISSUE TITLE
Why the first purchase is success, second purchase attempt will cannot connect to itunes store?

### ISSUE THREAD

**Issue by jk2K** [bizz84/SwiftyStoreKit#117]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [x] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.
0.4.0

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.
- the first purchase. Succeed.
- the second purchase. cannot connect to itunes store.
- the third purchase. Succeed
...

### What did you expect to happen
ℹ Please replace this with what you expected to happen.
- the first purchase. Succeed.
- the second purchase. Succeed.
- the third purchase. Succeed

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by maodd** [comment]
I got same result, while same app worked a few days ago. Only work around is to uninstall app and reinstall from fresh. because first purchase always works.

This might be related to appstore maintenance.

![screen shot 2016-12-07 at 10 55 03 am](https://cloud.githubusercontent.com/assets/253223/20980134/8d5dde8e-bc6c-11e6-8059-fd50e4d7b96a.png)

**Comment by bizz84** [comment]
@jk2K @maodd would you be able to retest this with version 0.7.0? If this issue is not updated in the coming weeks I will close it.

**Comment by bizz84** [comment]
Closing this issue for now. If you still encounter purchase issues feel free to reopen or create a new one.
