### ISSUE TITLE
Hosted content is not downloaded

### ISSUE THREAD

**Issue by Hugo75002** [bizz84/SwiftyStoreKit#119]
### Platform

- [ ] iOS

### In app purchase type

- [ ] Non-consumable 

### Environment

- [ ] Sandbox

### Version
>= 0.5.x   Swift3

### Related issues
Hello there,
I'm using the following code to proceed to In App Purchase of Non consumable product. (folder of 11 mp3) . Everything is working except hosted content is not downloaded.

On the relevant code just below , we can read : ""    // Deliver content from server, then: ""
Do we need to implement something ? and if yes , what ?

I change atomically "true" by "false". But nothing change.
The size of my app don't change after this IAP. (For information, mp3 folder size is roughly 75 Mo, so normally i have to see a difference !)

Any help will be much appreciated.

```
func purchase(_ purchase: RegisteredPurchase) {
        
        NetworkActivityIndicatorManager.networkOperationStarted()
        SwiftyStoreKit.purchaseProduct(AppBundleId + "." + purchase.rawValue, atomically: true) { result in
            NetworkActivityIndicatorManager.networkOperationFinished()
            
            if case .success(let product) = result {
                // Deliver content from server, then:
                if product.needsFinishTransaction {
                    SwiftyStoreKit.finishTransaction(product.transaction)
                }
            }
            self.showAlert(self.alertForPurchaseResult(result))
        }
    }
```
    

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by bizz84** [comment]
SwiftyStoreKit only gives you the API to make a purchase with Apple.

You have to write the code to download the content from your server.

Also make sure that you pass `atomically: false` (see README).
