### ISSUE TITLE
Leaks

### ISSUE THREAD

**Issue by huangboju** [bizz84/SwiftyStoreKit#120]
<img width="809" alt="2016-12-20 2 50 31" src="https://cloud.githubusercontent.com/assets/14818224/21340802/d89a65be-c6c3-11e6-8336-f29c0969efeb.png">
<img width="660" alt="2016-12-20 2 50 23" src="https://cloud.githubusercontent.com/assets/14818224/21340803/d8d500d4-c6c3-11e6-914d-3aaf7936cccc.png">
<img width="915" alt="2016-12-20 2 50 07" src="https://cloud.githubusercontent.com/assets/14818224/21340805/d9bd7b3e-c6c3-11e6-93a9-3fd849ae7828.png">

**Comment by bizz84** [comment]
`InAppProductPurchaseRequest` will be removed here: https://github.com/bizz84/SwiftyStoreKit/pull/131.

Would be good to check for similar leaks once the PR is merged.

**Comment by bizz84** [comment]
@huangboju would be good if you could retest this on version 0.7.0. If there are no updates to this issue in the coming weeks I will close it.

**Comment by phimage** [comment]
I think same things could be found in `InAppProductQueryRequest`

```swift
 DispatchQueue.main.async {
            self.callback(...
        }
```
could be
```swift
 DispatchQueue.main.async {  [unowned self] in
            self.callback(...
        }
```
or 
```swift
 DispatchQueue.main.async {  [weak self] in
            guard let this = self else { /*log, or send error somewhere...*/; return }
            this.callback(...
        }
```

**Comment by bizz84** [comment]
@phimage good point. I'm aiming to fix this in the next minor release.

**Comment by bizz84** [comment]
@huangboju Just noticed you reported a leak on `InAppProductQueryRequest`, not `InAppProductPurchaseRequest`, so this issue still stands. Working on a fix now.

**Comment by huangboju** [comment]
@bizz84 Thinks
