### ISSUE TITLE
Support for content hosted by Apple for non-consumable products

### ISSUE THREAD

**Issue by masaldana2** [bizz84/SwiftyStoreKit#128]
### Platform

- [x ] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ x] Consumable
- [x ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x ] Sandbox
- [ ] Production

Hello!
I want to know how to I access the array of downloads after the item is purchased?

**Comment by bizz84** [comment]
@masaldana2 Do you refer specifically to Content hosted by Apple for non-consumable products?

https://developer.apple.com/library/prerelease/content/documentation/LanguagesUtilities/Conceptual/iTunesConnectInAppPurchase_Guide/Chapters/CreatingInAppPurchaseProducts.html#//apple_ref/doc/uid/TP40013727-CH3-SW4

This is not something that SwiftyStoreKit is supporting at the moment. I have tagged this as a feature request.

As for enabling this, if I'm correct it should be done by supporting and exposing `SKDownload` in the completion block when making a purchase. More info here:

https://developer.apple.com/reference/storekit/skdownload

**Comment by Vanyaslav** [comment]
I have added a few lines into the framework to make it work.  Any interest to implement it?

**Comment by aaru** [comment]
Any update on hosted content? waiting..... :-(

**Comment by bizz84** [comment]
Hi everyone. Apologies for the very late reply on this one!

I started working on it. This is an initial reference implementation:

https://github.com/bizz84/SwiftyStoreKit/pull/343

I haven't tested it but you can give it a try.

Hopefully I can finish this within one week.

**Comment by aaru** [comment]
Hi, Thanks for quick response :-)
i implemented your code and started testing..
i see 'updatedDownloads' in paymentQueue is called only once with download.progress =0.
**Expected** : it should be called at regular intervals untill download has finished.
Also is there any delegate method to get the download progress so what i can update my UI progress bar?

thanks
aura

**Comment by bizz84** [comment]
I can't test this as I'm unable to upload hosted content. See [my comment here](https://github.com/bizz84/SwiftyStoreKit/pull/343#issuecomment-361398819).

Any ideas?

**Comment by aaru** [comment]
I am able to upload hosted content and testing it since yesterday.
Your code works like a charm...
With help of NSNotifications i am even able to get the progress bar working..
I used iTMSTransporter command tool to upload my content to itunes connect and test it.

**Comment by bizz84** [comment]
This is now available on version [0.13.0](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.13.0)

**Comment by getaaron** [comment]
@bizz84 Is this feature still available? The readme says:

> Note: SwiftyStoreKit doesn't yet support downloading content hosted by Apple for non-consumable products. See this feature request.
