### ISSUE TITLE
Carthage Compatible!

### ISSUE THREAD

**Issue by Dershowitz011** [bizz84/SwiftyStoreKit#13]
Please make this repo carthage compatible! Thanks.

[![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-4BC51D.svg?style=flat)](https://github.com/Carthage/Carthage)

**Comment by bizz84** [comment]
I have added Carthage support. Please let me know if it works ok for you.

**Comment by Dershowitz011** [comment]
Works perfectly. Thanks.
