### ISSUE TITLE
AppleReceiptValidator: .production or .sandbox

### ISSUE THREAD

**Issue by yurevich1** [bizz84/SwiftyStoreKit#132]
Please, help me to understand how it works:

in app purchases are 'sandbox'-like even if I use .production in my iPad.
May I always use `.production`?

Why? I'm confused.

As I know, inside swift code I have to write manually: debug or release code I use.

What happends while using this library?

**Comment by ramunasjurgilas** [comment]
In the Apple documentation is written that first of all validation should be checked against production and if it fails with specific error (now I can not remember this error code) it should be checked using sandbox environment. 
If you will use **.production** value it will be done as I wrote.

**Comment by ramunasjurgilas** [comment]
One more comment. Receipt validation should not be done on the device. You must to send it to the backend and do validation in the backend. It was mentioned in WWDC 2016 InApp Purchase session.
Receipt validation should be done locally. One way of doing it by using OpenSSL framework.

**Comment by bizz84** [comment]
@yurevich1 as @ramunasjurgilas pointed out, you should use the `.production` mode. SwiftyStoreKit will automatically retry with `.sandbox` if needed.

Contributions are welcome on local receipt validation.
I'm going to close this issue as this is already tracked here: https://github.com/bizz84/SwiftyStoreKit/issues/101
