### ISSUE TITLE
Question: Local receipt validation

### ISSUE THREAD

**Issue by ramunasjurgilas** [bizz84/SwiftyStoreKit#133]
I could not found in the source code (master). Dose your framework contains local receipt validation? 

Like it is written here: [Validate the Receipt](https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html).

**Comment by bizz84** [comment]
There is already a feature request for this: https://github.com/bizz84/SwiftyStoreKit/issues/101

Closing as duplicate.
