### ISSUE TITLE
Extra functional from branch swift-2.3

### ISSUE THREAD

**Issue by jianghaoyuan2007** [bizz84/SwiftyStoreKit#135]
### Platform
- ✅ iOS

### In app purchase type
- ✅ Consumable

### Environment

- ✅ Sandbox

### Version
swift-2.3 (ed0fc30cc349bf160c8e6ed83c0bd482a161cc22)

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.

### What did you expect to happen
1⃣️ When purchased successfully, I got a callback, but was executed `paymentQueue.finishTransaction(transaction)`
2⃣️ When I got messages from function `SwiftyStoreKit.completeTransactions()` in AppDelegate, I couldn't get receipt content.
### What happened instead
1⃣️ I would like to get execute ability of `paymentQueue.finishTransaction(transaction)`
2⃣️ I would like to get receipt content from function `SwiftyStoreKit.completeTransactions()` in AppDelegate.

Thank you so much~

**Comment by bizz84** [comment]
You are advised to migrate to SwiftyStoreKit 0.7.0 or greater which introduces some important fixes to the purchase flows.

Note that these are Swift 3.0 only and according to [the project guidelines](https://github.com/bizz84/SwiftyStoreKit/blob/master/CONTRIBUTING.md), Swift 2.3 is no longer supported.

I'm closing this issue for now - if you encounter any issues with the latest version feel free to open a new one.
