### ISSUE TITLE
Ambiguous reference to member 'dataTask(with:completionHandler:)'

### ISSUE THREAD

**Issue by ChStarfish** [bizz84/SwiftyStoreKit#136]
Hello, need help...

I'm using CocoaPods.

In Swift 3.0 i have problem:

~/Pods/SwiftyStoreKit/SwiftyStoreKit/InAppReceipt.swift:214:24: Ambiguous reference to member 'dataTask(with:completionHandler:)'

This problem in this line:

 let task = session.dataTask(with: storeRequest, completionHandler: { data, response, error -> Void in

class func verify(
        receiptVerifyURL url: ReceiptVerifyURL = .Test,
        password autoRenewPassword: String? = nil,
        session: URLSession = URLSession.shared,
        completion:@escaping (_ result: SwiftyStoreKit.VerifyReceiptResult) -> ()) {

            // If no receipt is present, validation fails.
            guard let base64EncodedString = self.base64EncodedString else {
                completion(.error(error: .noReceiptData))
                return
            }

            // Create request
            let storeURL = Foundation.URL(string: url.rawValue)! // safe (until no more)
            let storeRequest = NSMutableURLRequest(url: storeURL)
            storeRequest.httpMethod = "POST"

            let requestContents :NSMutableDictionary = [ "receipt-data" : base64EncodedString]
            // password if defined
            if let password = autoRenewPassword {
                requestContents.setValue(password, forKey: "password")
            }

            // Encore request body
            do {
                storeRequest.httpBody = try JSONSerialization.data(withJSONObject: requestContents, options: [])
            } catch let e {
                completion(.error(error: .requestBodyEncodeError(error: e)))
                return
            }

            // Remote task
            let task = session.dataTask(with: storeRequest, completionHandler: { data, response, error -> Void in

                // there is an error
                if let networkError = error {
                    completion(result: .error(error: .networkError(error: networkError)))
                    return
                }

                // there is no data
                guard let safeData = data else {
                    completion(result:.error(error: .noRemoteData))
                    return
                }

                // cannot decode data
                guard let receiptInfo = try? JSONSerialization.jsonObject(with: data!, options: .mutableLeaves) as? ReceiptInfo ?? [:] else {
                    let jsonStr = String(data: safeData, encoding: String.Encoding.utf8)
                    completion(result: .error(error: .jsonDecodeError(string: jsonStr)))
                    return
                }

                // get status from info
                if let status = receiptInfo["status"] as? Int {
                    let receiptStatus = ReceiptStatus(rawValue: status) ?? ReceiptStatus.unknown
                    if receiptStatus.isValid {
                        completion(result: .success(receipt: receiptInfo))
                    }
                    else {
                        completion(result: .error(error: .receiptInvalid(receipt: receiptInfo, status: receiptStatus)))
                    }
                }
                else {
                    completion(result: .error(error: .receiptInvalid(receipt: receiptInfo, status: ReceiptStatus.none)))
                }
            }) 
            task.resume()
    }

How to fix?

**Comment by bizz84** [comment]
You're using an old version of the library. Please update to the latest SwiftyStoreKit.

I have just tested a setup with Xcode 8.2.1, Cocoapods 1.2.0 and SwiftyStoreKit 0.8.0 and everything compiles correctly.

I'm going to close this issue for now. You can open a new one if you're still experiencing problems.
