### ISSUE TITLE
Issues in production

### ISSUE THREAD

**Issue by odedharth** [bizz84/SwiftyStoreKit#148]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x] Production

### Version
0.6.1

### Issue summary
In the last 24 hours we have seen a very significant and unusual decrease in the number of successful purchases of our subscriptions. 
I'm wondering if cause could be that our SwiftyStoreKit version is 0.6.1? Were there changes in the last updates of the pod that fixed bugs that could cause that?

**Comment by bizz84** [comment]
There were some known issues with the purchase flows up to version 0.6.x.

Since 0.7.0 things are considerably improved. I recommend updating to the latest version.
