### ISSUE TITLE
Value of type 'PurchaseError' has no member 'code'

### ISSUE THREAD

**Issue by MaeseppTarvo** [bizz84/SwiftyStoreKit#156]
### Platform

- [9.0 ] iOS

### In app purchase type

- [ ] Consumable
- [* ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [* ] Sandbox
- [ ] Production

### Version
Latest

I get the error "Value of type 'PurchaseError' has no member 'code'". Weird thing is that I copy pasted the code. It is in the alertForPurchaseResult() function. 

What could be the fix for that?

**Comment by MaeseppTarvo** [comment]
NVM problem fixed. Why the pod is outdated and why you have to do pod update after fresh install of the library?

**Comment by keyanli** [comment]
still have this problem, how to fix that?

**Comment by MaeseppTarvo** [comment]
@keyanli My problem was fixed if I did `pod update` I can't say other solutions for now.

**Comment by keyanli** [comment]
@MaeseppTarvo Yeah it works for me, but once you run pod install again, the problem shows again

**Comment by timsredman** [comment]
using `pod update` worked of me too.
