### ISSUE TITLE
Error Domain=SKErrorDomain Code=3 Invalid product id

### ISSUE THREAD

**Issue by returnzer0** [bizz84/SwiftyStoreKit#157]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [x] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
ℹ Swift 3.0 >= 0.5.x

### Related issues
Purchase Issue for v0.2.7 #29

### Issue summary
I'm testing IAP in sandbox, I have followed this link http://troybrant.net/blog/2010/01/invalid-product-ids/

Made sure my ids are correct, am using downloaded example with different id and shared secret.
but the problem still persists.

### What did you expect to happen
I expect to see and purchase the IAP item.

### What happened instead
I get the error that the product id is invalid.

Purchase Failed: SKError(_nsError: Error Domain=SKErrorDomain
Code=3 "Invalid product id: com.myapp.genericproductID.IAPItem" UserInfo={NSLocalizedDescription=Invalid product id: com.myapp.genericproductID.IAPItem})

**Comment by bizz84** [comment]
This is the same as #154.

Closing as duplicate
