### ISSUE TITLE
Restore issue

### ISSUE THREAD

**Issue by androidcn** [bizz84/SwiftyStoreKit#159]
### Platform

- [X] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [X] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [X] Sandbox
- [ ] Production

### Version
latest

always report

Restore Failed: [(__C.SKError(_nsError: Error Domain=SKErrorDomain Code=0 "无法连接到 iTunes Store" UserInfo={NSLocalizedDescription=无法连接到 iTunes Store}), nil)]

**Comment by bizz84** [comment]
Do you get an invalid product ID error? If so this is a duplicate of #154

**Comment by bizz84** [comment]
I'm going to close this for now. Feel free to reopen if you have more questions.
