### ISSUE TITLE
Unable to reproduce Swifty's in app purchase

### ISSUE THREAD

**Issue by quantumproducer** [bizz84/SwiftyStoreKit#160]
### Platform

- [X ] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [ X] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ X] Sandbox
- [ ] Production

### Version
branch "swift2" of     pod 'SwiftyStoreKit', '~> 0.3.0'

### Related issues
https://github.com/bizz84/SwiftyStoreKit/issues/158

### Issue summary

I'm able to make an in-app purchase successfully. My problem is in understanding what Swifty Store Kit is doing. I tried copying the base64encodedString and creating a cURL with my shared secret but I get `21002`. In Swifty, it works.

What am I missing here?

http://stackoverflow.com/questions/42656273/in-app-purchase-swifty-store-kit-showing-valid-purchase-curl-shows-error-code-2

### What did you expect to happen
I expect to be able to reproduce Swifty's request with a cURL

### What happened instead
Apple rejects for malformed JSON.

**Comment by bizz84** [comment]
@quantumproducer Apologies for the late reply.

Maybe [this reference page](https://developer.apple.com/library/ios/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html) can help you.

I'm closing this issue as it's not a problem in SwiftyStoreKit.
