### ISSUE TITLE
TVOS AutoRenewable Cannot Purchase Cannot GetInfo

### ISSUE THREAD

**Issue by gerasimospy** [bizz84/SwiftyStoreKit#165]
### Platform

- [ ] iOS
- [ ] macOS
- [x] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
Pod version 0.8.4

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
I have created auto renewing subscription IAP's for use with a TVOS app.  When I attempt to getinfo or purchase using TVOS it fails with the following error : Invalid Product Identifier

When I run the same code in iOS everything works fine, both getinfo and purchase.

I have attached both project files so you can see them, iOS working and TVOS not working.

### What did you expect to happen
I expected the Subscription to work as it does in iOS

### What happened instead
Both Purchase and GetInfo failed

[Archive.zip](https://github.com/bizz84/SwiftyStoreKit/files/844443/Archive.zip)

**Comment by bizz84** [comment]
@gerasimospy thank you for submitting this.

I have included your tvOS demo code into SwiftyStoreKit here: https://github.com/bizz84/SwiftyStoreKit/pull/167

I can also see that retrieving products info works on iOS but not tvOS.

Will be investigating some more.

**Comment by gerasimospy** [comment]
Hello Bizz

Thank you for getting back to me. Hopefully we can get to the bottom of this. I'm wondering if autorenewable subscriptions need the group they are set up in passed into the code. I have a feeling the issue is related to the group, hopefully can pin point it.

**Comment by bizz84** [comment]
"Invalid product identifier" is the first step before a purchase is made. This fails consistently for all IAP types on tvOS: (non-consumable, consumable, auto-renewable, non-renewing). See updates on #167

**Comment by Sam-Spencer** [comment]
Closing as stale duplicate.
