### ISSUE TITLE
Auto Renewable Error

### ISSUE THREAD

**Issue by ghost** [bizz84/SwiftyStoreKit#166]
### Platform

- [X] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [X] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [X] Sandbox
- [X] Production

### Version
0.7.1 (In Production and Live)
0.8.4 (In Testing, trying to fix the bugs now)

### Related issues
None Found.

### Issue summary
I have auto renewable subscriptions in my app. After SwiftyStoreKit.purchaseProduct, atomically, If it succeeds, I call SwiftyStoreKit.verifyReceipt. When I SwiftyStoreKit.verifyReceipt, should I call refreshReceipt if there is an error like below?

In the live version of the app:
```
case .error(let error):
    print(error)
    if case .noReceiptData = error {
        self.refreshReceipt(product: product, isPurchased: isPurchased, completion: { result in
            completion(result)
        })
    }
    else{
        completion("Failure")
    }
```

Or should it be like the following:
```
case .error(let error):
    print(error)
    completion("Failure")
```

### What did you expect to happen
Users successfully subscribe and purchase the product with no errors.

### What happened instead
Users are purchasing the product and getting charged, but the code fails to update the user's purchase.

**Comment by bizz84** [comment]
@mrnahidtalukder Apologies for the late reply.

I have updated the documentation for [Receipt Verification](https://github.com/bizz84/SwiftyStoreKit#receipt-verification). According to [Apple Docs](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/DeliverProduct.html#//apple_ref/doc/uid/TP40008267-CH5-SW4):

> Information about all other kinds of purchases is added to the receipt when they’re paid for and remains in the receipt indefinitely.

Based on this I believe that **after** you successfully purchase a subscription, you should never get `.noReceiptData` in your receipt (unless there's a bug in SwiftyStoreKit).

Instead, if you call `verifyReceipt` **before** you made any purchases (for example, first time install), you could get `.noReceiptData`.

Is this still a problem on the latest version?

**Comment by bizz84** [comment]
@ghost `refreshReceipt` was removed in version [0.10.0](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.10.0).

After you purchase an auto-renewable subscription, you can verify it as explained [in the README](https://github.com/bizz84/SwiftyStoreKit#verify-subscription).

I'm closing this issue. Feel free to reopen and comment if you still have questions.
