### ISSUE TITLE
MAIN ISSUE: Pressing cancel lead to completing purchase transaction...

### ISSUE THREAD

**Issue by yarodevuci** [bizz84/SwiftyStoreKit#168]
Tried the demo. When I press Purchase and then Cancel button in UIAlertWindow, my purchase still goes trough... why??

**Comment by bizz84** [comment]
I don't believe that's the case. When the user cancels the purchase the transaction fails:

<img width="752" alt="screen shot 2017-03-21 at 22 13 10" src="https://cloud.githubusercontent.com/assets/153167/24173386/b79deda6-0e83-11e7-8b33-8b2bc0bdd8fa.png">

As a result, the completion block of the `purchase()` method returns an error:

```
public enum PurchaseResult {
    case success(product: Product)
    case error(error: SKError)
}
```

Please make sure that you're parsing the result correctly.

**Comment by yarodevuci** [comment]
@bizz84 Tested on iOS 8.4, iOS 10 cancel works fine,
