### ISSUE TITLE
How to deal with auto-renewable subscription?

### ISSUE THREAD

**Issue by gerchicov-bp** [bizz84/SwiftyStoreKit#174]
Need to update a readme file.

Current readme just describes how to send a purchase request.

How to handle result? How to renew it? Does sandbox users' behaviour differs from real one?

**Comment by bizz84** [comment]
@gerchicov-bp apologies for the late reply.

This snippet summarises how to:
* purchase a subscription, then
* verify that the receipt is valid, then
* check the status of the subscription

```swift
let productId = "your-product-id"
SwiftyStoreKit.purchaseProduct(productId, atomically: true) { result in
    
    if case .success(let product) = result {
        // Deliver content from server, then:
        if product.needsFinishTransaction {
            SwiftyStoreKit.finishTransaction(product.transaction)
        }
        
        let appleValidator = AppleReceiptValidator(service: .production)
        SwiftyStoreKit.verifyReceipt(using: appleValidator, password: "your-shared-secret") { result in
            
            if case .success(let receipt) = result {
                let purchaseResult = SwiftyStoreKit.verifySubscription(
                    type: .autoRenewable,
                    productId: productId,
                    inReceipt: receipt)
                
                switch purchaseResult {
                case .purchased(let expiryDate):
                    print("Product is valid until \(expiryDate)")
                case .expired(let expiryDate):
                    print("Product is expired since \(expiryDate)")
                case .notPurchased:
                    print("This product has never been purchased")
                }

            } else {
                // receipt verification error
            }
        }
        
    } else {
        // purchase error
    }
}
```

This is a combination of the [Purchase](https://github.com/bizz84/SwiftyStoreKit#purchase-a-product) and [Verify Subscription](https://github.com/bizz84/SwiftyStoreKit#verify-subscription) methods.

As requested, I have updated the documentation in the README: https://github.com/bizz84/SwiftyStoreKit/pull/189

**Comment by bizz84** [comment]
@gerchicov-bp Suggested Read:

[Apple - Working with Subscriptions](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html#//apple_ref/doc/uid/TP40008267-CH7-SW6)

**Comment by bizz84** [comment]
Documentation further improved on #213.
If you don't have other questions, I will close this issue once the PR is merged.

**Comment by htarwara6245** [comment]
How to handle it for restored? Please correct me if I am wrong. I really need a way to handle restore process on auto-renewable subscription.

**Comment by bizz84** [comment]
Do you just need to check if an auto-renewable subscription is valid?

If so, this is all you need:

https://github.com/bizz84/SwiftyStoreKit#verify-subscription

**Comment by bizz84** [comment]
@htarwara6245 you can information about all previously purchased non-consumable purchases and subscriptions by verifying the receipt, even if the user reinstalled the app. In your case, you can verify an auto-renewable subscription as explained [in the README](https://github.com/bizz84/SwiftyStoreKit#verify-subscription).

Closing this issue.

**Comment by WillMays1** [comment]
My code keeps going to the `// purchase error` else statement. Once I verify the subscription and it shows that it has not been purchased, I call the purchase statement and it goes to the purchase error statement. What do I need to do to get this working for production?
