### ISSUE TITLE
Xcode 8.3: String interpolation Warning

### ISSUE THREAD

**Issue by aguila9** [bizz84/SwiftyStoreKit#176]
### Platform

- [X] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [X] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [X] Sandbox
- [X] Production

### Version
0.8.4

### Issue summary
I just update to Xcode 8.3. I'm getting the following warnign:
/Users/.../SwiftyStoreKit/PaymentQueueController.swift:62:126: String interpolation produces a debug description for an optional value; did you mean to make this explicit?

**Comment by francoisduchemin** [comment]
I'm getting the same warning.

**Comment by kmcgill88** [comment]
Same, pretty annoying. I'm new to this project but will try a PR soon, get my feet wet.

**Comment by kmcgill88** [comment]
So this was fixed in PR [172](https://github.com/bizz84/SwiftyStoreKit/pull/172) but a new pod version hasn't been released. So just need @bizz84 to cut the next release or point at master for the time being with `:git =>`

**Comment by bizz84** [comment]
[Version 0.8.5](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.8.5) fixes this and has been released.
