### ISSUE TITLE
Change Restore to return all products ids at once 

### ISSUE THREAD

**Issue by mortenholmgaard** [bizz84/SwiftyStoreKit#18]
Could it be possible to change the Restore method to return all productIds at once?

Sometimes one needs some heavy computation after the restores, but like it is right now, it is not possible to know which callback is the last.

**Comment by bizz84** [comment]
I agree that this would be desirable behaviour.

The Apple documentation for [SKPaymentQueue.restoreCompletedTransactions()](https://developer.apple.com/library/ios/documentation/StoreKit/Reference/SKPaymentQueue_Class/#//apple_ref/occ/instm/SKPaymentQueue/restoreCompletedTransactions) says the following:

_The payment queue will deliver a new transaction for each previously completed transaction that can be restored. Each transaction includes a copy of the original transaction._

SwiftyStoreKit uses the 
[SKPaymentTransactionObserver.paymentQueueRestoreCompletedTransactionsFinished](https://developer.apple.com/library/ios/documentation/StoreKit/Reference/SKPaymentTransactionObserver_Protocol/#//apple_ref/occ/intfm/SKPaymentTransactionObserver/paymentQueueRestoreCompletedTransactionsFinished:) method to detect when the transactions have been restored. The documentation for this method says:

_This method is called after all restorable transactions have been processed by the payment queue. Your application is not required to do anything in this method._

While in theory this means that it should be possible to gather all the transactions' productIDs and return then, in practice it appears that `SKPaymentTransactionObserver.paymentQueueRestoreCompletedTransactionsFinished` is called once for each transaction.

If this is the actual behaviour of StoreKit, there doesn't seem to be a way of returning all restored productIDs in one callback. Worse, I'm not sure that there is a way to tell which is the last callback.

This is my interpretation though and I may have missed something. If anyone knows a way around this, please let me know.

**Comment by mortenholmgaard** [comment]
I have taken a quick look at the code and to me it looks like you should be able to just use the 
`SKPaymentTransactionObserver.paymentQueueRestoreCompletedTransactionsFinished`
Right now you don't really use it for any thing else than return `.NothingToRestore`

I think it could be done just iterating `queue.transactions` in `SKPaymentTransactionObserver.paymentQueueRestoreCompletedTransactionsFinished`
 with the code from the `.Restore `case in the method `func paymentQueue(queue: SKPaymentQueue, updatedTransactions transactions: [SKPaymentTransaction])` and remove the `.Restore `case from that method.

Does it make sense?

**Comment by bizz84** [comment]
Haven't investigated yet but yes. I'll try to look into it this week.

**Comment by bizz84** [comment]
Implemented tentative solution here:
https://github.com/bizz84/SwiftyStoreKit/pull/19/files
Feedback welcome

**Comment by mortenholmgaard** [comment]
I have just tested it and it seems to work perfectly! - just as expected it restored multiple products in only one callback.
Hope you will make a pods release with this soon

**Comment by bizz84** [comment]
This has now been merged and included in pod release 0.2.5
