### ISSUE TITLE
Could not retrieve product infoInvalid product identifier

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [bizz84/SwiftyStoreKit#180]
Platform:
iOS

In app purchase type
Non-Consumable

Environment
Sandbox

Version
Latest

I wrote the code under to test SwiftyStoreKit:
        SwiftyStoreKit.retrieveProductsInfo(["com.TCWQ.Oregairu.FullVersion"]) { result in
            if let product = result.retrievedProducts.first {
                let priceString = product.localizedPrice!
                print("Product: \(product.localizedDescription), price: \(priceString)")
            }
            else if let invalidProductId = result.invalidProductIDs.first {
                print("Could not retrieve product info"+"Invalid product identifier: \(invalidProductId)")
            }
            else {
                print("Error: \(result.error)")
            }
        }
And then, the debugger prints 
Could not retrieve product infoInvalid product identifier: com.TCWQ.Oregairu.FullVersion

And I'm sure the identifier is correct, what should I do?

**Comment by kmcgill88** [comment]
- Did you first call `SwiftyStoreKit.completeTransactions()` in your AppDelegate, before calling `SwiftyStoreKit.retrieveProductsInfo`? 
- Are you positive`com.TCWQ.Oregairu.FullVersion` is setup in iTunes Connect?

**Comment by CaptainYukinoshitaHachiman** [comment]
This is my appDelegate
Could you help me find out the problem?
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?


    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        GADMobileAds.configure(withApplicationID: "XXXXXXXXXXXXXXX")
        SwiftyStoreKit.completeTransactions(atomically: true) { products in
            
            for product in products {
                
                if product.transaction.transactionState == .purchased || product.transaction.transactionState == .restored {
                    
                    if product.needsFinishTransaction {
                        // Deliver content from server, then:
                        SwiftyStoreKit.finishTransaction(product.transaction)
                    }
                    print("purchased: \(product)")
                }
            }
        }
        return true
    }

    func applicationWillResignActive(_ application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
    }

    func applicationDidEnterBackground(_ application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }

    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }

    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
        // Saves changes in the application's managed object context before the application terminates.
    }

}

**Comment by kmcgill88** [comment]
That looks correct to me. I do the same thing. Call `SwiftyStoreKit.completeTransactions` in app delegate at start, then a button triggers `SwiftyStoreKit.retrieveProductsInfo`  which displays the details of the purchase. Last `SwiftyStoreKit.purchaseProduct` makes the purchase.

Couple other ideas:
- Make sure the device `SwiftyStoreKit.canMakePayments`
- Again make sure the in app purchase is setup in itunes connect
- Make sure you are using a sandbox user. Look at `Users & Roles` section of iTunes connect.

**Comment by CaptainYukinoshitaHachiman** [comment]
I noticed that I did not fill the banking info.
Is it the reason why it can't retrieve?

**Comment by kmcgill88** [comment]
Very well could be. Let me know if that fixes it.

**Comment by D8man** [comment]
I have the same issue.

**Comment by CaptainYukinoshitaHachiman** [comment]
Now it works after filling the banking information on iTunes Connect.

**Comment by KingOlami** [comment]
hi please I have been unable to get this project to work kind view my issue and contribute to it please thanks. https://github.com/bizz84/SwiftyStoreKit/issues/412

**Comment by johndpope** [comment]
This should be added into the sample ios code - 


   func alertForProductRetrievalInfo(_ result: RetrieveResults) -> UIAlertController {

        if let product = result.retrievedProducts.first {
            let priceString = product.localizedPrice!
            return alertWithTitle(product.localizedTitle, message: "\(product.localizedDescription) - \(priceString)")
        } else if let invalidProductId = result.invalidProductIDs.first {

// check you have setup banking & tax info in itunes connect
            return alertWithTitle("Could not retrieve product info", message: "Invalid product identifier: \(invalidProductId)")
        } else {
            let errorString = result.error?.localizedDescription ?? "Unknown error. Please contact support"
            return alertWithTitle("Could not retrieve product info", message: errorString)
        }
    }
