### ISSUE TITLE
Getting the Transaction Date of a Restored Auto Renewable Transaction

### ISSUE THREAD

**Issue by Jayvd** [bizz84/SwiftyStoreKit#181]
### Platform

- [ ] iOS

### In app purchase type
- [ ] Auto-Renewable Subscription

### Environment
- [ ] Sandbox

### Issue summary
ℹ Get the Transaction Date of a Restored Auto Renewable Transaction.

### What did you expect to happen
ℹ It is my understanding that, when we call  `SwiftyStoreKit.restorePurchases()`, **all previous purchases** will be returned in a `RestoreResults` object. Since in my app I only use Auto-Renewable subscription, how do I detect which one of the purchases are still valid (Not Expired yet)? 

### What happened instead
ℹ I am unable of getting the `expireDate` of the restoredPurchases aka `RestoreResults`

**Comment by bizz84** [comment]
@Jayvd To get the status of your auto-renewable subscriptions you should use the `verifySubscription` method as explained [in the README](https://github.com/bizz84/SwiftyStoreKit#verify-subscription).

This will return `purchased`, `expired` or `notPurchased` with the `expiryDate` as appropriate:

```swift
public enum VerifySubscriptionResult {
    case purchased(expiryDate: Date)
    case expired(expiryDate: Date)
    case notPurchased
}
```

1. In your specific case, you could call `SwiftyStoreKit.restorePurchases()`.
2. Then, in the completion block, call `SwiftyStoreKit.verifyReceipt` and `SwiftyStoreKit.verifySubscription` as outlined [in the README](https://github.com/bizz84/SwiftyStoreKit#verify-subscription).

**Comment by bizz84** [comment]
@Jayvd Please let me know if this answers your question. I will close this issue in the coming weeks if it's not updated.

**Comment by Jayvd** [comment]
Yes, it works @bizz84 . Sorry for the late reply, I only received the last email notification about replies on this issue. Thank you
