### ISSUE TITLE
Free Trial not showing up in Sandbox Mode

### ISSUE THREAD

**Issue by shortcircuit3** [bizz84/SwiftyStoreKit#182]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
SwiftyStoreKit (0.8.4)

### Related issues
http://stackoverflow.com/questions/42816340/ios-auto-renewable-subscriptions-free-trial-not-being-indicated

## Report
I can't seem to figure out how to get the free trial dialog to show up. All other apps that offer a free trial have a dialog like this:

![img_0871](https://cloud.githubusercontent.com/assets/421362/25066971/5991ba88-2203-11e7-8e24-f6c9b3fdf8c4.PNG)

### Issue summary
I added a 1 week free trial to the product in iTunes connect. When in sandbox the free trial doesn't appear.

### What did you expect to happen
I want a dialog to appear with a free trial text label. Silimar to the screenshot above.

### What happened instead
1)
![img_0872](https://cloud.githubusercontent.com/assets/421362/25067000/1de6d454-2204-11e7-8636-5a31e77d9c26.PNG)

2)
![img_0873](https://cloud.githubusercontent.com/assets/421362/25067001/233d12b0-2204-11e7-8a6b-fb7d8f2c0541.PNG)

**Comment by bizz84** [comment]
@milesalex could it be a Sandbox issue?

Could you spend some time reading the Apple Docs and see if you find an answer?

I wouldn't expect this to be an issue in SwiftyStoreKit (it's just a wrapper on StoreKit).

**Comment by vysakhcs1** [comment]
I was having the same issue. Its because you have already subscribed and used the free trial before. After that you will never get free trial message box.
Please login with another un used Apple ID and try, it will pop up with free trial message. Thanks
