### ISSUE TITLE
The library doesn't return all the necessary info it has and it increases the amount of code a programmer needs to write

### ISSUE THREAD

**Issue by gerchicov-bp** [bizz84/SwiftyStoreKit#185]
### Platform

- [ ] iOS

### In app purchase type

- [ ] Auto-Renewable Subscription

### Environment

- [ ] Sandbox
- [ ] Production

### Version
0.8.4/0.8.5

### Issue summary
Some of the methods of this library decrease the amount of returned info which forces to rewrite library methods and/or add extra code and perform extra requests.
In my particular case it is method ```SwiftyStoreKit.purchaseProduct(...)```. The intermediate result of this request is ```SKProduct``` which has ```price```. But for some purpose you hide it and pass an incomplete info into completion block. What should I do in this case? edit library sources? request all products' info and store it somewhere else? perform additional request to get full product info? It seems You should return ```SKProduct``` object instead of your own ```Product``` one.

### What did you expect to happen
```SKProduct``` object (or dictionary which replaces it) is returned.

### What happened instead
```Product``` object is returned which doesn't represent all the info from ```SKProduct```

**Comment by bizz84** [comment]
**Premise**: Two principles behind the design of the SwiftyStoreKit API are:

- make the API as easy to use as possible
- expose the smallest amount of information possible, so that it is harder to use it incorrectly.

As these can be in conflict with each other, the best approach is decided on a case-by-case basis.

-----------

In your specific case you need to read the `price` of a `SKProduct`. Do you need to use this **before** or **after** the product is purchased?

If the intent is to show the price to the user **before** the product is purchased, you can use the [`retrieveProductsInfo`](https://github.com/bizz84/SwiftyStoreKit#retrieve-products-info) method. 

In principle, purchasing a product can be done independently from retrieving product info, even though `purchaseProduct` calls `retrieveProductsInfo` internally.

If you are proposing to change the API for this, please explain your use case in detail so I can better understand the requirements.

**Comment by gerchicov-bp** [comment]
In my specific case I need to read the price **after** product purchased to send statistics. I understand that I should receive a product list before showing the pricing page at all.

Anyways I could receive price and price locale after purchase via pure StoreKit and can't do the same thing with this library

**Comment by bizz84** [comment]
I see. If you were to use StoreKit only, you would still have to do two steps:

- Request product info first (to get the `SKProduct`)
- Do the purchase for the given `SKProduct`

I'll treat this as a feature request and see what I can do about it. For now [`retrieveProductsInfo`](https://github.com/bizz84/SwiftyStoreKit#retrieve-products-info) is the way to go.

**Comment by bizz84** [comment]
@gerchicov-bp This is worth a read:
[Apple TN2387 In-App Purchase Best Practices](https://developer.apple.com/library/content/technotes/tn2387/_index.html)

Quoting: 

> Your app must first send a product request to the App Store before deciding what products to display for purchase in its user interface. Sending a product request allows you to determine whether your products are available for sale in the App Store, thus preventing you from displaying products that cannot be purchased in your app

On this basis, it makes sense to call `retrieveProductsInfo` first. Once the callback returns, you can store the product price somewhere if needed, and use it again after your purchase is complete.

**Comment by bizz84** [comment]
@gerchicov-bp #205 implements a tentative solution for this issue, however I don't like it for a number of reasons:

* the new`Purchase.product` value is optional, always present when making a purchase, but never present when restoring purchases or completing transactions:
```swift
public struct Purchase {
    public let productId: String
    public let quantity: Int
    public let product: SKProduct? // only available when making a purchase
    public let transaction: PaymentTransaction
    public let originalTransaction: PaymentTransaction?
    public let needsFinishTransaction: Bool
}
```
* I think this clutters the API a bit, and you would have to use it like this:

```swift
SwiftyStoreKit.purchaseProduct(appBundleId + "." + purchase.rawValue, atomically: true) { result in
    NetworkActivityIndicatorManager.networkOperationFinished()

    if case .success(let purchase) = result {
        // Deliver content from server, then:
        if purchase.needsFinishTransaction {
            SwiftyStoreKit.finishTransaction(purchase.transaction)
        }
        if let product = purchase.product {
            // do stuff with product
        }
    }
}
```
A slightly better solution would be to leave `Purchase` as it was, and subclass like this:

```swift
struct PurchaseDetails: Purchase {
    public let product: SKProduct
}
```
This way you would always get non-optional access to `SKProduct` when making a purchase, without cluttering the other APIs.

As discussed before though, you can get the `SKProduct` by calling `retrieveProductsInfo` beforehand, so I'm not sure if this is worthwhile enough to be added.

What do you think?

**Comment by bizz84** [comment]
This is now available on release [0.9.1](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.9.1).

**Comment by gerchicov-bp** [comment]
@bizz84 I got almost the same issue - I need a detailed `product` description in `SwiftyStoreKit.completeTransactions` but currently it returns `productId` only

**Comment by bizz84** [comment]
* `purchaseProduct()` enqueues a `SKPayment` which includes a `SKProduct`, so this can be returned in the completion block.
* `completeTransactions()` only gets updated transactions, which don't contain a `SKProduct`
* `restorePurchases()` is similar to `completeTransactions()` in this respect

Given a product id, it is always possible to get the corresponding product with a call to `retrieveProductsInfo()`.
