### ISSUE TITLE
Atomic purchase on the Swift 2.2 version?

### ISSUE THREAD

**Issue by swami-108** [bizz84/SwiftyStoreKit#186]
Is it possible to do an atomic purchase on the Swift 2.2 version? I'd like to wait till I get a response back from my server before I finish the IAP purchase, but unfortunately, I'm on Swift 2.2 and not in a position to upgrade at the moment. What can I do?

Thanks.

### Platform

- [x ] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [x ] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ x] Sandbox
- [ ] Production

### Version
0.4.0

**Comment by bizz84** [comment]
@swami-108 I suggest you do this:

- Fork SwiftyStoreKit v0.4.0
- Try to merge the changes from #107 (you could create a patch from commit d4579d9dc91225c0a6fe32e93f01e49197aa1444 and apply it to your branch)
- Resolve any merge conflicts
- Make merged code compatible with Swift 2.2.

Then, you should be able to perform **non-atomic** purchases, which will work with your server logic.

Note that purchase flows have been reimplemented entirely in version 0.7.0 and you should update to the latest version.

**Comment by bizz84** [comment]
Closing this issue for now, feel free to ask more questions if needed.

**Comment by swami-108** [comment]
@bizz84 Thanks for the suggestions! I'm new to Git and to Swift, so let me see what I can manage! I used CocoaPods to install SwiftStoreKit...will I still be able to do use CocoaPods to install this in my project after forking and merging?

**Comment by swami-108** [comment]
Also, I have a general question if you wouldn't mind answering. All I'm really doing is calling SwiftyStoreKit.retrieveProductsInfo() and SwiftyStoreKit.purchaseProduct(). Everything works fine, but I'm not doing anything with receipt validation, etc. Is that required by Apple?

**Comment by bizz84** [comment]
Re. Cocoapods, yes, you can point to your own repo. Something like this:
```
pod 'SwiftyStoreKit', :git => 'https://github.com/swami-108/SwiftyStoreKit', :branch => 'your-branch-name'
```

You can think of receipt validation as an extra layer of security for your IAPs. Strictly you don't need it but if you're selling your IAPs in considerable numbers I think it's worth looking into it and understanding how it works.

Also if you work with subscriptions you'll definitely need to use it as it will give you the receipt that you can use to check if the subscription is expired or not. [See this](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html#//apple_ref/doc/uid/TP40008267-CH7-SW6).
