### ISSUE TITLE
Complete transactions callback not called if there are not pending transactions.

### ISSUE THREAD

**Issue by Dino4674** [bizz84/SwiftyStoreKit#187]
If there are no updated transactions, this callback will not be called. In am depending on it on app startup to continue with app logic. But if it is not being called, my app is stuck.

Why can not this callback be called with empty products array if there are no pending transaction in the system?

    public class func completeTransactions(atomically: Bool = true, completion: @escaping ([Product]) -> ()) {
        sharedInstance.completeTransactionsObserver = InAppCompleteTransactionsObserver(atomically: atomically, callback: completion)
    }

**Comment by bizz84** [comment]
@Dino4674 This is expected.

The `completeTransactions` callback is only called if:
* the payment queue reports that there are updated transactions via the `SKPaymentTransactionObserver` protocol implemented in [PaymentQueueController.swift](https://github.com/bizz84/SwiftyStoreKit/blob/master/SwiftyStoreKit/PaymentQueueController.swift), and:
* there aren't already active calls to `purchaseProduct` or `restorePurchases`.

Please read [this section](https://github.com/bizz84/SwiftyStoreKit#payment-flows---implementation-details) for a clarification on how the payment flows work.

My recommendation is to change your app startup logic to not expect a callback from `completeTransactions`.

If this is not suitable for you, please confirm what your use case is and I see what is the best way to handle it.

**Comment by Dino4674** [comment]
Thanks for the info. My use case is that I check the auto-renewable subscription receipt on app startup to check if subscription is still valid (to further know what app features to show inside the app).

When in sandbox environment, auto-renewable subscription is renewed after 5mins (max 5x a day) and then it expires. In production environment, subscription would try to auto renew 24h before the expiration date but in sandbox, lots of times, it happens slightly after the 5min expiration, meaning, subscription failed to auto-renew before the expiration date and there is a period where subscription is not valid.

I just realized I was using some other SwiftyStoreKit version where PaymentQueueController.swift is not event in there. I need to update the code. How could this happend, I installed though cocapods and did not specify some other version?

**Comment by Dino4674** [comment]
I also see that autorenewable subscription verification code is updated with this version of SwiftyStoreKit. There was no AppleReceiptValidator object in the SwiftyStoreKit version I was using. This is strange.

**Comment by Dino4674** [comment]
@bizz84 can you please suggest the flow to implement with auto-renewable subscriptions with client side validation of subscription and server side storage.

e.g.
I have one auto-renewable subscription, after user signs in, I check the status of that subscription. If subscription is .purchased, I notify my server that subscription is purchased. If it is not and server thinks that user is 'premium' I notify server that user does not have valid subscription anymore and do auto logout/login of user because app is depending on server to tell whether subscription is valid or not when presenting premium features. Client is responsible for validation and syncing the AppStore subscription with the server 'isPremiumUser' flag.

When subscription gets auto-renewed, where is the place where that event can be received?
Is `completeTransactions()` meant for that or only for transactions that haven't yet been completed (`SwiftyStoreKit.finishTransaction(product.transaction)` have not been called).

**Comment by bizz84** [comment]
@Dino4674 I suggest to update to pod version [0.9.0](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.9.0).

In your Podfile:
```ruby
pod 'SwiftyStoreKit'
```
Then, run `pod install` or `pod update`.

Closing this for now, feel free to reopen if you have problems with the new version.

**Comment by Minishlink** [comment]
@bizz84 Hi, I use a React Native wrapper around SwiftyStoreKit. Typically in a React Native project the retrieved purchases (either bought/restored/or pending completion like for completeTransactions) are sent to the server or treated in any way on the Javascript side and not on the native side.
So what I do is that is resolve a promise with the retrieved products / purchases.
Problem is, with the completeTransactionsController, if there are no purchases waiting for completions, I can't have the information, so I can't resolve anything

So it would be great to have an empty array returned by completeTransactions, or a new function getTransactionsWaitingForCompletion that does so
