### ISSUE TITLE
Get 'Subscription updated' event

### ISSUE THREAD

**Issue by Dino4674** [bizz84/SwiftyStoreKit#191]
Hi @bizz84 

I am working with auto-renewable subscription.

Client is doing subscription validation and server is storing the 'isPremiumUser' flag (`isPremiumFlag` should be in sync with the purchased subscription - if there is a valid subscription, server will have to be updated with TRUE value, when subscription expires, server should be updated with FALSE value).

After user logins I need to check few things:

1. If AppStore subscription is valid and server's `isPremiumUser == false`, I update the server flag to `true` and auto logout/login user so that login process fetches the updated `isPremiumUser == true` so that I can show premium features inside the app.

2. If AppStore subscription is NOT valid (expired or not purchased) and server's `isPremiumUser == true', I update the server flag to `false` and auto logout/login user so that login process fetches the updated `isPremiumUser == false` so that I can hide premium features.

Where can I expect 'Subscription Updated' event, meaning how can I know when my subscription gets auto-renewed?

Also, where does the 'completeTransactions()' API come in place here? I am calling this API also after the login but after I updated to the newest `SwiftyStoreKit` I see the warning log that this method should be called only once.
Is this API meant to be used only to complete the transaction by calling the `SwiftyStoreKit.finishTransaction(product.transaction)`? (event though I am using non-atomic transactions).

Can I rely only on subscription verification logic to know what to tell to the server?

Thanks

**Comment by bizz84** [comment]
First of all, you should read Apple docs on [Working with Subscriptions](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html#//apple_ref/doc/uid/TP40008267-CH7-SW6).

From what I can see in the docs, you won't get a _Subscription updated_ event while the app is running.

Better to check your subscription each time the app is launched (see [Verify Subscription](https://github.com/bizz84/SwiftyStoreKit#verify-subscription)) and update your server flag depending on whether the subscription is `purchased` or `expired`.

In short:

* Call [`verifySubscription`](https://github.com/bizz84/SwiftyStoreKit#verify-subscription) when the app launches to check if your subscriptions is active or expired. Use this to update your server.
* Call [`verifySubscription`](https://github.com/bizz84/SwiftyStoreKit#verify-subscription) again when purchasing the subscription (or restore purchases) succeeds. Use this to update your server.

Makes sense?

As for `completeTransactions`, it is used to register to the payment queue. You should only call it once in `application(_: didFinishLaunchingWithOptions:)`. Quoting [Apple Docs](https://developer.apple.com/library/content/technotes/tn2387/_index.html):

> Adding your app's observer at launch ensures that it will persist during all launches of your app, thus allowing your app to receive all the payment queue notifications.

**Comment by Dino4674** [comment]
I've read that doc already but run onto much inconsistencies in the sandbox environment. Also I've seen lots of complaints online in regards to the auto-renewable subscription tools provided by Apple. Thats how I found `SwiftyStoreKit` which really solves the ugly Apple's API for purchases. 

I've already updated my code according to the "Verify Subscription" section after I updated `SwiftyStoreKit pod` today. Btw, I think this solved most of my problems since somehow I was using some older `SwiftyStoreKit` version which was reporting '.purchased' events in `completeTransactions` API 5x times each 5minutes for each sandbox test user. Also in that `SwiftyStoreKit` version the "Verify Subscription" API was not working with sandbox/production enum, it was handled internally inside the library.

I am verifying the subscription after user logs in and also during the purchase. Although these two are mutually exclusive, if there is already active subscription I won't show the UI for purchasing the one. It is meant to be a 'guard' code just in case not to trigger purchase flow for subscription that is already purchased if some bug finds its way.

But I am worried about one scenario:

- if calling `completeTransactions` (non-atomic) once on AppStartup while there is no signed in user inside the app I won't know which user to update on server. So I just call `SwiftyStoreKit.finishTransaction(product.transaction)`. Later when user logs in, this user would gain 'isPremiumUser' privileges since there is currently one active subscription on the AppStore which has been checked by the "Verify Subscription API".
I guess I need to see with my client if it is acceptable and if we need to move subscription validation on the server to make it more robust.

During the subscription purchase flow I am doing non-atomic purchase and am calling `SwiftyStoreKit.finishTransaction(product.transaction)` only after I update the server flag. In `completeTransactions` API I just call `SwiftyStoreKit.finishTransaction(product.transaction)` without notifying the server.

**Comment by bizz84** [comment]
@Dino4674 According to [Validating Receipts With the App Store](https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html#//apple_ref/doc/uid/TP40010573-CH104-SW1):

> Use a trusted server to communicate with the App Store. Using your own server lets you design your app to recognize and trust only your server, and lets you ensure that your server connects with the App Store server. It is not possible to build a trusted connection between a user’s device and the App Store directly because you don’t control either end of that connection.

Regarding this:

> During the subscription purchase flow I am doing non-atomic purchase and am calling SwiftyStoreKit.finishTransaction(product.transaction) only after I update the server flag. In completeTransactions API I just call SwiftyStoreKit.finishTransaction(product.transaction) without notifying the server.

I don't think that this is correct in this scenario:
* Start a subscription purchase 
* Close or kill the app while the purchase is being processed (in this case, iOS will continue the purchase even after the app is killed)
* Start the app again, which calls `completeTransactions()`
* `completeTransactions()` will return the purchased product immediately in the callback
* call `finishTransaction()` without notifying the server

In this case the purchase is completed successfully, but you have unlocked the functionality in your server, which means the user has paid for the subscription but the content was not delivered.

To fix this, you should always check `needsFinishTransaction` and update the server accordingly as documented [in the README](https://github.com/bizz84/SwiftyStoreKit#complete-transactions):
```swift
if product.needsFinishTransaction {
  // Deliver content from server, then:
  SwiftyStoreKit.finishTransaction(product.transaction)
}
```

Maybe it would make sense to **not** let the user make the purchase (by hiding the UI) if she's not logged in?

Alternatively you could delay calling `finishTransaction` **until** the user has signed in. If you do that, you will keep getting a callback from `completeTransactions()` every time you start the app.

**Comment by Dino4674** [comment]
Since server is not doing the validation (it will in the future) I think it is good for now. Thanks for the AppStore quote, I'll communicate this to my client also.

> Maybe it would make sense to not let the user make the purchase (by hiding the UI) if she's not logged in?

If user is not logged in, she would see login/signup screens which don't show purchase options so this is good.

I've implemented it like this:
- on app startup I call complete transactions and just finish them since at that moment app can be in 2. states (no logged in user during previous app session -> user did logout, or app could have one serialized user which it would use for skipping the login/register screens presenting).

- then when app is about the present main app screens I check the subscriptions state and server's value. And based on those two I update server. Now current logged in user is in sync with app store subscription.

- if app is killed during the purchase, transaction would finish on next startup and app would update server based on this 'after login' logic.

**Comment by bizz84** [comment]
@Dino4674 I'll close this for now. Feel free to reopen if you have other questions.

**Comment by Erumaru** [comment]
> Call verifySubscription when the app launches to check if your subscriptions is active or expired. Use this to update your server.

When I call verifySubscription at app start it asks for AppleID password, even if user is logged in AppStore. Is it right behavior of sandbox environment or it will be the same on the production? If so, it's terrible :(

**Comment by Erumaru** [comment]
> Call verifySubscription when the app launches to check if your subscriptions is active or expired. Use this to update your server. 

App would always ask for log in to Appstore at app start? Isn't it terrible?

**Comment by Erumaru** [comment]
@bizz84 Please give your response.

**Comment by bizz84** [comment]
@Erumaru The app shouldn't show the App Store sign in, especially if the user is already signed in.

That being said, [a lot of people are complaining](https://twitter.com/marcoarment/status/910156134450892800) about login popups.

I heard some rumors that things are better on iOS 11.3 beta. Maybe give it a try?
