### ISSUE TITLE
Auto-renewable subscription do not renews

### ISSUE THREAD

**Issue by ramunasjurgilas** [bizz84/SwiftyStoreKit#195]
### Platform
- [x] iOS
### In app purchase type
- [ ] Auto-Renewable Subscription
### Environment
- [ ] Sandbox
### Version
master (0.6.3) Installed throw CocoaPods

### Related issues
Auto-renewable subscription do not gets renewed. 

### Issue summary
After purchasing auto-renewable subscription, and after 5 min subscription gets expired.
I want to notice, that by executing restore or refresh receipt and doing subscription verification it sill show expired. 

### What did you expect to happen
I am expect that auto-renewable subscription will be extended 5 times.

**Comment by bizz84** [comment]
@ramunasjurgilas to clarify, this is the expected behaviour:

* just after you purchase your auto-renewable subscription in Sandbox mode, calling `verifySubscription()` should return `.purchased`.

* If you wait until after the `expiryTime` and call `verifySubscription()` again, you should get `.expired`

Is this not what you're observing?

**Comment by ramunasjurgilas** [comment]
My question is not about it, but I am interesting in this stuff as well and I commented bellow.

My problem was that I was struggling to understand why auto-renewable subscriptions usually expires after first 5 minutes and they do not gets extended for another 5 min. As in the Apple documentation is written that subscription term for 1 month in the sandbox environment it is 5 min and it will be renewed 5 times. From my observation I noticed that it gets extended 5 times for 5 minutes only once in 12 hours period. Did you observe same behavior?


You did touch good point about .purchased and .expired. During testing auto-renewed subscription receipts are not downloaded automatically. In this case user should click **Restore Purchase** and with restore new receipt will be download. It is not nice behavior UI interaction if user needs very month to hit restore purchase. I would expect that iOS will download automatically receipts and user will not need to hit **Restore Purchase**. 
What do you think should not be receipts download automatically?

**Comment by iwasrobbed** [comment]
>When testing auto-renewable subscriptions in the test environment, keep in mind that the duration times are compressed. **Additionally, test subscriptions only auto-renew a maximum of six times** [per day]

via https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnectInAppPurchase_Guide/Chapters/TestingInAppPurchases.html

**Comment by bizz84** [comment]
@iwasrobbed good reference.

@ramunasjurgilas You don't need to restore purchases to check if a subscription is valid or not. You can use the [`verifySubscription`](https://github.com/bizz84/SwiftyStoreKit#verify-subscription) method instead.

I'm closing this issue, but feel free to reopen if you have any more questions.
