### ISSUE TITLE
how to check if the product was purchased or not.

### ISSUE THREAD

**Issue by nsoud** [bizz84/SwiftyStoreKit#20]
ho to check if a product was previously purchased
Thank you very much

**Comment by bizz84** [comment]
There is no API in SwiftyStoreKit for this. You could do the following:
* Once the user makes a purchase the first time after installing the app, store the purchase information locally, for example using the keychain. You can then query you keychain anytime to see if the product has been purchased
* One advantage of using the keychain is that the information will still be there even if the user deletes and reinstalls the app. See this [answer](http://stackoverflow.com/questions/18911434/will-items-in-ios-keychain-survive-app-uninstall-and-reinstall).
* If you don't use the keychain, you can still rely on the restore purchases call to be requested by the user after she has reinstalled the app.

**Comment by acegreen** [comment]
@bizz84 A side question related to this. Does this library have a function to check expiration of a subscription? I would to check somewhere if the subscription is valid and then take away privileges if it expires.
