### ISSUE TITLE
Unable To Verify Non-Renewing Subscription - (could not parse receipt item)

### ISSUE THREAD

**Issue by manky** [bizz84/SwiftyStoreKit#208]
### Platform

- [ X] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ X] Non-Renewing Subscription

### Environment

- [ X] Sandbox
- [ ] Production

### Version
0.9.1

### Related issues
N/A

### Issue summary

**web_order_line_item_id** is missing in ReceiptInfo but is exptected to be there acording to
InAppReceipt.swift line 49

`extension ReceiptItem {

    public init?(receiptInfo: ReceiptInfo) {
        guard
            let productId = receiptInfo["product_id"] as? String,
            let quantityString = receiptInfo["quantity"] as? String,
            let quantity = Int(quantityString),
            let transactionId = receiptInfo["transaction_id"] as? String,
            let originalTransactionId = receiptInfo["original_transaction_id"] as? String,
            let purchaseDate = ReceiptItem.parseDate(from: receiptInfo, key: "purchase_date_ms"),
            let originalPurchaseDate = ReceiptItem.parseDate(from: receiptInfo, key: "original_purchase_date_ms"),
            let webOrderLineItemId = receiptInfo["web_order_line_item_id"] as? String
            else {
                print("could not parse receipt item: \(receiptInfo). Skipping...")
                return nil
        }`

**Error**:
`could not parse receipt item: ["product_id": product.id, "transaction_id": 1000000298268385, "purchase_date_pst": 2017-05-12 01:19:09 America/Los_Angeles, "original_purchase_date_ms": 1494577149000, "is_trial_period": false, "original_purchase_date_pst": 2017-05-12 01:19:09 America/Los_Angeles, "quantity": 1, "purchase_date_ms": 1494577149000, "purchase_date": 2017-05-12 08:19:09 Etc/GMT, "original_purchase_date": 2017-05-12 08:19:09 Etc/GMT, "original_transaction_id": 1000000298268385]. Skipping...
receipt has 1 items, but only 0 were parsed`

### What did you expect to happen
To verify receipt

### What happened instead
Skipping receipt

**Comment by vovkasmprigarin** [comment]
Problem with `let webOrderLineItemId = receiptInfo["web_order_line_item_id"] as? String`, because iTunes doesn't include this param in response, and all block under guard became failed :(

I'am catch it problem in `verifyPurchase` method.

You need fixed this method. Not good if this happens in released apps.

**Comment by bizz84** [comment]
@manky thanks for reporting! Fixed on version [0.9.2](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.9.2).
