### ISSUE TITLE
No such module

### ISSUE THREAD

**Issue by tylermrolfe** [bizz84/SwiftyStoreKit#209]
### Platform

- [X] iOS
- [ ] macOS
- [ ] tvOS

### Version
0.9.1

### Issue summary
Getting a weird "No such module 'SwiftyStoreKit'" I've done all the normal carthage checks like the run script file etc..I am on the latest version of carthage also. I've had this framework in my project for a little while now and this is first time I've had this issue.

**Comment by tylermrolfe** [comment]
Worth noting, the following warnings appear in Xcode
- ../Carthage/Build/iOS/SwiftyStoreKit.framework/Modules/SwiftyStoreKit.swiftmodule/arm64.swiftmodule is missing from working copy
- /Carthage/Build/iOS/SwiftyStoreKit.framework/Modules/SwiftyStoreKit.swiftmodule/arm.swiftmodule is missing from working copy
- Carthage/Build/iOS/SwiftyStoreKit.framework/Modules/SwiftyStoreKit.swiftmodule/arm.swiftdoc is missing from working copy
- Carthage/Build/iOS/SwiftyStoreKit.framework/Modules/SwiftyStoreKit.swiftmodule/i386.swiftdoc is missing from working copy

**Comment by tylermrolfe** [comment]
I've tried everything I can possibly think of and still no luck. Any ideas?

**Comment by bizz84** [comment]
Apologies. Haven't had time to look into this yet. Can someone try creating a new project and set it up with Carthage?

**Comment by robhellstrom** [comment]
I've had this a few times in the current Xcode. However I learnt to ignore it. I simply closed and reopened Xcode and it all worked. Sometimes just closing and reopening the project or even rebuilding was enough. Hope this helps. I don't like ignoring problems but on a tight deadline you sometimes don't have a choice.

**Comment by bizz84** [comment]
I have just created a new project on Xcode 9 and configured it to use SwiftyStoreKit as a framework with Carthage.

Everything went smoothly.

Closing this for now, feel free to reopen if it's still a problem.
