### ISSUE TITLE
Get a list of all products available from products ids

### ISSUE THREAD

**Issue by tbaranes** [bizz84/SwiftyStoreKit#21]
In my current application, I have a list of IDs clear to sales from the API, to be sure which ones I can show to the user, I need to verify which products are available or not on Apple side.

I though about using `retrieveProductInfo`, but that will create one request per product. One easy solution would be to create `retrieveProductsInfo`  which could take an array of product ids, and return the ids available in the completion block.

What do you think?

**Comment by bizz84** [comment]
I agree. Will try to look into this over the weekend.

**Comment by bizz84** [comment]
I implemented a proposal for this here:
https://github.com/bizz84/SwiftyStoreKit/pull/23

It's an API breaking change so I'm planning to leave the pull request open for one or two days to see if there is any feedback before merging it in.

Feel free to try it out :)

**Comment by bizz84** [comment]
PR merged. Closing
