### ISSUE TITLE
All alerts in macOS sample crash

### ISSUE THREAD

**Issue by zeromhz** [bizz84/SwiftyStoreKit#211]
### Platform

- [ ] iOS
- [X] macOS
- [ ] tvOS

### In app purchase type

- [X] Consumable
- [X] Non-consumable 
- [X] Auto-Renewable Subscription
- [X] Non-Renewing Subscription

### Environment

- [X] Sandbox
- [X] Production

### Version
0.9.2

## Report

Running the macOS sample on 10.12.x every time the sample shows an alert it crashes. To repro simply build the sample, run it, and click any of the buttons (presuming there is a proper IAP configuration behind it.)

SwiftyStoreKit_macOSDemo[8253:544747] [General] -[NSAlert beginSheetModalForWindow:completionHandler:] may only be invoked from the main thread. Behavior on other threads is undefined.

Putting the alert on the main thread fixes it but I'm not sure this is the right answer. 

### Issue summary
macOS sample crashes any time an alert is shown

### What did you expect to happen
alert should show

### What happened instead
app crashes

**Comment by bizz84** [comment]
Fixed on [release 0.9.3](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.9.3).
