### ISSUE TITLE
AppleReceiptValidator Set to .production but keep seeing [Environment: Sandbox] When trying to Purchase IAP

### ISSUE THREAD

**Issue by Jayvd** [bizz84/SwiftyStoreKit#219]
### Platform

- [*] iOS

### In app purchase type
- [*] Auto-Renewable Subscription

### Environment
- [ *] Production

### Version
ℹ Latest

### Issue summary
ℹ I have set the Apple Receipt Validator to `.production` but I keep seeing [Environment: Sandbox] text at the bottom of the prompt alert when trying to purchase an IAP.

### What did you expect to happen
ℹ No [Environment: Sandbox] texts?

**Comment by robhellstrom** [comment]
Can you confirm whether the scenario is limited to Apple's tests or your own? For instance, when Apple tested my app and shared screenshots they still saw sandbox despite it being marked .production.

**Comment by bizz84** [comment]
@Jayvd If you're running from Xcode, I think this is expected.

If your app is live and you download it from the app store everything should be fine.

It may also depend on whether you're using a sandbox user or a registered Apple ID.

**Comment by bizz84** [comment]
@Jayvd I'm going to close this issue. If you still have problems/questions, feel free to reopen.
