### ISSUE TITLE
Xcode 8 Carthage Build uses Swift 3.1

### ISSUE THREAD

**Issue by neilt** [bizz84/SwiftyStoreKit#226]
### Platform

- [X] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [X] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [X] Sandbox
- [ ] Production

### Version
0.10.3 SwiftyStoreKit, built using Carthage.
$ xcode-select --print-path
/Applications/Xcode.app/Contents/Developer
Xcode command line tools used for Carthage build are using Xcode Version 8.3.2 (8E2002)

### Issue summary
Problem shows up when trying Xcode 9.
Module compiled with Swift 3.1 cannot be imported in Swift 4.0: ...../Build/iOS/SwiftyStoreKit.framework/Modules/SwiftyStoreKit.swiftmodule/x86_64.swiftmodule

Other frameworks built using Carthage in the same project are not reported as errors. (SwiftyDropbox, XCGLogger).

### What did you expect to happen
To work.

### What happened instead
Build failed.

**Comment by bizz84** [comment]
@neilt Apologies for the late reply. Haven't had time to look into this yet.

- [ ] Did you start from a clean build?
- [ ] Can you build a new sample project that uses SwiftyStoreKit as the only Carthage dependency?

**Comment by neilt** [comment]
I am no longer able to reproduce this, so I am closing it.
