### ISSUE TITLE
[question] Best way to validate subscription

### ISSUE THREAD

**Issue by gloffreda** [bizz84/SwiftyStoreKit#229]
Hi there

I'm implementing the framework and would like to know, profiting of your experience with in-app purchases, whats is the best way to validate if a subscription still valid ?

I can do it on both sides, client and server, but can't figure the best fit.

Can you help me ?

Thank you
Giulio

**Comment by iwasrobbed** [comment]
See example here: https://github.com/bizz84/SwiftyStoreKit/issues/153

If you only have an iOS version, then just do it on the client side.
If the subscription is used across multiple clients (e.g. web, iOS, android), have your server do the validation.

**Comment by bizz84** [comment]
@gloffreda You can read the [Receipt Verification](https://github.com/bizz84/SwiftyStoreKit#receipt-verification) section on the README.

I'm going to close this issue. Feel free to reopen if you have more questions.
