### ISSUE TITLE
"Purchase successful" response comes back in result.error 

### ISSUE THREAD

**Issue by phalladar** [bizz84/SwiftyStoreKit#231]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
0.10.3

### Issue summary
After my `purchaseProduct` call I get a `PurchaseResult` error object that contains the following: 

`SKError(_nsError: Error Domain=SSServerErrorDomain Code=0 "You’re all set." UserInfo={NSLocalizedDescription=You’re all set.})`

### What did you expect to happen
I would expect a successful purchase would trigger the `success` case with a PurchaseDetails object.

### What happened instead
I received the above SKError.

**Comment by mdmrachev23** [comment]
The same problem! Please, fix it as soon as possible. It's really critical for our project!

**Comment by bizz84** [comment]
@phalladar @mdmrachev23 not sure how to reproduce this.

Can you post a stack trace and the code you're using?

Also can you try to modify the SwiftyStoreKit demo app to use your in-app purchase (make sure the bundle ID matches) an see if you get the same error?

**Comment by SebastianBO** [comment]
How did you solve this?

**Comment by hlung** [comment]
Getting this also..

**Comment by geodesicer** [comment]
Any update on this? @hlung @bizz84 @mdmrachev23

**Comment by bizz84** [comment]
If this is still an issue I would suggest creating a very basic demo using `StoreKit` directly and file a radar with Apple.

**Comment by sam961** [comment]
I dont know if it is the same problem with me ... The  autorenewable process is working fine on my device, but it was refused about 5 times from apple.
<img width="333" alt="screen shot 2017-08-15 at 10 08 43 am" src="https://user-images.githubusercontent.com/4921874/29305501-c0ba81ba-81a1-11e7-8952-caa1498a64d9.png">
They always send this message that appears on their side.
This popup is invoked in the following function 

let appleValidator = AppleReceiptValidator(service: .production)
SwiftyStoreKit.verifyReceipt(using: appleValidator, password: "your-shared-secret") { result in
    switch result {
    case .success(let receipt):
      
    case .error(let error):

   **# ///HERE I POP UP THE MESSAGE, WHAT COULD BE THE PROBLEM?**
        print("Receipt verification failed: \(error)")
    }
}

**Comment by Sam-Spencer** [comment]
This seems like an old issue on Apple's side. Should there be further discussion or questions related to this issue, it can be reopened. Thank you.
