### ISSUE TITLE
How to get rid off Cydia in-app purchase hack

### ISSUE THREAD

**Issue by RajChanchal** [bizz84/SwiftyStoreKit#232]
### Platform

- [ ] iOS

### In app purchase type

- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox

### Version
ℹ 0.10.3

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ A few users of my app has starting take advantage of Cydia and started getting free in-app purchases. They are using this way: https://www.drgeeky.com/localiapstore-hack-in-app-purchases-ios-910-iphone-tutorial/
The cancel button cause the in-app purchase to success block!

### What did you expect to happen
ℹ It should call error block, it's working fine without the Cydia way.

### What happened instead
ℹ `SwiftyStoreKit.purchaseProduct` method's result happens to be a `success` case, instead of `error`.

**Comment by fishcharlie** [comment]
@RajChanchal Is this really a SwiftyStoreKit problem? Sounds more like an Apple problem. SwiftyStoreKit just integrates with Store Kit and Apple. If Apple doesn't return an error SwiftyStoreKit won't return an error.

**Comment by bizz84** [comment]
@RajChanchal @fishcharlie Indeed, this is one for Apple to fix.

Closing this issue as it's not part of the scope of SwiftyStoreKit.

**Comment by RajChanchal** [comment]
@bizz84 ok, I will look into it to find out how can we get rid off this problem. A few of my users got most of the trick and are enjoying free resources without paying... If you happen to find out anything, do let me know here. Thanks
