### ISSUE TITLE
Consumable receipt validation confusion 

### ISSUE THREAD

**Issue by ashishfission** [bizz84/SwiftyStoreKit#237]
### Platform

- [* ] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ *] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ *] Sandbox
- [ ] Production

### Version
ℹ 0.10.3

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

## Report
Consumable Purchase
### Issue summary
case .purchased(let receiptItem):
                    print("Product is purchased")
                    print ("Product is purchased Product will not expire")
                case .notPurchased:
                    print("This product has never been purchased")
                    print("Not purchased This product has never been purchased")
                }

### What did you expect to happen
ℹ Purchased validation "Product is purchased"

### What happened instead
 returning :   "This product has never been purchased" ,Not purchased This product has never been purchased

**Comment by bizz84** [comment]
From [Apple Docs - Delivering Products](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/DeliverProduct.html#//apple_ref/doc/uid/TP40008267-CH5-SW16):

> Information about consumable products is added to the receipt when they’re paid for and remains in the receipt until you finish the transaction. After you finish the transaction, this information is removed the next time the receipt is updated—for example, the next time the user makes a purchase.

> Information about all other kinds of purchases is added to the receipt when they’re paid for and remains in the receipt indefinitely.

In other words, receipt validation is not useful for consumable products.
You should keep track of your purchase on the completion block of `SwiftyStoreKit.purchaseProduct()`.

**Comment by bizz84** [comment]
@ashishfission I'm going to close this issue. Feel free to comment if you have further questions.
