### ISSUE TITLE
retrieveProductsInfo working in simulator, not with users

### ISSUE THREAD

**Issue by netfoxuser** [bizz84/SwiftyStoreKit#238]
### Platform

- [x ] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [x] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x] Production

### Version
0.10.3

### Issue summary
I use retrieveProductsInfo to get a local currency value (the price of a non-consumable app purchase), and display this in a UILabel to the user. In simulator everything works perfectly, but on a device not. No value is being displayed. 

This is the code I use:

```
SwiftyStoreKit.retrieveProductsInfo(["xxxxxxxx"]) { result in
                    if let product = result.retrievedProducts.first {
                        let priceString = product.localizedPrice!
                        self.row4column2b.text = "\(priceString)"
                    }
                }
```

**Comment by Axcic** [comment]
Got the same problem. Just reload my device and everything works fine later
