### ISSUE TITLE
Detect user already purchased the app(itself)

### ISSUE THREAD

**Issue by Davtyanag** [bizz84/SwiftyStoreKit#246]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### Environment

- [ ] Sandbox
- [x] Production

### Issue summary
I'm moving my app from paid applications to free with IAP. I would like to know if it's possible to detect  if user bought an app before becoming free or not. Can I do that via SwiftyStoreKit? If so how can I test that?

**Comment by whitepixelstudios** [comment]
This solution has nothing to do with SwiftyStoreKit but the simplest way to do this, in my opinion, would be to:
Release a version well-ahead of time (so people don't skip it) while the app is still paid that would set a value in iCloud keychain that says they had the app before it became free.
You could then check for this value in future versions, and if set, act as though they've purchased the IAP.

**Comment by Davtyanag** [comment]
Thank you @whitepixelstudios for the answer. There is a solution via validating Appstore receipt and fetching original application version and comparing that to new app version. I did that via using and modifying another library, looks like SwiftyStoreKit doesn't support that.

**Comment by robertodias180** [comment]
@Davtyanag what lib did you use? I am faced with the same issue.

Thanks

**Comment by Davtyanag** [comment]
@robertodias180 https://github.com/crashoverride777/SwiftyReceiptValidator

**Comment by robertodias180** [comment]
@Davtyanag thanks for the info 👍  Also can you share the changes that you had to make?

**Comment by Davtyanag** [comment]
@robertodias180 https://github.com/Davtyanag/SwiftyReceiptValidator
The library didn't have error callback.
That's how I use changed library(fork), and the code on the bottom shows how I use it, "some text" in arguments doesn't matter, I don't use it.
SwiftyReceiptValidator.validate(forIdentifier: "some text", sharedSecret: nil) { (success, response,error) in
            if success {
                // example 2 (auto-renewable subscriptions)
                let receiptInfoFieldKey = SwiftyReceiptValidator.ResponseKey.receipt.rawValue
                if let receipt = response?[receiptInfoFieldKey]{
                    if let applicationVersion = receipt[SwiftyReceiptValidator.InfoKey.original_application_version.rawValue] as? String {
                        if applicationVersion <= "1.2" {
                            let alert = self.alertWithTitle("Purchases are restored".localized, message: "All purchases have been restored".localized)
                            self.showAlert(alert)
                            self.successfullyPurchased()
                            self.hideLoadingHUD()
                            NetworkActivityIndicatorManager.networkOperationFinished()
                            return
                        }
                    }
                }
                self.restoreAction()
            } else {
                if !(error?.domain == "SSErrorDomain" && error?.code == 16) {
                    self.restoreAction()
                } else {
                    self.hideLoadingHUD()
                    NetworkActivityIndicatorManager.networkOperationFinished()
                }
            }
        }

**Comment by robertodias180** [comment]
@Davtyanag thanks 😃

**Comment by Davtyanag** [comment]
@robertodias180 finally formatted comment, u r welcome

**Comment by umbrella-daniil-vorobyev** [comment]
Well, it seems to me that there is no legal way to heck it on development. Testflight / sandbox both always return the original_application_version = 1.0

**Comment by tobeglad** [comment]
I tested only local receipt validation, and original_application_version contains only build number (one number), not a full version.

I will try to validate receipt via apple server. Maybe this way I will be able to retrieve full version (like 1.x.x.x)
