### ISSUE TITLE
Calling finishTransaction after verify subscription is purchased? not expired.

### ISSUE THREAD

**Issue by htarwara6245** [bizz84/SwiftyStoreKit#252]
### Platform

- iOS

### In app purchase type

- Auto-Renewable Subscription

### Environment

- Sandbox
- Production

### Version
Latest

First of all, correct me if I am wrong about this. I am trying to do auto-renewable subscription. I want to know why finishTransaction is called before verifying subscription?

Here is my current logic that I want to do : 

**Purchase -> Success -> Verify -> if .Purchased => call to my API for updating user status => Then finishTransaction**

```
// First it will do purchase
        SwiftyStoreKit.purchaseProduct(productID, atomically: false) { result in
            
            // When it success, it will return recepit. Mean Apple officially reduct the money from your account
            if case .success(let purchase) = result {

                // Then we validate the receipt from the server to AppStore for double check
                // First we check via client [client to AppStore]
                // Please turn these into .production when release
                let appleValidator = AppleReceiptValidator(service: .sandbox) // .production
                SwiftyStoreKit.verifyReceipt(using: appleValidator, password: Constants.StoreConnect.SecretKey) { result in
                    
                    if case .success(let receipt) = result {
                        let purchaseResult = SwiftyStoreKit.verifySubscription(
                            type: .autoRenewable,
                            productId: productID,
                            inReceipt: receipt)
                        
                        switch purchaseResult {
                        case .purchased(let expiryDate, let receiptItems):
                            // Second we check via server [server to AppStore] by sending receipt and secret-code                   // Deliver content from server, then:
                           // Here we send receipt to our server again and let it verify, and then deliver premium content
                            // Then when it success
                            if purchase.needsFinishTransaction {
                                   SwiftyStoreKit.finishTransaction(purchase.transaction)
                             }    

                        case .expired(let expiryDate, let receiptItems):
                            
                            failure("Product is expired or cancel subscription")
                            
                            log.info("Product is expired since \(expiryDate)")
                            log.info("Last Receipt Product : \(receiptItems.last?.productId)")
                            log.info("Last Receipt OriginalPurchaseDate : \(receiptItems.last?.originalPurchaseDate)")
                            log.info("Last Receipt ExpireDate : \(receiptItems.last?.subscriptionExpirationDate)")
                            
                        case .notPurchased:
                            
                            log.info("This product has never been purchased")
                            
                        }
                        
                    } else {
                        failure("Receipt Verification Error")
                    }
                }
            } else {
                failure("Product Cannot Purchase")
            }
        }
```

Correct me if I am wrong about this. I checked using your verifyReceipt as well as after it was completed, it check again at my server with apple and then deliver the content and set finishTransaction. Any Help?

**Comment by bizz84** [comment]
Hi @htarwara6245,

I think you may have a problem because you try to verify the receipt before you call `finishTransaction`.

I can't find documentation for this on the Apple docs, but I think that in this case you won't get a receipt item for your purchase until you have finished the transaction.

Can you check that if this is the case?

**Comment by htarwara6245** [comment]
Ahh I see, you mean `finishTransaction` should be called before verifying the receipt in order to get the receipt from Apple right? I thought it should be called after payment is completed from my server side. Because I thought after verifying the receipt, I will get the latest receipt from AppStore and I send the receipt back to my server to check and activate subscription. Looks like I have to deliver the content after verify is completed right?

**Comment by bizz84** [comment]
I think the correct order of things is:

1. call `purchaseProduct` with `atomically = false`
2. on the completion block, deliver content from your server
3. Once the content is unlocked, call `finishTransaction`
4. To check if the subscription is still active, call `verifyReceipt` and `verifySubscription`

**Comment by htarwara6245** [comment]
My current flow was : 

1. call `purchaseProduct` with `automically = false`
2. on the completion block, I didn't deliver the content yet from the server
3. then I call `finishTransaction`.
4. then I first check the subscription with the Apple Server by using `verifyReceipt` and `verifySubscription` from the client side
5. when `verifySubscription` purchased, I send the receipt to the my server again to do validation, server-side to Apple Store Server again.
6. then the server return `success` based on it's latest receipt by checking expired data
7. then i deliver the content.

I want to know something,too. When `.expired` is called at `verifySubscription` and correct me If I am wrong about my above flow. I just double-check at server side and deliver the content.
