### ISSUE TITLE
How to handle restore process for Auto-Renewable Subscription

### ISSUE THREAD

**Issue by htarwara6245** [bizz84/SwiftyStoreKit#253]
### Platform

- iOS

### In app purchase type

- Auto-Renewable Subscription

### Environment

- [ ] Sandbox
- [ ] Production

### Version
ℹ Latest Version

Any Help, I still can't figure it out how to handle restore process for this? After verify, it got the receipt that it was .purchased or .expired right? then how can we finishTransaction without calling purchaseProduct?

**Comment by bizz84** [comment]
There is no concept of _restoring_ a subscription. The only time you would call `finishTransaction` is when you purchase it (or when you complete transactions).

Afterwards, if you want to check if the subscription is still valid or not, you can just verify the subscription as outlined here:

https://github.com/bizz84/SwiftyStoreKit#verify-subscription

**Comment by htarwara6245** [comment]
I am afraid that Apple will reject my app for missing restore button since mine was subscription based app. Everything is working at server-side. So, for the restore state, I will do `verifyReceipt` and `verifySubscription` every time the user come into the application.

**Comment by iwasrobbed** [comment]
@htarwara6245 I believe you're correct. There's a bit of clarifying information here as well: https://github.com/bizz84/SwiftyStoreKit/issues/207

You can hook the restore button up to `refreshReceipt` or the `verifyReceipt` -> `verifySubscription` method and check that they have subscribed to one of your subscription options.

**Comment by iwasrobbed** [comment]
Seems there's more information here as well: https://github.com/bizz84/SwiftyStoreKit/issues/194

It appears you need to enumerate over your product identifiers and call `verifySubscription` on each. The `restorePurchases` method will be "successful" even if a subscription is expired, which seems like a bug to me.

Could you clarify this @bizz84? The rest of the API is very clear (great work overall)

**Comment by iwasrobbed** [comment]
I've included some sample code here for how I'm doing this: https://github.com/bizz84/SwiftyStoreKit/issues/194#issuecomment-320405655

**Comment by htarwara6245** [comment]
@iwasrobbed  thanks for your help, I will take a look into. Also in a mean while, looking for any good suggestions.

**Comment by bizz84** [comment]
@iwasrobbed That's correct, calling `restorePurchases` will return all non-consumable products and subscriptions that were previously purchased, regardless of whether they are expired or not.

To check subscription validity, use `verifyReceipt` and `verifySubscription`.

I will update the README accordingly.

**Comment by iwasrobbed** [comment]
@htarwara6245 Mind leaving this issue open until the readme is updated?
