### ISSUE TITLE
Verify Purchase Crash

### ISSUE THREAD

**Issue by nicwhitts** [bizz84/SwiftyStoreKit#256]
### Platform

- [ x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [x ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x ] Sandbox
- [ ] Production

### Version
0.10.5
## Report

> unrecognized selector sent to instance 0x14d71a90
> Printing description of receipt:
> ▿ 3 elements
>   ▿ 0 : 2 elements
>     - .0 : "environment"
>     - .1 : Sandbox
>   ▿ 1 : 2 elements
>     - .0 : "status"
>     - .1 : 0
>   ▿ 2 : 2 elements
>     - .0 : "receipt"
>     ▿ .1 : 18 elements
>       ▿ 0 : 2 elements
>         - .0 : receipt_type
>         - .1 : ProductionSandbox
>       ▿ 1 : 2 elements
>         - .0 : app_item_id
>         - .1 : 0
>       ▿ 2 : 2 elements
>         - .0 : original_purchase_date_ms
>         - .1 : 1375340400000
>       ▿ 3 : 2 elements
>         - .0 : original_purchase_date
>         - .1 : 2013-08-01 07:00:00 Etc/GMT
>       ▿ 4 : 2 elements
>         - .0 : download_id
>         - .1 : 0
>       ▿ 5 : 2 elements
>         - .0 : request_date
>         - .1 : 2017-08-11 19:33:41 Etc/GMT
>       ▿ 6 : 2 elements
>         - .0 : request_date_ms
>         - .1 : 1502480021547
>       ▿ 7 : 2 elements
>         - .0 : original_purchase_date_pst
>         - .1 : 2013-08-01 00:00:00 America/Los_Angeles
>       ▿ 8 : 2 elements
>         - .0 : receipt_creation_date_ms
>         - .1 : 1502480018000
>       ▿ 9 : 2 elements
>         - .0 : in_app
>         ▿ .1 : 1 element
>           ▿ 0 : 11 elements
>             ▿ 0 : 2 elements
>               - .0 : original_purchase_date_ms
>               - .1 : 1502473112000
>             ▿ 1 : 2 elements
>               - .0 : original_transaction_id
>               - .1 : 1000000323833974
>             ▿ 2 : 2 elements
>               - .0 : purchase_date_pst
>               - .1 : 2017-08-11 10:38:32 America/Los_Angeles
>             ▿ 3 : 2 elements
>               - .0 : purchase_date_ms
>               - .1 : 1502473112000
>             ▿ 4 : 2 elements
>               - .0 : quantity
>               - .1 : 1
>             ▿ 5 : 2 elements
>               - .0 : original_purchase_date
>               - .1 : 2017-08-11 17:38:32 Etc/GMT
>             ▿ 6 : 2 elements
>               - .0 : is_trial_period
>               - .1 : false
>             ▿ 7 : 2 elements
>               - .0 : original_purchase_date_pst
>               - .1 : 2017-08-11 10:38:32 America/Los_Angeles
>             ▿ 8 : 2 elements
>               - .0 : product_id
>               - .1 : com.test.app.unlimited
>             ▿ 9 : 2 elements
>               - .0 : transaction_id
>               - .1 : 1000000323833974
>             ▿ 10 : 2 elements
>               - .0 : purchase_date
>               - .1 : 2017-08-11 17:38:32 Etc/GMT
>       ▿ 10 : 2 elements
>         - .0 : receipt_creation_date
>         - .1 : 2017-08-11 19:33:38 Etc/GMT
>       ▿ 11 : 2 elements
>         - .0 : request_date_pst
>         - .1 : 2017-08-11 12:33:41 America/Los_Angeles
>       ▿ 12 : 2 elements
>         - .0 : receipt_creation_date_pst
>         - .1 : 2017-08-11 12:33:38 America/Los_Angeles
>       ▿ 13 : 2 elements
>         - .0 : bundle_id
>         - .1 : com.test.app
>       ▿ 14 : 2 elements
>         - .0 : adam_id
>         - .1 : 0
>       ▿ 15 : 2 elements
>         - .0 : application_version
>         - .1 : 1
>       ▿ 16 : 2 elements
>         - .0 : version_external_identifier
>         - .1 : 0
>       ▿ 17 : 2 elements
>         - .0 : original_application_version
>         - .1 : 1.0
> Printing description of receipts:
> expression produced error: error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=2, address=0x7c30c).
> The process has been returned to the state before expression evaluation.

### Issue summary
Trying to verify a successful purchase, but app crashes with above error

I have copy pasted code from the iOS example but changed to use my own product id (which works because the purchase is successful) But struggling to see why this crashes..

### What did you expect to happen
Verify success

### What happened instead
Breakpoint crash on line:
`        let receipts = receipt["receipt"]?["in_app"] as? [ReceiptInfo]
` in file InAppReceipt.swift

**Comment by bizz84** [comment]
@nicwhitts Apologies for the late reply.

Can you put a breakpoint on that line and check if `receipt["receipt"]` exists?

What about `receipt["receipt"]?["in_app"]`?

**Comment by bizz84** [comment]
@nicwhitts can you try this with #283 and see if it solves the problem?

**Comment by bizz84** [comment]
This should have been fixed in version 0.11.0.

Closing this issue. If it still crashes, please reopen or create a new one.
