### ISSUE TITLE
URGENT!!! Change Text of Alert Message.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [bizz84/SwiftyStoreKit#260]
### Platform

- [ ] iOS

### In app purchase type

- [ ] Non-consumable 

### Environment

- [ ] Sandbox

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

I want to change the Text of Alert Message.

**Comment by bizz84** [comment]
Which alert message? What are you trying to do? Purchase a product? A subscription? Restore Purchases?

Your question is more likely to be answered and of more value to other users if you fill in all details in the issue template.

**Comment by Rashesh-Bosamiya** [comment]
Purchase a Product.

**Comment by Rashesh-Bosamiya** [comment]
I am doing In-App for the first time.
I am using this library.
Can you tell me what _Restore Purchase_ does?

**I am request you to keep in touch with me for few days. because I am new to In-App Purchase Development. I might require your help for couple of weeks until this module gets done.**

**Comment by Rashesh-Bosamiya** [comment]
_SwiftyStoreKit.verifyReceipt()_ 

This thing present Alert Controller saying..."Sign In to iTunes Store Enter the password for your Apple ID"

Is there any possible way to stop appearing this Alert ?

**Comment by wrutkowski** [comment]
@Rashesh-Bosamiya how can you request anything? This library is open source and big thanks to @bizz84 for creating and maintaining it in the first place!

@Rashesh-Bosamiya please describe what is the issue that you are experiencing. If you are unable to do so this issue should be closed.

**Comment by gapl** [comment]
The alert you are seeing is the default alert from the iOS platform and there is no control over that. The system could not possibly know what to restore, if the user would not be signed in.

I recommend reading through a good iAP tutorial, there are loads of those around the interwebs before jumping into such a cool library such as this.

If you look closely at this repo, you will see that there are no instances of any `UIAlertXXXX` family classes. This issue can be closed.

**Comment by bizz84** [comment]
Well answered by @gapl. Closing.
