### ISSUE TITLE
How to get cancellation_date with Non-Renewing Subscription?

### ISSUE THREAD

**Issue by tezheng** [bizz84/SwiftyStoreKit#271]
### Platform

- [] iOS

### In app purchase type

- [ ] Non-Renewing Subscription

### Question
Will SKReceiptRefreshRequest append cancellation_date to the receipt if a user report problems to Apple and get refund?

If not, is there a way to get the up-to-date receipt?

So far I can see that if a user 
1. Make a purchase of a Non-Renewing Subscription item
2. Refund it
3. Then purchase another item
The cancellation_date will be append the to receipt, but I wonder if it is possible to know this after step 2? 

Thanks.

**Comment by bizz84** [comment]
@tezheng Apologies for the very late reply.

`SwiftyStoreKit.verifySubscription` filters out any cancelled items - and treats them as if the product was never purchased. So this does not work well for your use case.

To get around this, you could parse the receipt yourself manually and get all the information you need:

```swift
let appleValidator = AppleReceiptValidator(service: .production, sharedSecret: "your-shared-secret")
SwiftyStoreKit.verifyReceipt(using: appleValidator, forceRefresh: false) { result in
    switch result {
    case .success(let receipt):
        // TODO: parse the receipt and read out the cancellation date
    case .error(let error):
        print("Verify receipt failed: \(error)")
	}
}
```

Relevant article: [Apple - Working with subscriptions](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html#//apple_ref/doc/uid/TP40008267-CH7-SW5)

**Comment by bizz84** [comment]
@tezheng I just found this on Apple Docs:

[How do I use the cancellation_date field?](https://developer.apple.com/library/content/technotes/tn2413/_index.html#//apple_ref/doc/uid/DTS40016228-CH1-RECEIPT-HOW_DO_I_USE_THE_CANCELLATION_DATE_FIELD_)

Quoting:

> Important: cancellation_date is not currently added for consumable and non-renewing subscription products.

So according to the docs the cancellation_date should not appear. Is this in line with what you see?

**Comment by bizz84** [comment]
@tezheng I believe my comment above answers your question, so I'm closing this issue. Feel free to reopen if you have more queries.
