### ISSUE TITLE
Consumable In-app-purchases not finished correctly

### ISSUE THREAD

**Issue by phillipthelen** [bizz84/SwiftyStoreKit#275]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [x] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
0.10.8

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
When trying to use finishTransaction with consumable in-app-purchases, the transactions are not finished. The next time the item is purchased the store responds that the item has already been purchased and will be restored. Calling completeTransactions also still returns this purchase and claims it needs finishing.

### What did you expect to happen
The consumable in-app-purchase transaction is finished and does not show up as needsFinishing anymore

### What happened instead
Consumable in-app-purchase is not finished and prevents any further purchases.

**Comment by charvoa** [comment]
Same problem, I was supposed to release my app in production tomorrow but with this bug I cannot do this right now ... Did you find anything ? 

Thanks !

**Comment by bizz84** [comment]
@vIiRuS @charvoa I'm trying to do some testing on this but I'm only getting failed transactions at the moment.

Are you experiencing this on iOS 11 only, or iOS 10 and below?

**Comment by charvoa** [comment]
iOS 11. But I was not calling finishTransactions properly , also I added the code below to my app delegate (as read in the README.md) : 

`func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    SwiftyStoreKit.completeTransactions(atomically: true) { purchases in
        for purchase in purchases {
            if purchase.transaction.transactionState == .purchased || purchase.transaction.transactionState == .restored {
                if purchase.needsFinishTransaction {
                    // Deliver content from server, then:
                    SwiftyStoreKit.finishTransaction(purchase.transaction)
                }
                print("purchased: \(purchase)")
            }
        }
    }
    return true
}`

**Comment by bizz84** [comment]
@charvoa if you use `atomically: true`, `purchase.needsFinishTransaction` should be `false`.

Can you put a breakpoint on `if purchase.needsFinishTransaction {` and test?

Does this work for you now?

Things [seem quite broken](https://forums.developer.apple.com/message/261428#261428) on iOS 11 sandbox at the moment so I'm unable to test purchases.

**Comment by sinarionn** [comment]
Any news? (can't open your link on apple forum)
I'm facing similar strange behavior - at some moment my consumable purchases start showing me message "This in-app purchase has already been bought. It will be restored for free". 
Im calling purchase with atomically = true, so it should call finishTransaction automatically. 
During debug session i found that finishTransaction was called properly, but when we adding new Purchase (same kind as before) to PaymentQueue and queue notifies "updatedTransactions" transactions array contains same instance of SKPaymentTransaction as in previous successfull purchase.

**Comment by maomorales** [comment]
Hi everyone- did someone manage to figure out how to solve it? my team started to face this same issue recently and don't know what to do. We were considering the native implementation instead.

Any feedback will be very appreciated. Thanks!

**Comment by muzammil-triffort** [comment]
Any fixes? Please help.
