### ISSUE TITLE
Non-Consumable: IPv6 App Store Review Rejection.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [bizz84/SwiftyStoreKit#276]
### Platform

- [ ] iOS

### In app purchase type

- [ ] Non-consumable 

### Environment

- [* ] Sandbox
- [ *] Production

### Version
ℹ Please replace this with the LATEST of SwiftyStoreKit you're using.

### Related issues
#81 

## Report
My Application has Non-Consumable In-App Purchase. I submitted for review.
Apple review team has rejected the App, due to IPv6 network error.

**Your app crashed on iPad running iOS 11.0.2 connected to an IPv6 network after we purchased the in-app purchase products.**

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by rebeloper** [comment]
When the Apple Review Team rejects apps with the IPv6 reason, it's most probably NOT an IPv6 reason. Their response is a generic one. What I found out through my experience is that you are most probably missing out on a step setting up your IAP. It's not SwiftyStoreKit that has a bug or whatnot. Please check your setup steps. See my YouTube video on a detailed walkthrough: https://www.youtube.com/watch?v=hcl2gqg5aJQ

**Comment by bizz84** [comment]
I'll treat this as a duplicate of #81 and close it.

**Comment by jaybowong** [comment]
@rebeloper The link is broken.
