### ISSUE TITLE
Retrieve Issue for v0.2.7

### ISSUE THREAD

**Issue by atjason** [bizz84/SwiftyStoreKit#28]
If disconnect network connection and try to retrieve product list, will only get error of "No bag entry". It's better using better string if could figure it out.

BTW, did you consider to localise the error strings? There're some choices.
- You can let volunteers help to translate. 
- Or let the developer to translate in their own projects.

**Comment by bizz84** [comment]
All the errors in the project are not meant to be user-facing.

SwiftyStoreKit often returns errors received in the delegate calls of the StoreKit APIs such as:
   - `request:didFailWithError:`
   - `paymentQueue:restoreCompletedTransactionsFailedWithError:`

In other cases, non-localized errors are created on the fly. While I agree that some error strings could be more meaningful, I believe the most appropriate user-facing error messages should be decided by the hosting applications, not by SwiftyStoreKit.

What do you think?

**Comment by bizz84** [comment]
This should be at least partially addressed by this PR: 
https://github.com/bizz84/SwiftyStoreKit/pull/31

**Comment by atjason** [comment]
@bizz84 Update: Fixed with Version 0.2.10
