### ISSUE TITLE
App Store Promotions Error :  delegate does not respond to method paymentQueue:shouldAddStorePayment:forProduct

### ISSUE THREAD

**Issue by gitton** [bizz84/SwiftyStoreKit#282]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In-app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
0.10.8
## Report
```
SwiftyStoreKit.shouldAddStorePaymentHandler = { (_ payment: SKPayment, _ product: SKProduct) in
            // check if user can purchase the product
return true
}
```

Added this handler after SwiftyStoreKit.completeTransactions and the following error is shown but  this handler is called after this error message is shown

### Issue summary
 

 [Daemon] [SKPaymentQueue]: Tried to send purchase intent: "inapppurchase id ", delegate does not respond to method paymentQueue:shouldAddStorePayment:forProduct

**Comment by dayjer** [comment]
Did you solve this? I've implemented as you have and see the same error. Thanks

**Comment by CFIFok** [comment]
I have this error too. But 2020 is already outside!

**Comment by punjasin** [comment]
also found this

**Comment by zrxq** [comment]
Having the same issue.

**Comment by yositsa** [comment]
Same here!
