### ISSUE TITLE
New confirmation purchases view. 

### ISSUE THREAD

**Issue by Bonusik** [bizz84/SwiftyStoreKit#286]
### Platform

- [x ] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x ] Sandbox
- [ ] Production

### Version
0.10.8

### Issue summary
Could you please tell me how can I obtain a view of buiyng the subscription from the first screenshot (expected) instead of view shown on the second screenshot (happened). I am working on iOS 11. 

### What did you expect to happen
![img_0502](https://user-images.githubusercontent.com/9887189/31495807-4fc69594-af59-11e7-9006-3ce7488d7438.PNG)

### What happened instead
![img_0007](https://user-images.githubusercontent.com/9887189/31495825-58cc21a4-af59-11e7-80bf-d59933de770d.PNG)

**Comment by bizz84** [comment]
Good question. Had a quick look but couldn't find documentation for this.

Ideas anyone?

**Comment by Ziph0n** [comment]
Any update on this?

**Comment by Bonusik** [comment]
New confirmation view is on iOS 11.0.2, the old one from 11.0.0

**Comment by funkenstrahlen** [comment]
I still see the old one on iOS 11.2 in sandbox environment. Maybe the new one is only available in production?

**Comment by bizz84** [comment]
Can anyone confirm this? I don't have apps with auto-renewable subscriptions to test in production.

**Comment by JustinGanzer** [comment]
I think I might have the answer!

During sandbox testing the view does indeed look like this.
HOWEVER, once I downloaded my own app from the app store, the new confirmation purchase view appears instead.

**Comment by bizz84** [comment]
@Bonusik this seems confirmed as a difference between sandbox and production.

I'm closing this issue for now, but feel free to reopen if needed.
