### ISSUE TITLE
Purchase Issue for v0.2.7

### ISSUE THREAD

**Issue by atjason** [bizz84/SwiftyStoreKit#29]
- If first purchase `net.toolinbox.ihosts.plus`, then try to purchase `net.toolinbox.ihosts.pro`. The Mac App Store part is correct (show the password dialog, confirm dialog, "Thank You" for purchase succeed dialog), but in `paymentQueue`, beside 2 transaction of `Purchasing` state, only get a transaction with id of `net.toolinbox.ihosts.plus` which was `continued`. And then no more transaction is called, thus the complete handler of purchase is never called.
![purchase_0](https://cloud.githubusercontent.com/assets/803199/14881709/c5a0e2f0-0d67-11e6-87c4-321bec5a409d.jpg)

  - I manually cancel the purchasing and purchase again, it will return `.Purchased` even I haven't input password.
![purchase_2](https://cloud.githubusercontent.com/assets/803199/14881719/cd7fbce4-0d67-11e6-85ac-763469896d39.jpg)

- In your demo of 'alertForPurchaseResult', doesn't deal with the case user cancel purchasing.
- In `SwiftyStoreKit.purchaseProduct`, if the product identifier is empty string, the complete handler will not be called.

**Comment by bizz84** [comment]
@atjason I have registered a new OS X app and two in app purchases so that I can test this on OS X, however I get an 'Invalid Product Identifier' error when I try to retrieve products info.

I have also tried with the test account you sent me before but getting the same problem so I can't test on OS X yet. Are you able to send me login+password for a test account that works?

**Comment by atjason** [comment]
@bizz84 I just test again with the account I ever sent to you: bizz***3. I could successfully purchase one of the product. Didn't meet the issue of 'Invalid Product Identifier'. Strange you can't do it in your side.

Any way, I just create another test account and sent to you by email. Please let us if it doesn't work.

**Comment by bizz84** [comment]
I get this:

<img width="482" alt="retrieve-failed" src="https://cloud.githubusercontent.com/assets/153167/14951501/50186f70-1051-11e6-9762-58f079390832.png">

What bundle ID are your using to register your app? I think it only works if the hosting app has the same bundle ID that is associated to the in app purchases.

**Comment by atjason** [comment]
The bundle id is "net.toolinbox.ihosts", just the beginning part of the product id. Have a try.

**Comment by bizz84** [comment]
Same thing:

<img width="961" alt="retrieve failed" src="https://cloud.githubusercontent.com/assets/153167/14951933/50d75540-1054-11e6-95ad-514781174b0d.png">

<img width="957" alt="purchase failed" src="https://cloud.githubusercontent.com/assets/153167/14951931/4c5d21a2-1054-11e6-80f8-d99b516f6308.png">

I have signed out of iTunes on my Mac, however the app doesn't ask me to sign in to my Apple ID, only shows these errors.

**Comment by atjason** [comment]
@bizz84 there're dozens of possible reason for the "Invalid Production Identifier" issue. Please refer to this check list: [http://troybrant.net/blog/2010/01/invalid-product-ids/](http://troybrant.net/blog/2010/01/invalid-product-ids/)

I'm afraid you can't use my product identifiers for the reason like provision file or others. Perhaps you need to find out why the product you created is treated as invalid. Please double check the provision file in [https://developer.apple.com/account/mac/profile/production](https://developer.apple.com/account/mac/profile/production). Note: try the provision used for production, but not for development.

Maybe you just need to wait for some time, or reboot computer ^_^

**Comment by atjason** [comment]
Some other tips you can try:

- Enable the sandbox mode. Enable the 'Outgoing connections (Client)' and 'In-App Purchases' in project settings.
- Signing using 'Mac App Store' in project settings.

**Comment by atjason** [comment]
@bizz84 Update: Fixed with Version 0.2.10.
