### ISSUE TITLE
Extra argument 'sharedSecret' in call

### ISSUE THREAD

**Issue by yakupad** [bizz84/SwiftyStoreKit#290]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
ℹ 0.10.8

let appleValidator = AppleReceiptValidator(service: .production, sharedSecret: "your-shared-secret")
Extra argument 'sharedSecret' in call

**Comment by bizz84** [comment]
@yakupad `sharedSecret` has been introduced in version [0.11.0](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.11.0).

Please update to the latest version.
