### ISSUE TITLE
it's only for swift ? not for oc?

### ISSUE THREAD

**Issue by luoganzhi** [bizz84/SwiftyStoreKit#291]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [ ] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by bizz84** [comment]
As [discussed here](https://github.com/bizz84/SwiftyStoreKit/issues/123), support for Objective-C is missing and is not planned for the future.
