### ISSUE TITLE
VerifyReceipt does not return type ReceiptItem on .success

### ISSUE THREAD

**Issue by electic** [bizz84/SwiftyStoreKit#293]
### Platform

- [ x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [ x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ x] Sandbox
- [ ] Production

### Version
0.11.0

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

## Report

`let appleValidator = AppleReceiptValidator(service: .production, sharedSecret: "your-shared-secret")
SwiftyStoreKit.verifyReceipt(using: appleValidator) { result in
    switch result {
    case .success(let receipt):`

This code returns a dictionary. I was expecting a ReceiptItem or an array of items. Not sure.

**Comment by bizz84** [comment]
@electic `verifyReceipt` returns is a dictionary:

```swift
public typealias ReceiptInfo = [String: AnyObject]
```

This can then be parsed manually or with the convenience `verifyPurchase` or `verifySubscription` methods.

If this answers your question, please close this issue.

**Comment by electic** [comment]
Hi,

That makes sense. The issue is that the user might chnage plans in the same group .For example, if they go from a 12 month plan to a six month plan. This creates an array of expired receipts and I do not quite know the subscription plan they are on as to verify it matches with my cached copy. I ended up doing it this way:

`SwiftyStoreKit.verifyReceipt(using: appleValidator) { result in
            switch result {
                case .success(let receipt):
                    let purchases = receipt["receipt"]?["in_app"] as! [NSDictionary]
                    let productID = purchases.last!["product_id"] as! String
                    
                    if let product = self.returnProduct(productIdentifier: productID) {
                        let purchaseResult = SwiftyStoreKit.verifySubscription(
                            type: .autoRenewable, // or .nonRenewing (see below)
                            productId: productID,
                            inReceipt: receipt)

**Comment by bizz84** [comment]
@electic currently there are no helper methods in SwiftyStoreKit for subscription groups. So implementing your own logic is the way to go for now.

**Comment by electic** [comment]
Got it, wanted to make sure. Not sure if this could be a feature request but will leave that up to you to decide :) Thanks again for a great library!
