### ISSUE TITLE
carthage, Xcode 9.1 9B55, Module compiled with Swift 4.0 cannot be imported in Swift 3.2.2

### ISSUE THREAD

**Issue by zhudengdengdeng** [bizz84/SwiftyStoreKit#295]
### Platform

- [ ] iOS
- [x] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by bizz84** [comment]
@zhudengdengdeng apologies for the late reply.

Can you try to do a clean build and see if it happens again? I have seen this error with Carthage in other projects and cleaning all temp files did solve the problem for me.

**Comment by zhudengdengdeng** [comment]
@bizz84 I've tried several times before, but I will try again later. Thanks for your reply.

**Comment by bizz84** [comment]
@zhudengdengdeng was this resolved? We can close the issue if so.

**Comment by zhudengdengdeng** [comment]
@bizz84 Sorry that not notified you, it's solved.
