### ISSUE TITLE
RestorePurchases call comes back empty sometimes 

### ISSUE THREAD

**Issue by Jevon718** [bizz84/SwiftyStoreKit#297]
### Platform

- [ ] iOS

### In app purchase type
- [ ] Non-consumable 

### Environment
- [ ] Sandbox

### Version
0.10.8

### Related issues
N/A

### Issue summary
When I call `restorePurchases` sometimes fires back a result and sometimes it doesn't.  I have noticed that if I wait awhile after purchasing it works.  Is this because some time has to go by on Apple's side before restoring can work or do you think my code is possibly flawed?

It's just a button in an alert view.  From testing, I know for a fact your `restorePurchases` call is happening `restoreFailedPurchases` is coming back empty.

### What did you expect to happen
`restoredPurchases` to have a value in it.
### What happened instead
Sometimes `restoredPurchases` is empty. 

    SwiftyStoreKit.restorePurchases(atomically: true, completion: { results in
         for purchase in results.restoredPurchases {
             if purchase.needsFinishTransaction {
                 SwiftyStoreKit.finishTransaction(purchase.transaction)
             }
             guard purchase.productId == MyProducts.fullJulianDate.rawValue else { return }
             self.receiptHelper.importIAPsFromReceipt()
             self.restoreSuccessDelegate?.restoreSuccess()   
       }
    })

**Comment by bizz84** [comment]
@Jevon718 Apologies for the late reply.

Can you try using the code [in the README](https://github.com/bizz84/SwiftyStoreKit#restore-previous-purchases) to check what you get?

```swift
SwiftyStoreKit.restorePurchases(atomically: true) { results in
    if results.restoreFailedPurchases.count > 0 {
        print("Restore Failed: \(results.restoreFailedPurchases)")
    }
    else if results.restoredPurchases.count > 0 {
        print("Restore Success: \(results.restoredPurchases)")
    }
    else {
        print("Nothing to Restore")
    }
}
```

It could be a timing issue as you said.

Potentially you could change your approach and use [receipt verification](https://github.com/bizz84/SwiftyStoreKit#receipt-verification) to restore previously purchased products (this is the Apple recommended way).
