### ISSUE TITLE
InAppProductPurchaseRequest sometimes returns an error when starting a purchase

### ISSUE THREAD

**Issue by bizz84** [bizz84/SwiftyStoreKit#3]
Sometimes an early error is raised in the payment queue when making a purchase, even though the purchase is still in progress.

**Comment by AlexCatch** [comment]
I get this error occasionally. It makes the library unusable in Production.

**Comment by bizz84** [comment]
I haven't been able to determine exactly when this happens. Do you have any more information that could help me reproducing the issue?

**Comment by odedharth** [comment]
@bizz84 was the error solved? I wondering whether I should use the library for production

**Comment by bizz84** [comment]
I have not had the chance to investigate further. It's unclear when it happens or why. If anyone has more insight or knows how to fix this, please let me know or send me a PR.

**Comment by bizz84** [comment]
@odedharth This _should_ now be resolved. Please test pod version 0.2.7 with your app.

**Comment by bizz84** [comment]
@odedharth Closing this. Feel free to reopen if this is still a problem.
