### ISSUE TITLE
What is `applicationUsername` for?

### ISSUE THREAD

**Issue by usamabinattique** [bizz84/SwiftyStoreKit#300]
### Platform

- [x] iOS

### In app purchase type

- [x] Non-consumable 

### Environment

- [x] Sandbox

### Version
SwiftyStoreKit version: 0.11.0

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
In the purchase method, we have two types one takes only the product id and completion block and the other takes in atomicBool and applicationUserName as well. I am really confused as to what am i supposed to give in the application user name, and clearly this has been updated because it isn't mentioned anywhere in the documentation, ps i went over stack and browsed this section as well. i couldn't find anything. Please update the documentation or let me know what should be the application user name?

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by bizz84** [comment]
@usamabinattique apologies for the late reply.

I found this page from [Apple Docs](https://developer.apple.com/documentation/storekit/skmutablepayment/1506088-applicationusername).

Quoting:

> Use this property to help the store detect irregular activity. For example, in a game, it would be unusual for dozens of different iTunes Store accounts to make purchases on behalf of the same in-game character.

> The recommended implementation is to use a one-way hash of the user’s account name to calculate the value for this property.

Not sure if this helps?

**Comment by bizz84** [comment]
This is a question about StoreKit (SwiftyStoreKit only exposes this), so I'm closing this issue.

If you have more queries, feel free to ask.
