### ISSUE TITLE
Error when validating receipt in Production [Promo Code]

### ISSUE THREAD

**Issue by florinmatinca** [bizz84/SwiftyStoreKit#301]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [x] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x] Production

### Version
ℹ 0.11.0 

### Issue summary
ℹ I have an app in production and a user can redeem a promo code for an in-app purchase item. I did that using a real account, not a sandbox one. I want to Debug this before implementing the validation in the app and for that I try to verify receipt first by using the code :

```
SwiftyStoreKit.verifyReceipt(using: AppleReceiptValidator(service: .production), password: "2783929eeXXXXXXXXXXXXXX") { result in
            switch result {
            case .success(let receipt):
                
            case .error(let error):
                
            }
        }
```

Each time I got the error "Cannot connect to iTunes Store".

Is this related to the production environment ?

**Comment by WillMays1** [comment]
I am getting this same error. Have tried everything to get it working. Could someone look at my code and find the issue?

**Comment by bizz84** [comment]
@florinmatinca @WillMays1 Possibly a bug with Apple? See this thread from Apple Developer forums:

https://forums.developer.apple.com/thread/67935

**Comment by Sam-Spencer** [comment]
Has anyone had any luck / updates on this?
