### ISSUE TITLE
App Store login popup appearing all the time!

### ISSUE THREAD

**Issue by funkenstrahlen** [bizz84/SwiftyStoreKit#307]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
`0.11.0`

### Issue summary

I call `verifyReceipt` and `verifySubscription` in `applicationDidFinishLaunchingWithOptions` to verify that the user is still a valid subscriber of my premium service.

Right now in Test Flight beta testing I see the App Store login alert popping up every time I open the app. This is very annoying.

Is there a better best practise way to verify subscription status? I know Apple recommends doing this via my own server, but I do not want to go this way.

### What did you expect to happen
No popup to sign in. Verification runs in the background.

### What happened instead
Right now in Test Flight beta testing I see the App Store login alert popping up every time I open the app.

**Comment by arslanraza** [comment]
@funkenstrahlen I am facing the same issue. Were you able to find a fix for this one yet ?

**Comment by funkenstrahlen** [comment]
I could not find out the source of the issue. It looks like it does refresh the receipt from the App Store. However after looking at the code this should not happen because the receipt is already stored on disk.

I will try to find out more via debugging.

**Comment by SirComet** [comment]
I had the same issue, its an issue of sandbox I think because once in production it doesn't happen.

just make sure you are verifying  in production and not in sandbox.

**Comment by funkenstrahlen** [comment]
@SirComet Thank you for your answer! How can I be sure this does not happen in production too? There seems to be no way to test this via Testflight because this will use the Sandbox backend too.

**Comment by funkenstrahlen** [comment]
I read about a way to test this but have not confirmed yet:

* change release settings to manual release
* submit app in iTunes connect for review
* wait for approval
* create promo code to install the unreleased app version on your device
* test subscriptions

**Comment by funkenstrahlen** [comment]
I did some debugging on this. Subscription verification runs with the commands listed above perfectly fine and seems to have nothing to do with the login popup.

I found a suggestion that I have an unfinished transaction. However I can not see any transaction being passed to me in applicationDidBecomeActive. I also am sure to finish all transactions correctly.

Any further ideas?

**Comment by comobiophys** [comment]
I have the same issue. And I don't want to release to production until anyone can confirm that problem is from sandbox env.
Need help!

**Comment by funkenstrahlen** [comment]
* I do not refresh the receipt in background from iTunes. The popup even occurs when I remove all of my IAP code.
* I did not use a separate sandbox account to test the subscription IAP. I downloaded the app from TestFlight and used my normal account as it is possible according to Apple. This will also use the sandbox backend tough.
* I checked for unfinished transactions: Nothing. I even called restoreTransactions to replay all transactions and finish them in case, but everything looks correct.
 
The request for password I see is for my actuall AppleID but in the sandbox environment.
 
The weird thing is: This seems to happen very randomly. Sometimes it takes 20s after I launch the app until the popup occurs. All of my code that has something to do with subscriptions is finished already (verified through logging). I feel like my code has NOTHING to do with this popup.
 
I did not have this issue before working with IAP. However even installing an old version from TestFlight which does not have any IAP in it does bring up the popup now.
 
I am really out of ideas why this does happen.

**Comment by zdesiree** [comment]
Same problem here, I hoped this has something todo with the sandbox environment and submitted the app anyway but Apple rejected it because of "Unable to access app due to 'Sign In to iTune Store' prompt". When I remove all my IAP code it stops appearing. Happy for any help and suggestions.

**Comment by bizz84** [comment]
@funkenstrahlen thank you for the report and apologies for the late reply.

Yes, the login popup is something that I have previously seen myself and I suspect it is to do with unfinished transactions. I have even seen it appearing randomly while using other apps, likely because once a purchase is started, it can continue even if the app is backgrounded or killed.

Like everyone else, I don't have clear reproduction steps and I haven't found a reliable way of testing this in sandbox / production.

I'll try to spend a bit of time on this and see if I can be of any help.

**Comment by funkenstrahlen** [comment]
> When I remove all my IAP code it stops appearing.

Interesting. This did not have the same effect for me.

> Yes, the login popup is something that I have previously seen myself and I suspect it is to do with unfinished transactions.

This was also my initial thought and is also suggested on many forum threads. However how can I debug this? All approaches to find out what's going on did not help:

I added logging to my code in App Delegate that does check for new unfinished transactions. It does reliably get called when the subscription does auto renew and it finishes the transaction. I can confirm it finished because it does not appear in the queue again.

I also can confirm the popup is not related to an unfinished transaction that is hanging in the queue because of messing around with iTunes Connect sandbox users. I see this error also on test devices that only have seen the app version I released via Test Flight. On these devices I only use the main device Apple ID to test the IAP. On these devices the popup does also appear very often.

Very weird: Even after removing the app from my devices I still sometimes see the popup requesting a login?! This really confuses me.

Previously I talked about this approach to test in production:

> I read about a way to test this but have not confirmed yet:
> change release settings to manual release
> submit app in iTunes connect for review
> wait for approval
> create promo code to install the unreleased app version on your device
> test subscriptions

This does only work if the app is not released on the App Store yet. As I am working on an app update to include subscriptions this does not work for me.

**Comment by bizz84** [comment]
I discovered a bug in `completeTransactions` that may (or may not) be relevant. See #322.

**Comment by bizz84** [comment]
This issue may be related to #288.

**Comment by funkenstrahlen** [comment]
This is the code I execute in App Delegate when my app is launched:

```swift
    static func completeIAPTransactions() {
        SwiftyStoreKit.completeTransactions(atomically: true) { purchases in
            var isVerifySubscriptionRequired = false
            
            for purchase in purchases {
                if purchase.needsFinishTransaction {
                    SwiftyStoreKit.finishTransaction(purchase.transaction)
                }
                switch purchase.transaction.transactionState {
                case .purchased, .restored, .failed: isVerifySubscriptionRequired = true
                default: break
                }
            }
            
            if isVerifySubscriptionRequired {
                verify(.premiumOneYear)
            }
        }
    }
```

As I use `atomically: true` this is probably not the source of my problem.

**Comment by bizz84** [comment]
@funkenstrahlen Do your popups look like this?

![8 sign-in-to-itunes-store](https://user-images.githubusercontent.com/153167/34319015-e401858c-e7cd-11e7-844f-2250a48e5c3a.jpg)

![3 apple-id-verification](https://user-images.githubusercontent.com/153167/34319014-e08e9700-e7cd-11e7-806d-c37bf2253675.jpg)

I have seen them randomly appearing outside the app.

**Comment by funkenstrahlen** [comment]
I run via TestFlight. The popup looks like this for me (explicitly referring to the sandbox environment).

![img_0105](https://user-images.githubusercontent.com/144173/34319115-c15c6af4-e7d9-11e7-8a8b-e2fc603b7c51.png)

I also see the popup in your second screenshot but this only happens when I logout of my regular Apple ID in iOS settings App Store and use a special sandbox testing account. When running in TestFlight I do not see the seconds kind of popup. I also do not feel like the "login in settings" popup is related to the issue.

**Comment by bizz84** [comment]
@funkenstrahlen To diagnose your problem, I would try to determine if the login popup is triggered by `completeTransactions()` or `verifyReceipt()`. At the moment you call both.

Could you try the following scenarios in AppDelegate and report in which cases the popup appears?

* Don't call anything
* Call `completeTransactions()` only
* Call `verifyReceipt()` only

**Comment by funkenstrahlen** [comment]
@bizz84 I already did have this idea and tried to investigate exactly like this. I learned that even if I do not call anything the popup still appears. See https://github.com/bizz84/SwiftyStoreKit/issues/307#issuecomment-351359669

**Comment by bizz84** [comment]
@funkenstrahlen If you don't call anything and still get a popup then I can only think somehow there is some internal state set by StoreKit at the system level for your app. 

Nasty issue this is. It would really help if we could get consistent reproduction steps.

Maybe I'll try to test a few scenarios, write down steps and take screenshots.

**Comment by funkenstrahlen** [comment]
@bizz84 Yes this is really a difficult issue because it is so hard to debug.

I am currently running a version of my app on my device directly from the App Store. This version does not contain any IAP code (this is the old version). I do not get the popup at every app launch now. It still does appear from time to time though. It even does popup 10 times repeating then! So weird :O

**Comment by bizz84** [comment]
@funkenstrahlen I also noticed the login popup outside the app even though all the transactions are finished. 

After some research, I found this:

https://stackoverflow.com/questions/38828163/skpaymentqueue-does-not-finish-skpaymenttransaction-for-an-auto-renewable-subscr

I think what is happening is that auto-renewable subscriptions add new transactions to the queue when they get renewed. This can be particularly annoying in sandbox mode as the durations are compressed:

```
1 week : 3 minutes
1 month : 5 minutes
2 months : 10 minutes
3 months : 15 minutes
6 months : 30 minutes
1 year : 1 hour
```

So it could be that StoreKit adds new transactions and these trigger the popup at random times. 

This theory is also confirmed as sometimes I get new transactions in `completeTransactions` for auto-renewable subscriptions I purchased before.

A few things to test:

- In production, do the subscriptions auto-renew without triggering the login popup if the user is logged in?
- In sandbox, do we ever get login popups if we configure the app with any IAPs other than auto-renewable subscriptions?

**Comment by funkenstrahlen** [comment]
@bizz84 You are right. I am aware that auto-renewable subscriptions do automatically renew 6 times in the sandbox environment. I did confirm with logging that the auto-renew process is registered as a new transaction in my app and gets finished successfully. This is why I know I can process new transactions in App Delegate successfully when they actually appear in the queue.

I understand your idea that this can cause the popup to appear even when the app is not running. However I also see this popup after all 6 renew transactions are finished and my app goes back to invalid subscription purchase state because the user is no longer premium.

**Comment by bizz84** [comment]
@funkenstrahlen I've been doing some testing with a weekly subscription on sandbox.

### Test 1

When purchasing a subscription, I got this message:

![subscriptionlogic](https://user-images.githubusercontent.com/153167/34441425-9b62bffe-ecb3-11e7-972f-69a69f908161.jpg)

After the purchase, I've been able to verify that every three minutes I get a new item in the receipt.
However, no transactions show up until I restart the app and `completeTransactions()` captures them.

### Test 2

I purchased a subscription, and logged out of my sandbox account in Settings.

- After three minutes, no more items were added to the receipt.
- Restarting the app also didn't capture any more transactions in `completeTransactions()`

So it looks like signing out stops the subscriptions from renewing (maybe this is what the message about cancelling a subscription in Settings means).

----

Still, no answer to the random login popups.

**Comment by funkenstrahlen** [comment]
> However, no transactions show up until I restart the app and completeTransactions() captures them.

As far as I know this is how it is supposed to be?

> So it looks like signing out stops the subscriptions from renewing (maybe this is what the message about cancelling a subscription in Settings means).

I do not think this is correct. Signing out should have no effect on subscription renewal. However as long as your are signed out you will not get transaction updates in the app of course.

The message about subscription cancelation in Settings is not working in sandbox mode. This message is intended to production use because you can get to your manage subscriptions page from iOS Settings. This is only available for real Apple IDs. Sandbox subscriptions can not be cancelled manually. This is why they stop renewing automatically after 6 renewals.

**Comment by huyduc** [comment]
Hi, just want to chip in, we've been observing incessant login popup for _consumable_ iap, not subscription. It's been quite a nightmare for our Beta tester as the popup shows 10-20 times a day

**Comment by R0uter** [comment]
Hello there, however I use the _non-consumable_ iap, it also does popup.

And for my experience, it can be reproduce through TestFlight:
1.download your app from tf
2.then you buy iap use your REAL Apple ID
3. once you do it, _sign in required_ even if you are using other app.

> ( One more thing, my issue seems it only popup when you open the test app and after your network status changed, eg:from wifi to 4G, from 4G to wifi)

**Comment by Vaberer** [comment]
I have just got into this situation as well. I'll try to explain my use case:
I already have created a non-consumable in-app purchcase on iTunes connect. some time ago. It works without any problem.

I am just implementing subscriptions. After creating a subscription on iTunes connect and testing it with my real account in the app, the popup starts appearing.

Even if I remove all the code related to SwiftyStore Kit, the popup is showing all the time.

I'm really frustrated.

**Comment by funkenstrahlen** [comment]
What about the possibility this is no issue in this framework but actually a bug from Apple?

**Comment by zdesiree** [comment]
For me the popup always appears when verifying the receipt. But because I do it on app launch of course to check on the expiration time of the subscription it always appears on launch. I already refactored to a plain implementation of StoreKit without any framework but it still happens. But maybe this really is the "infinite loop" and an unfinished transaction is alreay in the queue  and so also affects me with and without framework? Apple keeps rejecting my app because of the issue so I have no chance to test if it would be working in production.

**Comment by Vaberer** [comment]
![img_0239](https://user-images.githubusercontent.com/8090436/34985919-fa873afe-fab5-11e7-9a65-38d584fb2259.jpg)

This is what happened right now, it's my real apple id this is what I saw. I think my apple id is somehow broken when I was testing subscriptions:(

**Comment by snake302** [comment]
Same problem here.

Little detail: I have got purchased 2 subscriptions from one group.

**Comment by funkenstrahlen** [comment]
Has anyone discovered the source of the problem yet? Or even a solution?

I still can not figure out what's happening. This is definitely not the infinite loop problem many threads are talking about.

**Comment by R0uter** [comment]
Update: My app has been proved by apple review and status changes into `pending developer release`  for now,  App Store login still popup when network status changes.

**Comment by bizz84** [comment]
I have found this interesting blog post today. It seems relevant to this issue:

https://medium.com/revenuecat-blog/testing-in-app-purchases-ruins-your-phone-3751665ca5c1

**Comment by R0uter** [comment]
Update: I have changed my app state in to ready for sale, then download it from App Store, after I input my password in test flight popup, everything seems great, no popups anymore.

**Comment by joehribar** [comment]
My app that has auto-renewable subscriptions is also getting the repeated sandbox password prompt. I'm testing subscriptions through TestFlight, and every time I open the app (fresh launch or returning from the background), I get the prompt—even when the subscription is expired. The production version of the app seems to work just fine.

I did hear other developers say iOS 11.3 fixes the issue, so I installed the developer beta, and sure enough, the repeated prompts are no longer happening. Anyone else with this problem able to test on iOS 11.3?

**Comment by Danny182** [comment]
same issue here. Noticed that:
`    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        print("first")      
        SwiftyStoreKit.completeTransactions(atomically: true) { purchases in
            print(purchases.count)
            print("second") //never gets printed
            for purchase in purchases {
                switch purchase.transaction.transactionState {
                case .purchased, .restored:
                    if purchase.needsFinishTransaction {
                        // Deliver content from server, then:
                        SwiftyStoreKit.finishTransaction(purchase.transaction)
                    }
                // Unlock content
                case .failed, .purchasing, .deferred:
                    break
                }
            }
        }

        return true
    }`

The "second" print never gets printed.

**Comment by funkenstrahlen** [comment]
My guess is that the callback only gets called when there is actually a purchase in the queue. Just take a look at the source code. It’s all here.

We can discuss of course if this is a good expected behaviour of this callback or not. But this should be the topic of another thread maybe? What do you think?

**Comment by funkenstrahlen** [comment]
I have one user on test flight beta who reported the login popups are fixed since he upgrade to 11.3 beta. I could not test this myself yet though.

**Comment by Danny182** [comment]
I'm continuously getting the login popup (sandbox). 
If nothing is inside the queue I don't understand where is the problem.

**Comment by funkenstrahlen** [comment]
> If nothing is inside the queue I don't understand where is the problem.

Now you have reached the same dead end as everybody else in this thread.

**Comment by bloodmajik** [comment]
Hi. Wondering if anyone has resolved this issue?!

**Comment by R0uter** [comment]
Sadly, no. However it will go away when user download your app from App Store.

**Comment by bloodmajik** [comment]
Is this 100%? That means it only doesn't work on TestFlight?

**Comment by R0uter** [comment]
Sence I published my app to Appstore, it has been 7 days, all good now.......

**Comment by bloodmajik** [comment]
One more question: do you receive a lag between sign in and the pop up that says purchase?

**Comment by R0uter** [comment]
sometimes? I don't think so.

**Comment by djvolz** [comment]
I've been dealing with the exact same issues for auto-renewables as everyone else in this thread.  Hopefully 11.3 becoming widely available will put this to rest for future IAP implementers.

**Comment by ovdm** [comment]
I have the same issue. I suspect it is because iOS is automatically checking the the app receipt. 

When you do an in-app purchase another receipt is added and because of the testing, some or all, of these are signed with your test user id. iOS automatically checks and potentially updates this chain of receipts linked to your app and it needs you to log in so that in can validate the signature on the receipts. But because of the sandbox environment you are somehow not properly logged in, or at least it kicks users out quickly.

I have not found a solution for this

**Comment by christophemarois** [comment]
I confirm that the bug is fixed on iOS 11.3 (Beta). Careful though; I had to:

1. Install the beta provisioning certificate on iOS
2. Intall iOS beta
3. Install xCode beta
4. Upgrade to macOS High Sierra

just to test it.

**Comment by funkenstrahlen** [comment]
Thank you for testing this an letting us know! I really think we can hopefully mark this issue as closed as soon as iOS 11.3 is released.

**Comment by funkenstrahlen** [comment]
I am confirm this is fixed in iOS 11.3.

**Comment by mrleesin** [comment]
What about old iPhone models? ((

**Comment by vasadulin** [comment]
I have the same problem with annoying requesting password. iOS 11.4.1

**Comment by PittCho** [comment]
I have the same problem with annoying requesting password. iOS 11.4.1
same.

**Comment by NunoAlexandre** [comment]
Same issue. Started with iOS 12...

**Comment by exevil** [comment]
+1 here.

**Comment by wupshaw** [comment]
+1 same issue. Worked fine until iOS 12.

**Comment by DanijelHuis** [comment]
When I call this:
```
SwiftyStoreKit.purchaseProduct(productIdentifier) { result in
}
```
It first asks me to enter password and then after purchase is complete it shows "Sign-In Required alert". Purchase is OK even if I tap cancel on second alert. I am testing with sandbox user on iOS 12.

I have tried purchasing product in another app that doesn't use this library but native StoreKit implementation, behavior is the same. It seems Apple messed something on iOS 12, at lease on sandbox.

**Comment by exevil** [comment]
@DanijelHuis: Try to remove your app from your iPhone 7 and Log Out from both your normal and sandbox accounts in Settings.

**Comment by markz-nyc** [comment]
+1 here on iOS 12

**Comment by SohaibSiddique** [comment]
> ### Platform
> * [x]  iOS
> * [ ]  macOS
> * [ ]  tvOS
> 
> ### In app purchase type
> * [ ]  Consumable
> * [ ]  Non-consumable
> * [x]  Auto-Renewable Subscription
> * [ ]  Non-Renewing Subscription
> 
> ### Environment
> * [x]  Sandbox
> * [x]  Production
> 
> ### Version
> `0.11.0`
> 
> ### Related issues
> ## Report
> ### Issue summary
> I call `verifyReceipt` and `verifySubscription` in `applicationDidFinishLaunchingWithOptions` to verify that the user is still a valid subscriber of my premium service.
> 
> Right now in Test Flight beta testing I see the App Store login alert popping up every time I open the app. This is very annoying.
> 
> Is there a better best practise way to verify subscription status? I know Apple recommends doing this via my own server, but I do not want to go this way.
> 
> ### What did you expect to happen
> No popup to sign in. Verification runs in the background.
> 
> ### What happened instead
> Right now in Test Flight beta testing I see the App Store login alert popping up every time I open the app.

Hello,
it's late but asking,
how can you handle user verification? it's on user default or any other method?
and which values you get from receipt and verify subscription to the check user still you premium user?

**Comment by denirorobert** [comment]
This answer helped me: https://stackoverflow.com/questions/51820800/receipt-validation-before-showing-iap-page

**Comment by m-afham** [comment]
OS: **macOS 10.15.5**
XCode : **11.2.1** 
Environment: **SandBox, Production**
Is I am logged in with apple id while testing? (Yes)


I am getting this each time when I called **verifyReceipt** method.
