### ISSUE TITLE
[Question] Is calling restorePurchases required for auto-renewable subscriptions?

### ISSUE THREAD

**Issue by funkenstrahlen** [bizz84/SwiftyStoreKit#308]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
`0.11.0`

### Issue summary
I learned that auto-renewable subscriptions can not be successfully restored by simply calling `restorePurchases`. It does require `verifyReceipt` and `verifySubscription`. Now I am not sure if I can even remove the `restorePurchases` call completely and it is enough to call `verifyReceipt` and `verifySubscription` if the user taps the **Restore** button.

**Comment by ajonno** [comment]
We've got an app under review at the moment w/ auto-renewing subs, and Apple told us that we do need to provide users with a "Restore" option

**Comment by funkenstrahlen** [comment]
> We've got an app under review at the moment w/ auto-renewing subs, and Apple told us that we do need to provide users with a "Restore" option

This is not what my question is about. I know Apple does require a `Restore` button. I want to know which action I should call in code when the user does tap the restore button.

When I use auto-renewable subscriptions only it might be enough to call `verifyReceipt` and `verifySubscription` from `SwiftyStoreKit`. I am just not sure if this is the case.
