### ISSUE TITLE
 attention in the keyword TransactionResult.

### ISSUE THREAD

**Issue by abdulKarim002** [bizz84/SwiftyStoreKit#309]
### Platform

- [ ] iOS

I wanted to make your attention in the keyword _TransactionResult_ which you have used in 
`SwiftyStoreKit/SwiftyStoreKit/PaymentQueueController.swift`

The problem is, in firebase v4 real-time data they have renamed the keyword `FIRTransactionResult` to `TransactionResult`   in a callback function which is creating a small issue using both the library at the same time and as a user of this awesome library I wanted to point it out so that developer who are using SwiftyStoreKit and Firebase v4 should take this point in mind

Currently, i have renamed the `TransactionResult` to `iTransactionResult` in my project were 'i' denoted apple 'i'

Once again 
Thank you for this awesome library.

**Comment by bizz84** [comment]
@abdulKarim002 Thank you for pointing this out. 

[SwiftyStoreKit+Types](https://github.com/bizz84/SwiftyStoreKit/blob/master/SwiftyStoreKit/SwiftyStoreKit%2BTypes.swift) defines a lot of public types at global scope and this could lead to name conflicts with other libraries.

I'll leave everything as is for the moment.

If this becomes a concern, these types could become nested inside the SwiftyStoreKit class.
