### ISSUE TITLE
What happens if AppDelegate method can't be called (React Native app) ?

### ISSUE THREAD

**Issue by ajonno** [bizz84/SwiftyStoreKit#311]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In-app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
RN0.42.3 
The latest version of this lib.

### Issue summary
React Native has an Objective-C AppDelegate. Can we still use SwiftyStoreKit if unable to use the AppDelegate Swift code you require? Sounds like a stupid question I know but still worth understanding the impact of using this lib, without the AppDelegate Swift callback method

### What did you expect to happen
Would LOVE an Objective-C wrapper JUST for the AppDelegate code block.

### What happened instead
Isn't possible. React Native limitation.

**Comment by bizz84** [comment]
@ajonno Thank you for reporting this. 

With regards to Objective-C support, it's all of nothing. It doesn't make much sense to have some methods that support it and others that don't.

This is not in scope for SwiftyStoreKit, but you could write your own wrappers in Objective-C only for the methods that you need?

**Comment by dev-ios-sogo** [comment]
No problem, thanks.
