### ISSUE TITLE
Expose transactionDate in PaymentTransaction

### ISSUE THREAD

**Issue by ogres** [bizz84/SwiftyStoreKit#312]
### Version
0.11.0

Hello,
is there any reason why PaymentTransaction does not have transactionDate already?
If no, can we add it? its very handy to sort/filter them using this property

https://developer.apple.com/documentation/storekit/skpaymenttransaction/1411273-transactiondate

**Comment by bizz84** [comment]
@ogres apologies for the late reply. 

Sure, I'm happy to add it. ETA: before end of tomorrow.

**Comment by ogres** [comment]
Thanks @bizz84

**Comment by bizz84** [comment]
Available in version [0.11.1](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.11.1)
