### ISSUE TITLE
App is crashed While Verifying Recipt

### ISSUE THREAD

**Issue by moontecholabs** [bizz84/SwiftyStoreKit#313]
### Platform

- [#] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [#] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ #] Sandbox
- [ ] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
after Purchasing Product.We encounter Crash at start of Receipt Verification.This is random generated crash. not occurred every time.but we face it frequently

![screen shot 2017-12-11 at 2 47 47 pm](https://user-images.githubusercontent.com/18573842/33823916-b7f71528-de82-11e7-87ac-042ef2d99e9e.png)

### What did you expect to happen
ℹ App should not crashed 

### What happened instead
ℹ App is crashed while receipt verification

**Comment by bizz84** [comment]
@moontecholabs We need to work out what could cause `result` to be `nil`.

1. Are you definitely passing a `AppleReceiptValidator` to `SwiftyStoreKit.verifyReceipt`?

2. The `ReceiptValidator` protocol specifies that result is non-optional:

```swift
public protocol ReceiptValidator {
	func validate(receiptData: Data, completion: @escaping (VerifyReceiptResult) -> Void)
}
```
This means that once validator returns, the result should always be non-`nil`.

3. The other suspect is `DispatchQueue.main.async`, which should capture the (escaping) closure and retain `result` strongly.

Unless I'm missing something, you should never get `nil`. But then again, your screenshot clearly shows it happens.

Could you try to check if `result` is nil just before the `DispatchQueue.main.async` block?

**Comment by moontecholabs** [comment]
@bizz84 thanks for your update
1. yes we are passing AppleReceiptValidator to SwiftyStoreKit.verifyReceipt
3.Ok we will check for nil value befor DispatchQueue.main.async

we will update here and close this bugs if issue is fixed.

thanks again for your help.

**Comment by bizz84** [comment]
@moontecholabs any updates?

**Comment by moontecholabs** [comment]
@bizz84 thanks for your help. now we have placed condition to check  nil before dispatch.main.async. and and it works perfectly.we also found another case in our code where we are not passing itunes sharead screat in AppleReceiptValidator.so this may also be case for crash.but now it work perfectly after passing sharead screat.
