### ISSUE TITLE
Question on purchase response

### ISSUE THREAD

**Issue by psuarez** [bizz84/SwiftyStoreKit#32]
Hello, 
I'm using 0.2.7 version 
I'm experiencing the following problem:  I got the Success response before I got the Store popups to do the purchase.  Sometimes I got the Failed (Cannot connect to the App Store) and after that the Store popups to do the purchase appear. 
Is there a way to control the flow of Store popups? or at least prevent them to appear in those situations?

**Comment by bizz84** [comment]
Are you running on iOS or OS X?

Could it be possible that you started the purchase, then closed or killed the app?

It appears that if a purchase is started, the OS continues with the purchase even after the app is killed.
In this scenario, if the app is started again and you perform a purchase, you are likely to receive the callback from the completed purchase from the previous session.

I'm aware that this can cause confusion and to address this problem on version 0.2.8 I have added a new `completeTransactions()` method that should be called when the app launches.

Could you please try version 0.2.8 (see the README and demo app for how to use this) and let me know if it works?

**Comment by bizz84** [comment]
Does this StackOverflow Q/A describe well the issue you're encountering?

http://stackoverflow.com/questions/4988663/skpaymentqueue-addtransactionobserver-asking-for-app-store-password-on-startup-a

If so, could you try to follow the steps and let me know if it solves the problem?

**Comment by psuarez** [comment]
Hi,
I'm using iOS latest version of everything, deployment target 8.0, testing
on iPhone6 with 9.3

I started coding my own IAP but when I found yours totally like it and I
switched last week.
My code for the purchase is exactly the same as the Demo App.

...

      NetworkActivityIndicatorManager.networkOperationStarted()

      SwiftyStoreKit.purchaseProduct(productIDToBuy) { result in

        NetworkActivityIndicatorManager.networkOperationFinished()



        //self.showAlert(self.alertForPurchaseResult(result))



        switch result {

        case .Success(let productId):


          self.productPurchasedByID(productId)


        case .Error:

          self.indicator.stopAnimating()

        }

...

And no, the app didn't close... but we have been doing so many tests with
the sandbox that when you look at the receipt you have dozens of old
transactions.


Thanks!

**Comment by psuarez** [comment]
Nop is not that case... I'll try to explain it step by step

This is the code, I'll put fake number lines to explain:


L1.     NetworkActivityIndicatorManager.networkOperationStarted()

L2.      SwiftyStoreKit.purchaseProduct(productIDToBuy) { result in

        NetworkActivityIndicatorManager.networkOperationFinished()



L3.        self.showAlert(self.alertForPurchaseResult(result))



        switch result {

        case .Success(let productId):


L4.          self.productPurchasedByID(productId)


        case .Error:

          self.indicator.stopAnimating()

        }



Step 1- Start purchase
Step 2- L1 ok... I see the network activity indicator
Step 3- L2. ok... debugging I can see the line is correctly executed
Step 4- I got the result almost immediately either is Success or Error
(some times I got connection error)
Step 5- L3. alert is shown
Step 6- Almost in the same moment I start receiving App Store Popups that
appear on top of the app indicating what I'm going to buy, how much, some
times asking for my apple ID or password or touch id
Step 7- When I get rid of all the popups, either buying or cancelling
finally I got to the Alert to close it.
Step 8- If I got .Success on Step 4 the app continues to what should happen
if you have paid the subscription L4.  etc.  (even if you cancelled the
payment on the popups)



Does it help?  It's more clear?
Thanks!

**Comment by bizz84** [comment]
The issue you are describing seems very similar in nature to this: https://github.com/bizz84/SwiftyStoreKit/issues/30
Would you be able to test with version 0.2.8 and make sure that you call `completeTransactions()` when the app starts in your AppDelegate? This should clear any old pending transactions and should improve things especially if you were testing with multiple accounts.

**Comment by psuarez** [comment]
I'm testing it, looks promising!

I have 2 more questions after I finish with this one.

Thanks!

**Comment by bizz84** [comment]
@psuarez did version 0.2.8 solve this in your implementation?

**Comment by psuarez** [comment]
Hi,
yes, still having some issues with the beta tester users, we didn't know
that Apple considers testflight users as sandbox users so we had to add a
fail back validation of the receipts so we can upload a build to testflight
and have the same build published, that seems to be working for now but
some users are getting the receipt ok but according to our logs the receipt
doesn't contain the product IDs they are supposedly bought...

Is there a way to have more visibility of what happens at production level
with the IAP?, we have some remote logs implemented but it will not scale
when the app will be more used.

Thanks!

**Comment by bizz84** [comment]
@psuarez Please take a look at the `ReceiptVerifyURL` type as the correct value should be passed in depending on whether the app runs in Test or Production mode.

Currently SwiftyStoreKit only processes requests but doesn't have a way to track IAPs in more detail and I'm not sure I could come up with an unified set of rules for what needs to be tracked (different organisations may have different requirements). I would suggest you fork the project and add hooks as needed.

Also it's possible that once a test plan is devised and implemented (see https://github.com/bizz84/SwiftyStoreKit/issues/38) we can have some more confidence that the library is doing the right thing - however I don't anticipate being able to look at this in detail any time soon (proposals and contributions would be welcome though).

**Comment by psuarez** [comment]
URLs are ok! Did you understood the problem with the fail-back mechanism?

Off course if I found anything that could be added to the library I'll do
it, for now I think is OK.

**Comment by josueruiz7** [comment]
I have the method callback :  
SwiftyStoreKit.completeTransactions() { completedTransactions in
            
            for completedTransaction in completedTransactions {
                
                if completedTransaction.transactionState == .Purchased || completedTransaction.transactionState == .Restored {
                    
                    print("purchased: \(completedTransaction.productId)")
                }
            }
        }

But It keep display the prompt of password, while I am naviagate inside the app, with out purchasing any product.

I am using version 0.3.0
Any advice?

**Comment by bizz84** [comment]
@psuarez Apologies for the very late reply.

There have been some major improvements to the purchase flows recently.

Could you update to the latest version and let me know if everything now works as expected?

I will close this issue if there are no updates in the next few weeks.
