### ISSUE TITLE
Rejected Due To Verify Receipt Error

### ISSUE THREAD

**Issue by WillMays1** [bizz84/SwiftyStoreKit#321]
### Platform

- [X] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [X] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [X] Production

This is what apples explanation was for my app rejection.

Specifically, the app continues to prompt the user to sign in to iTunes when attempting to Create an Account.

Next Steps

When validating receipts on your server, your server needs to be able to handle a production-signed app getting its receipts from Apple’s test environment. The recommended approach is for your production server to always validate receipts against the production App Store first. If validation fails with the error code “Sandbox receipt used in production,” you should validate against the test environment instead.

**Comment by funkenstrahlen** [comment]
Looks like #288

**Comment by WillMays1** [comment]
Yes, sorry for the double post. I posted this before the other issue was identified.

**Comment by funkenstrahlen** [comment]
@WillMays1 If you are sure it is the same issue, just close this one and clarify it as a duplicate.
