### ISSUE TITLE
YouTube Video Documentation

### ISSUE THREAD

**Issue by rebeloper** [bizz84/SwiftyStoreKit#326]
I love SwiftyStoreKit so much that I have used it in hundreds of project (both mine and my clients) and I have created a YouTube video series on how to use it. It is a step by step walkthrough. Take a look at it here: [https://www.youtube.com/watch?v=bIyj6BZ1-Qw&list=PL_csAAO9PQ8b9kqrltk2_SpYslTwyrwjb](https://www.youtube.com/watch?v=bIyj6BZ1-Qw&list=PL_csAAO9PQ8b9kqrltk2_SpYslTwyrwjb)

@bizz84 if you like the playlist you could add it to the ReadMe.

**Comment by bizz84** [comment]
@rebeloper that's amazing! I think it's really helpful for the community to have step-by-step instructions on how to set things up. 👏🎉🚀

I'll add it to the readme.

One thing I noticed is that sometimes the videos flicker a bit at the beginning. Example:

<img width="854" alt="flash" src="https://user-images.githubusercontent.com/153167/34424040-50185fa4-ec18-11e7-8705-64f59960b615.png">

**Comment by rebeloper** [comment]
Great! Thanks for adding it to the ReadMe. I could not find the flicker, I believe it is a player issue from YouTube.

**Comment by bizz84** [comment]
@rebeloper done, it's on master now. Closing this issue for now, let me know if you have other questions.
