### ISSUE TITLE
Support for setting of SKPayment applicationUsername

### ISSUE THREAD

**Issue by ShawnAukstak** [bizz84/SwiftyStoreKit#33]
Unless I'm missing something, It seems as though [SKPayment applicationUsername](https://developer.apple.com/library/ios/documentation/StoreKit/Reference/SKPaymentRequest_Class/index.html#//apple_ref/occ/instp/SKPayment/applicationUsername) can't be set as this is internalized.  [Apple recommends](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/RequestPayment.html) setting this on the SKPayment request to detect fraud.

**Comment by bizz84** [comment]
@ShawnAukstak Thank you for reporting this. It looks like a simple change to make - should be able to implement this week.

**Comment by bizz84** [comment]
This has been implemented on the latest master branch and will be available once version 0.2.9 is released.

**Comment by ShawnAukstak** [comment]
@bizz84 Thanks so much! I'll pull this down this week and use it for my implementation :)

**Comment by bizz84** [comment]
Available on pod/release version 0.2.9

**Comment by DamonChen117** [comment]
This job is half done.
You can set applicationUsername, but never be able to get it after purchase.
