### ISSUE TITLE
Invalid product identifier

### ISSUE THREAD

**Issue by zois** [bizz84/SwiftyStoreKit#335]
### Platform

- [ x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [x ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x ] Production

### Version
0.12.0

### Related issues
?

### Issue summary
I get an invalid product identifier response. ProductId is correct and live, because my live app is using it and I see inapp purchases being completed.
So ie If I want to see info for my product PS_Auto_IA2
```
SwiftyStoreKit.retrieveProductsInfo(["PS_Auto_IA2"]) { result in
			if let product = result.retrievedProducts.first {
				let priceString = product.localizedPrice!
				print("Product: \(product.localizedDescription), price: \(priceString)")
			}
			else if let invalidProductId = result.invalidProductIDs.first {
				print("Invalid product identifier: \(invalidProductId)")
			}
			else {
				print("Error: \(String(describing: result.error))")
			}
		}
```

### What did you expect to happen
Get back info about the product

### What happened instead
I got: Invalid product identifier: PS_Auto_IA2

**Comment by zois** [comment]
I will close this for now, since it might be due to iTunesConnect issues

**Comment by RentonLin** [comment]
If you release your new app with new iAPs, there is chance you must wait 4+ hours before you can get the info from appstore.
