### ISSUE TITLE
Question: How to fetch receipt for restored purchases?

### ISSUE THREAD

**Issue by aehlke** [bizz84/SwiftyStoreKit#339]
When using `restorePurchases`, an array of `results.restoredPurchases` is returned. If I need to use the receipt(s) in order to non-atomically validate these restored purchases in my backend server, do I just use the same `SwiftyStoreKit.localReceiptData` inside the `restorePurchases` callback and send this one receipt to my backend? Or are there multiple receipts I need to access, for each restored purchase?

**Comment by TheRebelMan** [comment]
If I'm not mistaken, it was discussed on  #272

**Comment by bizz84** [comment]
@aehlke Apologies for the very late reply.

You can use this method to fetch the receipt and send it to your server:

```swift
func fetchReceipt(forceRefresh: Bool, completion: @escaping (FetchReceiptResult) -> Void)
```

Closing this. Feel free to reopen if you have any other questions.
