### ISSUE TITLE
Support for iOS 11 app store payment is automatically?

### ISSUE THREAD

**Issue by prsolucoes** [bizz84/SwiftyStoreKit#341]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
Latest

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
Hi, i only want know if i need change something on my app to support App Store payment to continue in my app? I only have today in my AppDelegate didFinishLaunch:

```
DispatchQueue.global(qos: .background).async {
            SwiftyStoreKit.completeTransactions(atomically: false) { purchases in
                ItunesSubscriptionSystemService.completePurchases(purchases: purchases, onSuccess: {
                    //
                }, onError: { (error) in
                    //
                })
            }
        }
```

I need put more something in my app delegate to support app store direct payment?

**Comment by bizz84** [comment]
@prsolucoes I believe you're looking for [`purchaseProduct`](https://github.com/bizz84/SwiftyStoreKit#purchase-a-product-given-a-product-id).

**Comment by prsolucoes** [comment]
Hi man, no, im looking for the direct in-app-purchase without the app, direct from app store. I want know if i need change something on my code that support it.

**Comment by bizz84** [comment]
In that case you want to use `shouldAddStorePaymentHandler`. Documentation for that is in the readme.

**Comment by prsolucoes** [comment]
I know man. What i ask is if i need change my current code or it was added in library initialisation.

**Comment by bizz84** [comment]
All the information you need is here: #240.

In short: you need to implement `shouldAddStorePaymentHandler()` to return true if the content can be delivered when the user will open the app.

You will then receive a callback on `completeTransactions()` once the transaction is `.purchased` or `.failed`.

**Comment by prsolucoes** [comment]
Hi

In my case I’m using auto renew subscription and I need call the server before.

How it work in the method that need return true?
