### ISSUE TITLE
Crash While Requesting Product Info

### ISSUE THREAD

**Issue by moontecholabs** [bizz84/SwiftyStoreKit#344]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Issue summary
ℹ While requesting product info some time app is suddenly crashed.  

### What did you expect to happen
ℹ App should not crash

### What happened instead
ℹ App is crashed occasionally.

Following is our code Snippet.
func requestProductData(productIds: Set<String>, productOrderedList:NSMutableArray,  viewController:UIViewController?) {
        
        orderedList = productOrderedList
        DLog("orderedList \(orderedList)")
        DLog("product list \(productIds)")
        DLog("productOrderedList \(productOrderedList)")
        
        currentController = viewController
   
        SwiftyStoreKit.retrieveProductsInfo(productIds) { result in
            self.productList = Array(result.retrievedProducts)
            self.displayProductInfo()
            
        }
    }

We are calling above Function From Background Queue.Following is crash SS.
![screen shot 2018-01-27 at 11 57 15 am](https://user-images.githubusercontent.com/18573842/35469373-5720e8e0-0359-11e8-8f29-730d9119e2de.png)

**Comment by moontecholabs** [comment]
@bizz84 Any Solution for this.

**Comment by bizz84** [comment]
@moontecholabs Can you try to call this from the main queue instead?

As a general rule, SwiftyStoreKit ensures that all completion blocks are called on the main queue.
So it may be best to call these methods from the main queue also.

**Comment by moontecholabs** [comment]
thanks @bizz84 
> Can you try to call this from the main queue instead?
OK we will try and update here.

**Comment by moontecholabs** [comment]
@bizz84 thanks for your help.
this crash solved with calling Storekit method on main thread.
