### ISSUE TITLE
Module compiled with Swift 3.1 cannot be imported in Swift 3.2

### ISSUE THREAD

**Issue by hyperh** [bizz84/SwiftyStoreKit#350]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
ℹ Cartfile is at `github "bizz84/SwiftyStoreKit" == 0.6.1`
Xcode Version 9.0 (9A235)

### Related issues
ℹhttps://github.com/bizz84/SwiftyStoreKit/issues/295
https://github.com/bizz84/SwiftyStoreKit/issues/226

### Issue summary
ℹ On Xcode 8.3.3 my app builds fine. However, on Xcode 9.0, I cannot build anymore.

Error msg on build failed
```
Module compiled with Swift 3.1 cannot be imported in Swift 3.2
```

I've tried `Clean Build Folder` and rebuilding, but that did not work.

### What did you expect to happen
ℹ To build successfully

### What happened instead
ℹ Build failed

**Comment by bizz84** [comment]
@hyperh This looks like a Carthage problem to me, not SwiftyStoreKit:

- https://stackoverflow.com/questions/46659988/module-compiled-with-swift-4-0-cannot-be-imported-in-swift-3-2-1
- https://forums.developer.apple.com/thread/81310

I think there's a way to remove carthage build files (not just the Xcode build folder), which should fix this for you.

Closing this.
