### ISSUE TITLE
Use of unresolved identifier 'AppleReceiptValidator'

### ISSUE THREAD

**Issue by hyperh** [bizz84/SwiftyStoreKit#356]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
Cartfile is at `github "bizz84/SwiftyStoreKit" == 0.6.1`
Xcode Version 9.2  #(9C40b)
React Native 0.34.1

### Related issues
https://github.com/bizz84/SwiftyStoreKit/issues/334
https://github.com/bizz84/SwiftyStoreKit/issues/234

### Issue summary

My app is a React Native app. I'm trying to upgrade from Xcode 8.3.3 (where everything was compiling before) to Xcode 9.2.

1. Delete  `app/Carthage` folder
1. Delete `app/ios/SwiftyStoreKit.framework`
1. Under `General` >  Remove `SwiftyStoreKit.framework` from `Embedded Binaries` and `Linked Frameworks and Libraries`
1. Run `carthage update --platform iOS --no-use-binaries` to build
1. Copy `app/Carthage/Build/iOS/SwiftyStoreKit.framework` to `app/ios/`
1. Drag and drop `SwiftyStoreKit.framework` into `Embedded Binaries` and `Linked Frameworks and Libraries`
1. Build

Now getting `Use of unresolved identifier 'AppleReceiptValidator'`.

My imports look like

```
import Foundation
import UIKit
import StoreKit
import SwiftyStoreKit
```

My compiled `SwiftyStoreKit-Swift.h` has
`// Generated by Apple Swift version 4.0.3 effective-3.2.3 (swiftlang-900.0.74.1 clang-900.0.39.2)`
at the top.

### What did you expect to happen
To compile properly.

### What happened instead
Did not compile.

**Comment by Sam-Spencer** [comment]
Were you ever able to resolve this issue?
