### ISSUE TITLE
Download freeze or stop

### ISSUE THREAD

**Issue by astrokin** [bizz84/SwiftyStoreKit#357]
### Platform
- [x ] iOS
### In app purchase type
- [ x] Non-consumable 
### Environment
- [x ] Sandbox
### Version
0.13.0
## Report
[IAP] purchase <my_IAP_id> **success**
call **1** `updatedDownloadsHandler `
[IAP] updatedDownloadsHandler with downloads 1
[IAP] download.contentVersion 1.1
[IAP] download.contentURL nil
[IAP] download.contentIdentifier <my_IAP_id>
[IAP] download.error nil
[IAP] download.timeRemaining -1.0
[IAP] download.progress 0.0
[IAP] download.downloadState **waiting**
[IAP] contentURLs 
call `completeTransactions`
[Purchase] completeTransactions state: purchased
call **2** `updatedDownloadsHandler `
[IAP] updatedDownloadsHandler with downloads 1
[IAP] download.contentVersion 1.1
[IAP] download.contentURL nil
[IAP] download.contentIdentifier <my_IAP_id>
[IAP] download.error nil
[IAP] download.timeRemaining -1.0
[IAP] download.progress 0.0
[IAP] download.downloadState **waiting**
[IAP] contentURLs 
call **3** `updatedDownloadsHandler `
[IAP] updatedDownloadsHandler with downloads 1
[IAP] download.contentVersion 1.1
[IAP] download.contentURL nil
[IAP] download.contentIdentifier <my_IAP_id>
[IAP] download.error nil
[IAP] download.timeRemaining -1.0
[IAP] download.progress 0.0
[IAP] download.downloadState **active**
[IAP] contentURLs 

no more anything related to IAP activity

### Issue summary
Help needed.
Can not finish download IAP Hosted content.  I've faced with situation when i successfully buy IAP, then `updatedDownloadsHandler` called with correct object, but download freeze or stop.

### What did you expect to happen
Interactive download process

### What happened instead
download freeze or stop

**Comment by astrokin** [comment]
@bizz84 do you have any ideas about this issue?

**Comment by Sam-Spencer** [comment]
Did you ever figure out what was going on here?

**Comment by zhouhao27** [comment]
I have similar issue. It stops at 0% for some IAP items but works for others.

**Comment by astrokin** [comment]
@Sam-Spencer @zhouhao27 it's happening when you have no Wi-Fi connection. StoreKit will not start downloading until you are using non-wi-fi internet connection. that's it )
