### ISSUE TITLE
Failed for macOS app sometimes

### ISSUE THREAD

**Issue by chaocharleswang** [bizz84/SwiftyStoreKit#359]
### Platform

- [ ] iOS
- [x] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [x] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x] Production

### Version
0.13.1

### Issue summary
I used your library on my macOS app. However, some customers complain they cannot purchase my product.

**Comment by Sam-Spencer** [comment]
Closing as possible duplicate of #347.
