### ISSUE TITLE
Got wrong receipt when using two itunes accounts

### ISSUE THREAD

**Issue by Yetispapa** [bizz84/SwiftyStoreKit#362]
### Platform

- [X ] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [X ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [X ] Production

### Version
0.13.1

### Issue summary
I register a new User and purchase my subscription with Itunes Account A on an Iphone while going through the sign-up flow in my app. Now I make the same from another device with ITunes Account B. Unfortunately I got some issues with the receipt which I am validating cause the receipt which I'm getting on my Itunes Account B is the same like A. I also found the following [stackoverflow question](
https://stackoverflow.com/questions/27282225/ios-in-app-purchase-receipt-with-different-itunes-user) related to this.

### What did you expect to happenI 
The receipt which I'm getting on my second Itunes Account should be invalid in regards of the subscription validation. 

### What happened instead
Instead I got the wrong receipt on my second Itunes Account. I got the receipt from my first Itunes Account instead of my second. The receipt which I got is valid cause the first account successfully purchased the subscription.

What can I do here? I just fetch the receipt without force when I make the subscirption validation.

**Comment by vielucasluu** [comment]
Did you found root problem? @Yetispapa.

What is stale label? @Sam-Spencer ?

I code in same device, sign out Apple ID / download new app.
And still get old receipt.

How to get receipt base on AppleID?
