### ISSUE TITLE
What is sharedSecret?

### ISSUE THREAD

**Issue by antonijap** [bizz84/SwiftyStoreKit#374]
I must be the only one not getting what is that. I read the docs, I checked the code and I can't get it what is that and how to retrieve/use it?

I always get `Receipt verification failed: receiptInvalid(receipt: ["status": 21004, "environment": Sandbox], status: SwiftyStoreKit.ReceiptStatus.secretNotMatching)`

**Comment by dynamite8** [comment]
You can find this in iTunes Connect:
[tutorial here](https://www.appypie.com/faqs/how-can-i-get-shared-secret-key-for-in-app-purchase
)

This article discusses more on detail: https://medium.com/ios-development-tips-and-tricks/working-with-ios-in-app-purchases-e4b55491479b
