### ISSUE TITLE
How to get Purchased Product Info in app delegate

### ISSUE THREAD

**Issue by tripathishivam35** [bizz84/SwiftyStoreKit#378]
### Platform

- [ ] iOS

### In app purchase type

- [ ] Auto-Renewable Subscription

### Environment

- [ ] Sandbox
- [ ] Production

### Issue summary
ℹ I am calling completeTransactions() in App delegate but it is not getting invoked.
I want to get the purchased product Info in order to show user the purchased plan. 
Is there any other method through which I can achieve this while opening the app.

I used the complete transaction method like this : 

        SwiftyStoreKit.completeTransactions(atomically: true) { purchases in
            
            for purchase in purchases {
                switch purchase.transaction.transactionState {
                case .purchased, .restored:
                    let downloads = purchase.transaction.downloads
                    if !downloads.isEmpty {
                        SwiftyStoreKit.start(downloads)
                    } else if purchase.needsFinishTransaction {
                        // Deliver content from server, then:
                        SwiftyStoreKit.finishTransaction(purchase.transaction)
                    }
                    print("\(purchase.transaction.transactionState.debugDescription): \(purchase.productId)")
                    
                    if(purchase.productId == "com.company.appname.monthlyplan"){
                        print("monthly plan purchased")
                        self.LocalStorage .set(true, forKey: "monthly")}
                    else if(purchase.productId == "com.company.appname.quarterlyplan"){
                        print("quarterly plan purchased")
                        self.LocalStorage .set(true, forKey: "quarterly")}
                    else if(purchase.productId == "com.company.appname.yearlyplan"){
                        print("yearly plan purchased")
                        self.LocalStorage .set(true, forKey: "yearly")}
                    self.LocalStorage .synchronize()
                case .failed, .purchasing, .deferred:
                    break // do nothing
                }
            }
        }

But execution never goes inside Completion Block.

**Comment by Sam-Spencer** [comment]
This seems unusual. Did you ever find anything out about this?
