### ISSUE TITLE
RetrieveResults SKErrorDomain Code 0

### ISSUE THREAD

**Issue by goktugyil** [bizz84/SwiftyStoreKit#379]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In-app purchase type

- [x] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
0.10.3

### Issue summary
Getting the error when I run this code:

```swift
SwiftyStoreKit.retrieveProductsInfo([purchaseId)]) { result in
```

```swift
RetrieveResults(retrievedProducts: Set([]), invalidProductIDs: Set([]), error: Optional(Error Domain=SKErrorDomain Code=0 "(null)"))`
```

It was working a week ago, nothing changed, my IDs are correct.

**Comment by Sam-Spencer** [comment]
Hi @goktugyil! Did you ever find out what was going on here?

**Comment by goktugyil** [comment]
Not sure, forgot :(

**Comment by Sam-Spencer** [comment]
Aw :( well thanks for letting us know!
