### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by bizz84** [bizz84/SwiftyStoreKit#38]
Need to devise a plan and add unit tests for this library as the feature set and the number of contributors has been increasing.

Ideally we could discuss proposed approach for test coverage here and then proceed to implementation.

**Comment by Techprimate** [comment]
+1 but is it even possible to test Storekit using Unit Tests?
Wouldn't you have to reset the Simulator everytime after successful purchases?

**Comment by bizz84** [comment]
In my view all relevant StoreKit classes could be stubbed out with property or constructor injection, so that all tests would be synchronous and not make any network calls.

**Comment by bizz84** [comment]
Unit tests are being gradually added on a feature-by-feature basis.

Closing this issue.
