### ISSUE TITLE
Compile Error when targeting macOS/tvOS using Xcode 10

### ISSUE THREAD

**Issue by JonathanDowning** [bizz84/SwiftyStoreKit#380]
### Platform

- [ ] iOS
- [x] macOS
- [x] tvOS

### In app purchase type

- [x] Consumable
- [x] Non-consumable 
- [x] Auto-Renewable Subscription
- [x] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
0.13.2

### Related issues
N/A

### Issue summary
SwiftyStoreKit will not compile for macOS/tvOS using Xcode 10, the following error is emitted:
> Cannot override 'paymentQueue' which has been marked unavailable
at this location:

https://github.com/bizz84/SwiftyStoreKit/blob/master/SwiftyStoreKit/PaymentQueueController.swift#L242

This is because
``` objc
- (BOOL)paymentQueue:(SKPaymentQueue *)queue shouldAddStorePayment:(SKPayment *)payment forProduct:(SKProduct *)product NS_SWIFT_NAME(paymentQueue(_:shouldAddStorePayment:for:))
```
is marked as `NS_AVAILABLE_IOS(11_0);`

### What did you expect to happen
SwiftyStoreKit should compile on macOS/tvOS.

### What happened instead
Compilation fails due to the aforementioned error.

**Comment by shaynem** [comment]
+1 just an into this issue myself

**Comment by KodaKoder** [comment]
+1 is impossible to compile with xcode10/mac

**Comment by prsolucoes** [comment]
Please, merge:
https://github.com/bizz84/SwiftyStoreKit/pull/381

**Comment by bizz84** [comment]
This is now fixed and available on pod version [0.13.3](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.13.3).

Apologies for the very late reply everyone.

**Comment by prsolucoes** [comment]
Thanks.

**Comment by easiwriter** [comment]
Still doesn't compile when installed using cocoapods
