### ISSUE TITLE
App is damaged and can't be opened (Auto-Renewable Subscription)

### ISSUE THREAD

**Issue by rlee0524** [bizz84/SwiftyStoreKit#387]
### Platform

- [ ] iOS
- [x] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
0.13.1

### Related issues
None

### Issue summary
My users are able to subscribe to an auto-renewable subscription.  After they open it a second time after closing the app, they receive an error: 
StreetPulse is damaged and can't be opened.  Delete StreetPulse and download it again from the App Store.

### What did you expect to happen
Expecting users to go directly to the app main screen if the subscription in the receipt is active.

### What happened instead
Getting this error every time the app is launched after subscription:
"StreetPulse" is damaged and can't be opened. Delete "StreetPulse" and download it again from the App Store.

![screen shot 2018-07-14 at 11 13 53 am](https://user-images.githubusercontent.com/26809574/42727224-aa283afc-8757-11e8-90c5-cf1750a0751a.png)

**Comment by rlee0524** [comment]
I've narrowed down the failure to the SwiftyStoreKit.fetchReceipt routine.  

Error: Fetch receipt failed: networkError(Error Domain=SKErrorDomain Code=0 "(null)")
The operation couldn’t be completed. (SwiftyStoreKit.ReceiptError error 1.)

**Comment by tc** [comment]
@rlee0524  did you fix this?

**Comment by Sam-Spencer** [comment]
Any updates on this? Were you ever able to fix this? Is it possibly related to #379?
