### ISSUE TITLE
Fatal Error - Restore Purchases

### ISSUE THREAD

**Issue by arvidurs** [bizz84/SwiftyStoreKit#389]
### Platform

- [ 11.4.1 (15G77)] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [X ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [ X] Production

### Version
 0.13.2

### Issue summary
Once the UI Button calls the function restore I get a fatal crash. 

### What did you expect to happen
Restore the purchases 

### What happened instead
Fatal crash to home screen 

Code which leads to crash:

```
func restorePurchases(viewController: UIViewController) {
    NetworkActivityIndicatorManager.networkOperationStarted()
    SwiftyStoreKit.restorePurchases(atomically: true) { results in
        NetworkActivityIndicatorManager.networkOperationFinished()
        if results.restoreFailedPurchases.count > 0 {
            print("Restore Failed: \(results.restoreFailedPurchases)")
        }
        else if results.restoredPurchases.count > 0 {
            for purchase in results.restoredPurchases {
                logAndUpdate(productId: IAPProduct.init(rawValue: purchase.productId)!, restore: true)
            }
        }
        else {
            print("Nothing to Restore")
        }
        
        showAlert(viewController: viewController, alertForRestorePurchases(results))
    }
}
```

snipped from logAndUpdate:

```
fileprivate func logAndUpdate(productId: IAPProduct, restore: Bool = false) {
    let prefix = restore ? "restorePurchased" : "purchased"
    
    switch productId {
    case .singlet1:
        FB.shared.logEvent(name: "\(prefix)DonationT1", parameters: nil)
        FB.shared.updateUser(data: [UserKeys.hasDonatedT1.rawValue: true], updateLocal: true)
    case .singlet4:
        FB.shared.logEvent(name: "\(prefix)DonationT4", parameters: nil)
        FB.shared.updateUser(data: [UserKeys.hasDonatedT4.rawValue: true], updateLocal: true)
```

Crash Stack Trace
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/6709617/43089051-8f34c12c-8e58-11e8-9d37-075bb59ae0a7.png">

**Comment by bizz84** [comment]
This looks like a crash in your code, not SwiftyStoreKit.

Try removing the `logAndUpdate` call and see if it still crashes.

Closing for now.
