### ISSUE TITLE
Question: Is SwiftyStoreKit working for auto renewing subscriptions?

### ISSUE THREAD

**Issue by bb-git** [bizz84/SwiftyStoreKit#39]
I want to use auto renewing subscriptions and persist them in the keychain. Does the library support this?

**Comment by bizz84** [comment]
This is currently work in progress - see https://github.com/bizz84/SwiftyStoreKit/pull/36

**Comment by bb-git** [comment]
Great, looks like it’s nearly done :).

**Comment by bizz84** [comment]
Available on pod/release version 0.2.9.

**Comment by bb-git** [comment]
Great, thanks 👍
