### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by sewerynplazuk** [bizz84/SwiftyStoreKit#391]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
0.13.3

### Issue summary
Calling `SwiftyStoreKit.purchaseProduct(:identifier)` on simulator and then declining to provide apple id cause 7 memory leaks. I am not sure if this happens in other conditions.

![7](https://user-images.githubusercontent.com/17967811/43518981-0e98b2e8-958e-11e8-9ad1-e9d940c9230a.png)
![6](https://user-images.githubusercontent.com/17967811/43518982-0eb52504-958e-11e8-9a20-b60908fa1e0f.png)
![5](https://user-images.githubusercontent.com/17967811/43518989-0f3acace-958e-11e8-9792-ba164d65716a.png)
![4](https://user-images.githubusercontent.com/17967811/43518983-0ecd7a8c-958e-11e8-9b5e-53420efba184.png)
![3](https://user-images.githubusercontent.com/17967811/43518985-0eecbdb6-958e-11e8-9b0a-763166bde129.png)
![2](https://user-images.githubusercontent.com/17967811/43518986-0f07fe1e-958e-11e8-9d0d-8f6304b92e5e.png)
![1](https://user-images.githubusercontent.com/17967811/43518988-0f20aa54-958e-11e8-99ee-14c09dc38264.png)

**Comment by KingOlami** [comment]
hi please I have been unable to get this project to work kind view my issue and contribute to it please thanks. https://github.com/bizz84/SwiftyStoreKit/issues/412
