### ISSUE TITLE
about applicationUsername value

### ISSUE THREAD

**Issue by JJson** [bizz84/SwiftyStoreKit#393]
### Platform

-  iOS

### In app purchase type

-  Consumable

### Environment

- Sandbox
- Production

### Version
0.13.2

### Issue summary
I call the function SwiftyStoreKit.purchaseProduct("xxxx", quantity: 1, atomically: false, applicationUsername: "id111"), I passed in the parameter applicationUsername, in the payment object in its callback, I did not find the applicationUsername I passed in before.

But in StoreKit's SKPaymentTransactionObserver callback, the payment object has the applicationUsername value.

I think that you lost this property when generating Purchase/PurchaseDetails via SKPayment. It is recommended to add applicationUsername property to the PurchaseDetails and Purchase classes.

Or add a SKPayment property to PurchaseDetails/Purchase.

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by OliferZhang** [comment]
你好，这个问题后来解决了吗

**Comment by JJson** [comment]
> 你好，这个问题后来解决了吗

不记得了，好像我当时自己改了源码，加了个属性来用吧

**Comment by winterwd** [comment]
这个问题，还没解决吗？

**Comment by Baichenghui** [comment]
可以转换一下，不需要改源码

if let transaction = purchase.transaction as? SKPaymentTransaction,
                                   let applicationUsername = transaction.payment.applicationUsername {
                                    
                                }
