### ISSUE TITLE
Testing development IAP builds using SwiftyStoreKit

### ISSUE THREAD

**Issue by foobar8675** [bizz84/SwiftyStoreKit#394]
Not a bug, a question:

I'm using SwiftyStoreKit for my IAP subscriptions and am using retrieveProductsInfo to retrieve my products configured in itunes connect. I have it working in production, but I'm trying to allow my QA team to test on development builds.

QA is logging in using the Sandbox user accounts, but what is confusing to me is since it's a development build, it is using a development bundle identifier, so any products added to itunesconnect are obviously not approved by apple. So retrieveProductsInfo will never return any products.

If anyone has a suggestion, I would appreciate it.

**Comment by nick-iCars** [comment]
If possible (and by 'if possible' I mean change it immediately) use the same bundle ID for both environments. Fairly certain it's a bad practice to differentiate environments this way. There are other mechanisms that will allow you to differentiate between sandbox and production. There are some workarounds (#hacks) for the situation you're describing but they all involve duplicating a lot of stuff in app store connect which at the end of the day wouldn't really be testing your actual production infrastructure.

**Comment by foobar8675** [comment]
thank you!
