### ISSUE TITLE
Add Swift 4.1 to podspec so XCode knows what's up

### ISSUE THREAD

**Issue by acushway** [bizz84/SwiftyStoreKit#399]
I noticed in the release notes that you have updated the code to swift 4.1.

Could you add the following to the podspec:

s.swift_version = '4.1'

This will stop XCode from thinking SwiftySotreKit needs to be converted to Swift 4.1 still.

Thanks and I love the library :)

**Comment by KingOlami** [comment]
hi please I have been unable to get this project to work kind view my issue and contribute to it please thanks. https://github.com/bizz84/SwiftyStoreKit/issues/412

**Comment by bizz84** [comment]
@acushway I have updated the podspec to s.swift_version = '4.2' on version [0.14.0](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.14.0).

Closing this issue.
