### ISSUE TITLE
No callback when the a subscription is already purchased

### ISSUE THREAD

**Issue by odedharth** [bizz84/SwiftyStoreKit#40]
If user is already subscribed to a subscription and he tries to subscribe again to this subscription - the completion handler never gets executed:

```
        SwiftyStoreKit.purchaseProduct(subscriptionSKU) { result in
              // this never gets executed 
        }
```
  
In order to reproduce:
1. subscribe to a renewable subscription 
2. after subscribing successfully - execute the purchaseProduct method again 
this window will eventually will show up:
![img_8116](https://cloud.githubusercontent.com/assets/624023/15579356/fe0e27c2-236c-11e6-91ab-8031cc841886.PNG)

and then nothing happens...

**Comment by bizz84** [comment]
I've been following these steps to test this:

- Open the demo app
- Tap on the Purchase button on the right (which links to an auto renewable subscription)
- Tap through all the IAP messages
- Once complete, tap on the sam purchase button again
- Tap through all the IAP messages

At the end of this sequence, the following messages were logged to console:
```
Purchase Success: com.musevisions.iOS.SwiftyStoreKit.autoRenewablePurchase
Purchase Success: com.musevisions.iOS.SwiftyStoreKit.autoRenewablePurchase
```

While this is correct, I have observed that if there are some unfinished transactions when the app starts, following the steps above leads to non-consistent results, including the issue you reported.

One step to mitigate this is to ensure you call `completeTransactions()` when the app starts as this should clear the transaction queue. I have however observed that all these steps are not always reliable and have to yet diagnose this and find a solution.

**Comment by odedharth** [comment]
I did ran it without `completeTransactions() `, maybe this was the reason...
I'll update if I'll manage to reproduce this again in the future.
Thanks!

**Comment by bizz84** [comment]
I have updated the README file to make it clearer that `completeTransactions()` should be called upon app startup.

**Comment by bizz84** [comment]
@odedharth closing the issue for now. If it's still a problem feel free to reopen.
