### ISSUE TITLE
Xcode 10 Build fails

### ISSUE THREAD

**Issue by mekarpatx** [bizz84/SwiftyStoreKit#403]
I'm trying to solve this for 3 day but no luck. hopefully someone can help. 

### Platform
- 10.13.6 macOS with Xcode10 installed.
- Cocoapods 1.5.3
- The project is an iOS project with targeting iOS 11.0 and upwards.

### Version
0.13.3
### Issue summary

After updating to Xcode10 i got this problem.
Build fails with "Command CompileSwift failed with a nonzero exit code". 
I've tried pod update, deintegrate and install and cleaning build folder.

### What did you expect to happen
I expect build to succeed.

### What happened instead
Build failed.

Thanks for the help.

**Comment by christophemarois** [comment]
This seems related to your problem, and is likely not a direct error of SwiftyStoreKit, but rather of CommonCrypto: https://stackoverflow.com/a/52419690/1558527 

Can you try it and give us feedback? I'm reluctant to upgrade to Xcode 10 because of your issue.

**Comment by florinmatinca** [comment]
I managed to successfully build the project by going to File>Workspace Settings and choose Legacy Build System

**Comment by mekarpatx** [comment]
Wow, that really solved my problem. Thanks a lot. 👏🏼
