### ISSUE TITLE
problem with new ios12 update

### ISSUE THREAD

**Issue by rdforte** [bizz84/SwiftyStoreKit#405]
### Platform

- [ yes] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [ yes] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ yes] Sandbox
- [ ] Production

### Version
0.13.3 Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ the method you call SwiftyStoreKit.completeTransactions is not entering the closure & the methodSwiftyStoreKit.fetchReceipt is not entering the closure

### What did you expect to happen
ℹ I expected for the methods to get the result where I can then handle the success and error.
### What happened instead
ℹ instead we do not get a result and it straight away exits the closure.

**Comment by NunoAlexandre** [comment]
@rdforte 

> the method you call SwiftyStoreKit.completeTransactions is not entering the closure & the methodSwiftyStoreKit.fetchReceipt is not entering the closure

I was also experiencing the `completeTransactions` but it was because I was not "registering" it in the `AppDelegate.application didFinishLaunchingWithOptions`. Now it works.

**Comment by rdforte** [comment]
I think i found the problem so we can close this case as payments are working fine now. The reason why payments were not working is because i was not signing into my apple id upon login of the app but once signed in i was presented with another issue that wouldnt allow me to connect to the itunes store and that is because apple have changed they way they do sandbox test accounts. If im correct we can no longer use random emails but we have to use a proper email and then apple will send us an email to verify our account and once we have verified then we can use that sandbox account and payments are working fine now :)

**Comment by KingOlami** [comment]
hi please I have been unable to get this project to work kind view my issue and contribute to it please thanks. https://github.com/bizz84/SwiftyStoreKit/issues/412
