### ISSUE TITLE
Document mentioned about remote receipt verification but there is no example?

### ISSUE THREAD

**Issue by dzpt** [bizz84/SwiftyStoreKit#413]
I want to send out the receipt to verify it by my own server.
I see remote receipt verification is available, but couldn't find the way to do it ?

**Comment by unittesting0** [comment]
I'm also interested, were you able how to do it?

**Comment by zhanswift** [comment]
It interested for me too

**Comment by ricsantos** [comment]
Once you have the receipt data, you can send it to your own server. Your server should then validate that receipt with Apple https://developer.apple.com/documentation/storekit/in-app_purchase/validating_receipts_with_the_app_store, update your user object in the server accordingly, and send an appropriate response back to your app.
