### ISSUE TITLE
The latest Podspec is not in the public repo

### ISSUE THREAD

**Issue by easiwriter** [bizz84/SwiftyStoreKit#417]
### Platform

- [ ] iOS
- [x ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [ ] Production

### Version
ℹ 0.13.3

### Issue summary
The public Podspec repo is out of date so I can't compile PaymentQueueController on Mac OS.

### What happened instead
Compile error: Cannot override 'paymentQueue' which has been marked unavailable. This has been fixed in the latest release, so please add the Podspec to the public repo.

**Comment by bizz84** [comment]
Apologies for the late reply. I can't seem to publish a new version. If anyone can take a look at this log and suggest a solution that would be great.

[lib-lint.log](https://github.com/bizz84/SwiftyStoreKit/files/2586398/lib-lint.log)

**Comment by bizz84** [comment]
Seems like this is the issue: https://github.com/CocoaPods/CocoaPods/issues/7708.

I'll try updating to the latest cocoapods beta and see if that fixes it.

**Comment by bizz84** [comment]
I have now managed to publish version [0.14.0](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.14.0).

Closing this issue.

**Comment by easiwriter** [comment]
I'm afraid this is still not working. Here are the relevant lines in the pod file:

pod "SwiftyStoreKit"
use_frameworks!

And pod install produces:

Using SwiftyStoreKit (0.12.0)
Generating Pods project

Not 0.14.0 as expected. So I still get the Mac OS error.

**Comment by bizz84** [comment]
@easiwriter can you try `pod repo update` and then `pod install` again?

0.14.0 is definitely published so this is an issue on your end:

https://cocoapods.org/pods/SwiftyStoreKit

**Comment by easiwriter** [comment]
I tried that but am still getting the compiler error. Here's the log for the repo update and install.

AdminisatorsMBP:Writing Shed OSX writingshed$ pod repo update
Updating spec repo `bizz84`
  $ /usr/bin/git -C /Users/writingshed/.cocoapods/repos/bizz84 fetch origin
  --progress
  remote: Enumerating objects: 17, done.        
  remote: Counting objects: 100% (17/17), done.        
  remote: Compressing objects: 100% (5/5), done.        
  remote: Total 17 (delta 12), reused 16 (delta 12), pack-reused 0        
  From https://github.com/bizz84/SwiftyStoreKit
     eaa51b7..8a8120a  master     -> origin/master
     2f75c29..8a8120a  develop    -> origin/develop
   * [new branch]      fix-purchase-offline-crash-demo -> origin/fix-purchase-offline-crash-demo
   * [new tag]         0.14.0     -> 0.14.0
  $ /usr/bin/git -C /Users/writingshed/.cocoapods/repos/bizz84 rev-parse
  --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/writingshed/.cocoapods/repos/bizz84 reset --hard
  origin/master
  HEAD is now at 8a8120a Merge pull request #423 from bizz84/fix-purchase-offline-crash-demo
Updating spec repo `bizz84-1`
  $ /usr/bin/git -C /Users/writingshed/.cocoapods/repos/bizz84-1 fetch origin
  --progress
  remote: Enumerating objects: 17, done.        
  remote: Counting objects: 100% (17/17), done.        
  remote: Compressing objects: 100% (5/5), done.        
  remote: Total 17 (delta 12), reused 16 (delta 12), pack-reused 0        
  From https://github.com/bizz84/SwiftyStoreKit
     eaa51b7..8a8120a  master     -> origin/master
     2f75c29..8a8120a  develop    -> origin/develop
   * [new branch]      fix-purchase-offline-crash-demo -> origin/fix-purchase-offline-crash-demo
   * [new tag]         0.14.0     -> 0.14.0
  $ /usr/bin/git -C /Users/writingshed/.cocoapods/repos/bizz84-1 rev-parse
  --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/writingshed/.cocoapods/repos/bizz84-1 reset --hard
  origin/master
  HEAD is now at 8a8120a Merge pull request #423 from bizz84/fix-purchase-offline-crash-demo
Updating spec repo `master`
  $ /usr/bin/git -C /Users/writingshed/.cocoapods/repos/master fetch origin
  --progress
  remote: Enumerating objects: 143968, done.        
  remote: Counting objects: 100% (143968/143968), done.        
  remote: Compressing objects: 100% (24/24), done.        
  remote: Total 765505 (delta 143946), reused 143953 (delta 143944), pack-reused 621537        
  Receiving objects: 100% (765505/765505), 86.21 MiB | 3.72 MiB/s, done.
  Resolving deltas: 100% (520467/520467), completed with 10649 local objects.
  From https://github.com/CocoaPods/Specs
     92a70b138ae..cb534057238  master     -> origin/master
  $ /usr/bin/git -C /Users/writingshed/.cocoapods/repos/master rev-parse
  --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/writingshed/.cocoapods/repos/master reset --hard
  origin/master
  Checking out files: 100% (78961/78961), done.
  HEAD is now at cb534057238 [Add] VISPER-Swift 3.2.2
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 76836 and retry the command.

CocoaPods 1.6.0.beta.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.6.0.beta.2

Updating spec repo `mentalfaculty`
  $ /usr/bin/git -C /Users/writingshed/.cocoapods/repos/mentalfaculty fetch
  origin --progress
  remote: Enumerating objects: 2, done.        
  remote: Counting objects: 100% (2/2), done.        
  remote: Total 5 (delta 2), reused 2 (delta 2), pack-reused 3        
  From https://github.com/mentalfaculty/Specs
     59fbb80..acb8e4d  master     -> origin/master
  $ /usr/bin/git -C /Users/writingshed/.cocoapods/repos/mentalfaculty rev-parse
  --abbrev-ref HEAD
  master
  $ /usr/bin/git -C /Users/writingshed/.cocoapods/repos/mentalfaculty reset
  --hard origin/master
  HEAD is now at acb8e4d Added Ensembles 2.6.2
AdminisatorsMBP:Writing Shed OSX writingshed$ pod install
Analyzing dependencies
Downloading dependencies
Using Ensembles (2.6.1)
**Using SwiftyStoreKit (0.12.0)**
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 2 total pods installed.

[!] Smart quotes were detected and ignored in your Podfile. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

**Comment by bizz84** [comment]
@easiwriter What does you `Podfile` look like? Your log shows that 0.14.0 is found but you're still installing 0.12.0.

You could try `pod update` or this:

```
pod 'SwiftyStoreKit', '~> 0.14.0'
```

**Comment by easiwriter** [comment]
Damn it. I had pod 'SwiftyStoreKit', '~> 0.14.0' in there but removed it when it wouldn't install. Thanks for that - it's all working now,
