### ISSUE TITLE
Redeem promo code in App Store

### ISSUE THREAD

**Issue by zsong** [bizz84/SwiftyStoreKit#419]
I am adding the capability to my app for supporting promo code redemption of the in-app purchase of consumable products.

If I use just this code, when I hit the URL in Safari, the app pops twice asking the credentials. However it considers the 2nd time as a duplication.
```
SwiftyStoreKit.shouldAddStorePaymentHandler = { payment, product in
    SwiftyStoreKit.purchaseProduct(product as! SKProduct, quantity: 1, atomically: true){ result in
        //
    }
    return true
}
```

If I do
```
SwiftyStoreKit.shouldAddStorePaymentHandler = { payment, product in
    return true
}
```
Then it pops up the credentials just once, but nothing will be deposited.

**Comment by fattalgazi** [comment]
why you didn't explained why you closed your issue, can you please share your solution? @zsong  I'm also have some questions about this method, for example should we try to fetch Bundle.main.appStoreReceiptURL in this method and post it to backend? or just return true. If I'm using just only return true, how we handle to send receipt to server?

**Comment by fattalgazi** [comment]
Ok I found an explanation here: https://github.com/bizz84/SwiftyStoreKit/issues/240#issuecomment-313340416
