### ISSUE TITLE
Question: InAppReceiptVerificator design

### ISSUE THREAD

**Issue by Colafroth** [bizz84/SwiftyStoreKit#422]
Platform

  iOS
  macOS
  tvOS
In app purchase type

  Consumable
  Non-consumable
  Auto-Renewable Subscription
  Non-Renewing Subscription
Environment

  Sandbox
  Production
Version

ℹ Please replace this with the version of SwiftyStoreKit you're using.

Related issues

ℹ Please replace this with references to similar issues (either open or already closed).

Report

```
public func fetchReceipt(forceRefresh: Bool,
                             refresh: InAppReceiptRefreshRequest.ReceiptRefresh = InAppReceiptRefreshRequest.refresh,
                             completion: @escaping (FetchReceiptResult) -> Void)
```

In the code above, I am wondering what is the actual benefit for the design of `InAppReceiptRefreshRequest.ReceiptRefresh = InAppReceiptRefreshRequest.refresh?` 

I mean, it looks pretty cool, also it's helpful for unit testing. But unit test can be done in other simpler ways too.

I am just curious about what the biggest benefit with this design?

Many thanks!

**Comment by Sam-Spencer** [comment]
This allows a default value to be set for callers of `fetchReceipt(...)`, thus allowing them to exclude the `refresh:` parameter if needed.
