### ISSUE TITLE
Crash on casting transaction.error as NSError?

### ISSUE THREAD

**Issue by larryonoff** [bizz84/SwiftyStoreKit#430]
### Platform

- iOS 12.1.1

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [X] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [X] Production

### Version
0.14.1

### Related issues

Sometime application crashes after error cast here https://github.com/bizz84/SwiftyStoreKit/blob/master/SwiftyStoreKit/PaymentsController.swift#L88

**Comment by Sam-Spencer** [comment]
Please provide a little more detail about this issue if it is still occurring. I suspect it has been resolved and urge you to check out version 0.16.0.

**Comment by larryonoff** [comment]
@Sam-Spencer this's really difficult to provide. Because the crash isn't stable.

**Comment by larryonoff** [comment]
BTW I don't experiencing this crash anymore.

**Comment by Sam-Spencer** [comment]
Oh! That's great news!
