### ISSUE TITLE
Xcode 10 have error "cannot connect to itunes store" when purchase, but on xcode 9 is ok?

### ISSUE THREAD

**Issue by uocvip92** [bizz84/SwiftyStoreKit#437]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [x] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [x] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by dungntm58** [comment]
It does not come from XCode 10 or XCode 9. Maybe you did not do purchase properly. You should make sure that your product ID is available for sandbox and production first, then review your purchase flow again.

**Comment by uocvip92** [comment]
No, I use a productID for both Xcode.

**Comment by gaoshanyu** [comment]
It's working fine with Xcode 10 for me.

**Comment by ricsantos** [comment]
This issue should be closed.
