### ISSUE TITLE
Just a question: Loading Indicator

### ISSUE THREAD

**Issue by bilics** [bizz84/SwiftyStoreKit#443]
### Platform

- [X] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [X] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [X] Sandbox
- [ ] Production

### Version
(0.14.2)

## Report

This is not an issue - just a question. Sorry in advance if this is not the right place to ask this question.

After calling `SwiftyStoreKit.purchaseProduct()` there is a reasonable amount of time before any kind of alert (either login/password - or confirm purchase) appears on screen. 

I am wondering what is the best approach / best practice to handle this: should I display some kind of loading indicator before calling `SwiftyStoreKit.purchaseProduct()` and dismissing it after `SwiftyStoreKit.verifySubscription()` finishes (and also dismissing on any error) ? What kind of loading indicator is recommended ? Something that blocks UI ? Or just some spinner on the current UIViewcontroller view ?

Any suggestions are greatly appreciated. 

Thanks

**Comment by 7Kris** [comment]
Some sort of loading indicator would be nice to let users know something is happening, and blocking the UI would be even better so they don't attempt the same process again. Just follow the methods laid out in [SwiftyStoreKit-iOS-Demo/ViewController.swift](url) to know where and when to display the loading indicator, which in this case is `NetworkActivityIndicatorManager`.

**Comment by SohaibSiddique** [comment]
> func purchaseSubscription(with id:String, shareSecret:String) {
        SVProgressHUD.show()
        SwiftyStoreKit.purchaseProduct(id, atomically: true) { result in
            SVProgressHUD.dismiss()
            if case .success(let purchase) = result {
                // Deliver content from server, then:
                if purchase.needsFinishTransaction {
                    SwiftyStoreKit.finishTransaction(purchase.transaction)
                }
                self.verifySubscription(with: id, shareSecret: shareSecret
            }
            else {
                // purchase error
            }
        }
    }


SVProgressHUD is a loading indicator, hope it makes a sense.
