### ISSUE TITLE
auto renewable subscription status on app launch

### ISSUE THREAD

**Issue by bb-git** [bizz84/SwiftyStoreKit#45]
Is there a way to request the status of subscription on app launch without asking for the user credentials?

If not, is there at least a way to get the notification, when the subscription is being renewed?

Thanks

**Comment by bizz84** [comment]
Take a look at the `verifySubscription()` method introduced in version 0.2.9:

https://github.com/bizz84/SwiftyStoreKit#verify-subscription

You should be able to call `SwiftyStoreKit.verifyReceipt(receiptVerifyURL: .Production, password: "your_shared_secret")` and on success call `SwiftyStoreKit.verifySubscription()` with your product id.

This does not require the user to enter the AppleID.

**Comment by bb-git** [comment]
In sandbox it was enough to call SwiftyStoreKit.completeTransactions().
The renewed subscription was processed then.
