### ISSUE TITLE
Swift 5 Support w/ Cocoapods

### ISSUE THREAD

**Issue by jlaws** [bizz84/SwiftyStoreKit#456]
## Expected Results

No warning to convert SwiftyStoreKit.framework to Swift 5

## Actual Results

Xcode created warnings to convert SwiftyStoreKit.framework to Swift 5

## Steps to Reproduce

Build the cocoapod in Xcode 10.2

**Comment by 0ber** [comment]
+

**Comment by marcellofiore** [comment]
Warning: 'Hashable.hashValue' is deprecated as a protocol requirement; conform type 'Payment' to 'Hashable' by implementing 'hash(into:)' instead

**Comment by lighthouse16** [comment]
And warning:

 'public' modifier is redundant for property declared in a public extension 
Replace 'public ' with ''
 
in file SKProduct+LocalizedPrice.swift

**Comment by Mosaics** [comment]
any plan convert it to swift5 ?

**Comment by acushway** [comment]
According to the swift converter (apart from the deprecations) you just need to update line 50 of PaymentsController.swift (and of course the Podspec) to move to swift 5:

    return payments.firstIndex(of: payment)

I'm keen to stop having the swift runtime added to all my downloads.

**Comment by bizz84** [comment]
Swift 5 is now supported as of version [0.15.0](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.15.0). 

See #457.

**Comment by jlaws** [comment]
Thank you!
