### ISSUE TITLE
Support Subscription Offers

### ISSUE THREAD

**Issue by zhuravel-sergey** [bizz84/SwiftyStoreKit#458]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In-app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [+] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x] Production

Guys, please add support for [_Offers_ on auto-renewable subscriptions](https://developer.apple.com/documentation/storekit/in-app_purchase/implementing_subscription_offers_in_your_app). Thanks!

**Comment by zhs2472** [comment]
We need that!

**Comment by AnnieNinaJoyceV** [comment]
Would be great to know if this is expected to be added soon!

**Comment by R0uter** [comment]
Really need this :)

**Comment by maxykato** [comment]
We want it desperately!!

**Comment by aehlke** [comment]
Please use the emoji reaction feature to +1 so that you don't spam everyone subscribed for updates on this :)

**Comment by Gurpartap** [comment]
Thanks for the hard work @bizz84. Is support discount offers even being considered or are we on our own for this one?

**Comment by kylebrowning** [comment]
#499

**Comment by Sam-Spencer** [comment]
This is now available on the `develop` branch. Check back soon for an update to `master` including this enhancement. Thank you @kylebrowning 🎆

**Comment by petrusalin** [comment]
Any estimates for when this is going to make its way to master?

**Comment by Sam-Spencer** [comment]
Now available on master! Update to version 0.16.0 for the new feature! Thanks for bearing with us.

<hr/>
*A side note: we're waiting for CocoaPods push permission from @bizz84. Until he adds new authors to the trunk, CocoaPods will be stuck at 0.15.0. For the time being, you can use SPM, Carthage, or manually integrate!*
