### ISSUE TITLE
restorePurchases verifyReceipt is nil

### ISSUE THREAD

**Issue by srhtylmz19** [bizz84/SwiftyStoreKit#463]
//I'm trying to restore purchase of auto-renewable purchases and these 2 are my functions but
//         SwiftyStoreKit.verifyReceipt functions is returning a thread

func restorePurchases(completion: @escaping (Bool) -> ()) {

        SwiftyStoreKit.restorePurchases(atomically: true) { results in
            if results.restoreFailedPurchases.count > 0 {
                print("Restore Failed: \(results.restoreFailedPurchases)")
                completion(false)
            } else if results.restoredPurchases.count > 0 {
                for purchase in results.restoredPurchases {
                    print("Restore Success: \(results.restoredPurchases)")
                    self.validate(purchase: purchase.productId)
                }
                print("Restore Success: \(results.restoredPurchases)")
                completion(true)
            } else {
                print("Nothing to Restore")
                completion(false)
            }
        }
    }

    func validate(purchase purchaseId: String) {

    let appleValidator = AppleReceiptValidator(service: .sandbox, sharedSecret: "mySecretKey")
    
    SwiftyStoreKit.verifyReceipt(using: appleValidator) { result in            
            switch result {
            case .success(let receipt):
                // Verify the purchase of a Subscription
                let purchaseResult = SwiftyStoreKit.verifySubscription(
                    ofType: .autoRenewable, // or .nonRenewing (see below)
                    productId: purchaseId,
                    inReceipt: receipt)
                
                switch purchaseResult {
                case .purchased(let expiryDate, let items):
                    print("\(purchaseId) is valid until \(expiryDate)\n\(items)\n")
                case .expired(let expiryDate, let items):
                    print("\(purchaseId) is expired since \(expiryDate)\n\(items)\n")
                case .notPurchased:
                    print("The user has never purchased \(purchaseId)")
                }
            case .error(let error):
                print("Receipt verification failed: \(error)")
            }
        }
}

**Comment by Sam-Spencer** [comment]
Could you please provide more specifics on exactly what is going wrong?
