### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by luoxiao** [bizz84/SwiftyStoreKit#469]
### Platform

- [ ] iOS
- [ *] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [* ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [ ] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

![](https://gitbook-1251837863.cos.ap-beijing.myqcloud.com/2019-05-21-140925.png)

**Comment by Sam-Spencer** [comment]
When submitting issues, please provide sufficient detail and description so the community can help. From what I can see your crashed thread has nothing to do with SwiftyStoreKit.
