### ISSUE TITLE
How to verify auto subscription every time when start app

### ISSUE THREAD

**Issue by SohaibSiddique** [bizz84/SwiftyStoreKit#475]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In-app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x] Production

### Version
0.15.0

## Report
I want to verify auto-renewable subscription every time when my app starts, what will the best practice for this, I'm a little bit confused, and which method apple recommended doing this. please explain in which block I can unlock my app features.

**Comment by intacto27** [comment]
Hello, I think you should look to Verify Receipt https://github.com/bizz84/SwiftyStoreKit#verify-receipt
and do receipt verification in the appdelegate.

**Comment by aboutthismac** [comment]
Don't use this Library for verify subscription will make your app crash without proper error handling, use own server based manual verification is best one..
