### ISSUE TITLE
Production verifyReceipt returns latest_receipt_info as object not array.

### ISSUE THREAD

**Issue by kekkememadduck** [bizz84/SwiftyStoreKit#477]
### Platform

- [*] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [*] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [*] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.

Hello guys, 

For my auto renewable subscription app,
i realized that our production environment verifyReceipt endpoint of apple returns latest_receipt_info as Object Not Array. And I checked SwiftyStoreKit codes for that and see that it treats "latest_receipt_info" as Array so it returns nil even if it s not. Below code from SwiftyStoreKit, it tries to cast latest_receipt_info to ReceiptInfo array however it is not array. It is object. You can see apple's partial response 

 "latest_receipt_info": {
        "original_purchase_date_pst": "2019-07-03 06:10:03 America/Los_Angeles",
        "quantity": "1",
        "unique_vendor_identifier": "50C51364-CC63-4211-8A9C-D6ED544FF461",
        "bvrs": "110",
        "expires_date_formatted": "2019-07-06 13:10:02 Etc/GMT",
        "is_in_intro_offer_period": "false",
        "purchase_date_ms": "1562159402000",
       ......
}

`        let (receipts, duration) = getReceiptsAndDuration(for: type, inReceipt: receipt)
`

 ```
   private class func getReceiptsAndDuration(for subscriptionType: SubscriptionType, inReceipt receipt: ReceiptInfo) -> ([ReceiptInfo]?, TimeInterval?) {
        switch subscriptionType {
        case .autoRenewable:
            return (receipt["latest_receipt_info"] as? [ReceiptInfo], nil)
        case .nonRenewing(let duration):
            return (getInAppReceipts(receipt: receipt), duration)
        }
    }
```
### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by leo150** [comment]
Hey @kekkememadduck. Did you solve the issue? Thanks.

**Comment by kekkememadduck** [comment]
@leo150 if i remember correctly, there are two types of receipt. One from apple webhook events which they return latest_receipt_info as object not array, and other one is actual receipt that apple put phone as receipt, they return as array.
