### ISSUE TITLE
Not load product in iOS 13.0

### ISSUE THREAD

**Issue by SanDKHust** [bizz84/SwiftyStoreKit#478]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [x] Consumable
- [x] Non-consumable 
- [ ] Auto-Renewable Subscription
- [x] Non-Renewing Subscription

### Environment

- [x] Sandbox
- [ ] Production

### Version
ℹ Please replace this with the version of SwiftyStoreKit you're using.

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
ℹ Please replace this with an explanation of the issue, including reproduction steps.

### What did you expect to happen
ℹ Please replace this with what you expected to happen.

### What happened instead
ℹ Please replace this with what happened instead.

**Comment by SanDKHust** [comment]
help

**Comment by SanDKHust** [comment]
x

**Comment by RolandasRazma** [comment]
@SanDKHust did you managed to solve this?
