### ISSUE TITLE
Best practice to store the Shared Secret

### ISSUE THREAD

**Issue by unittesting0** [bizz84/SwiftyStoreKit#48]
I wondering where to store the Shared Secret as it is very sensitive data.
At the moment i have stored it as a string in the SwiftyStoreKit class but i know that this is not a good idea.
What if I regenerate the Shared Secret, i should update the whole app and would be a mess.

**Comment by Techprimate** [comment]
I faced this issue before and I got a solution for you: TPObfuscatedString
It is a cocoapod created by me, obfuscating a string by replacing it with method calls

Checkout the README for how it works:
https://github.com/Techprimate/TPObfuscatedString

**Comment by unittesting0** [comment]
@Techprimate Seems to be a good alternative, thank you very much. I'm also thinking an alternative to fetch the string remotely from server.

**Comment by bizz84** [comment]
Closing issue as this is strictly out of scope for this project.
