### ISSUE TITLE
What is needsFinishTransaction for?

### ISSUE THREAD

**Issue by NikKovIos** [bizz84/SwiftyStoreKit#483]
Question:  
Who set `needsFinishTransaction` property? How it should work?

**Comment by ricsantos** [comment]
As I understand it, `needsFinishTransaction` will be set by SwiftyStoreKit if you set `atomically` to `false` when purchasing a product.

> Parameter atomically: whether the product is purchased atomically (e.g. finishTransaction is called immediately)

If `atomically` is true, then `SwiftyStoreKit` will call `finishTransaction` as soon as it succeeds. If it is false, it is up to the application to call `finishTransaction` after some action, eg download data.

**Comment by NikKovIos** [comment]
Why we need this, is there any cases when needsFinishTransaction will be false?

**Comment by ricsantos** [comment]
I believe it is for when you want to download content that is related to the IAP.

**Comment by gzyunke** [comment]
> As I understand it, `needsFinishTransaction` will be set by SwiftyStoreKit if you set `atomically` to `false` when purchasing a product.
> 
> > Parameter atomically: whether the product is purchased atomically (e.g. finishTransaction is called immediately)
> 
> If `atomically` is true, then `SwiftyStoreKit` will call `finishTransaction` as soon as it succeeds. If it is false, it is up to the application to call `finishTransaction` after some action, eg download data.

you are right !
![QQ截图20190922222232](https://user-images.githubusercontent.com/4013363/65389354-cf509900-dd87-11e9-9424-258d651959ee.png)
