### ISSUE TITLE
Support catalyst/UIKit for Mac

### ISSUE THREAD

**Issue by yushuyi** [bizz84/SwiftyStoreKit#484]
#if os(iOS)
    func paymentQueue(_ queue: SKPaymentQueue, shouldAddStorePayment payment: SKPayment, for product: SKProduct) -> Bool {
        
        return shouldAddStorePaymentHandler?(payment, product) ?? false
    }
    #endif

build error

**Comment by Sam-Spencer** [comment]
Bump! Catalyst support would be great!

**Comment by nickthedude** [comment]
Bump

**Comment by ggua5470** [comment]
Bump

**Comment by Sam-Spencer** [comment]
This is especially relevant in light of last week's announcement from Apple that iOS, tvOS, and macOS can all ship as one bundle. This means that macOS apps (including Catalyst apps) can chare in-App purchases with iOS and tvOS apps.

**Comment by Sam-Spencer** [comment]
This change can now be tested on the `develop` branch thanks to PR #486.
