### ISSUE TITLE
Updated VIDEO TUTORIAL on YouTube available

### ISSUE THREAD

**Issue by rebeloper** [bizz84/SwiftyStoreKit#491]
I have updated my video tutorial that can be found here: https://www.youtube.com/watch?v=sIEZ9wijFy0&list=PL_csAAO9PQ8b9kqrltk2_SpYslTwyrwjb

The new video tutorial can be found here:
https://www.youtube.com/watch?v=MP-U5gQylHc

It's simpler and shorter and updated to the latest version of Swifty Store Kit.

Feel free to update the README with the following image:
![StoreKit - In App Purchases Tutorial - SwiftyStoreKit - Xcode 11 - consumables, non-cons, auto and non-renewing subscriptions Thubmnail](https://user-images.githubusercontent.com/2488011/65576278-55cccc80-df7a-11e9-8db5-244e2afa3e46.png)

**Comment by Sam-Spencer** [comment]
Thank you! Fixed in 23eb059.
