### ISSUE TITLE
Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by marybnq** [bizz84/SwiftyStoreKit#492]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [ ] Production

### Version
15.0

### Related issues
ℹ Please replace this with references to similar issues (either open or already closed).

### Issue summary
As soon as I install SwiftyStoreKit and I try to run my app it fails and says: "Command PhaseScriptExecution failed with a nonzero exit code". 
I noticed that when I run pod install, the terminal says: 

[!] The `App [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-App/Pods-App.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `App [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-App/Pods-App.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

Now I know I should go to other linker flags and change the value to $(inherited), but I had to set it on ObjC because I'm using google ad mob as well and it requires to set the linker flags on ObjC. Anyway I tried changing it and running pod update but I still have the same problem.
I even tried: 

- [This](https://stackoverflow.com/questions/40599454/use-the-inherited-flag-or-remove-the-build-settings-from-the-target-c?answertab=active#tab-top)

-  deleting the tests; 

- opening the keychain and lock\unlock it; 

- restarting my macbook; 

Nothing works, what should I do?

**Comment by Sam-Spencer** [comment]
CocoaPods integrations can get quite complicated. I would either suggest asking about this same issue in the CocoaPods community or simply installing SwiftyStoreKit in an alternate way:

1. Swift Package Manager
2. Manually
3. Carthage

See the README for installation instructions. If you're using Xcode 11+, SPM is likely your best bet and the easiest way to avoid mind-numbing issues like these.
