### ISSUE TITLE
Restoring purchase, restores all items

### ISSUE THREAD

**Issue by Momeks** [bizz84/SwiftyStoreKit#493]
### Platform

- [∙] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [∙ ] Consumable
- [ ] Non-consumable 
- [∙] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [∙] Sandbox
- [∙] Production

### Version
Latest version

### Issue summary
I have sereral IAP items on my app. When I tap restore purchase it restores all items! without purchasing other items. I want to restore only a specific product ID.

### What did you expect to happen
It must restore only related product.

### What happened instead
It restores all product without buying other items.

My code:
```
@IBAction func restorePurchase(_ sender: Any) {
        
           SwiftyStoreKit.restorePurchases(atomically: true) { results in
               if results.restoreFailedPurchases.count > 0 {
                   print("Restore Failed: \(results.restoreFailedPurchases)")
                   self.loading.alpha = 0
               }
               else if results.restoredPurchases.count > 0 {
                   print("Restore Success: \(results.restoredPurchases)")
                   self.completePurchase()
               }
               else {
                   print("Nothing to Restore")
                   self.loading.alpha = 0
               }
           }
           
           loading.alpha = 1
       }
```

**Comment by janakmshah** [comment]
Dude, this isn't a repo issue.

You get the collection `results.restoredPurchases` in the callback you need to check that to see which purchases are being successfully restored and then have a switch statement or something which fires the code to unlock the appropriate part of your app.
