### ISSUE TITLE
Update slack invite link in README

### ISSUE THREAD

**Issue by glm4** [bizz84/SwiftyStoreKit#497]
The current link is expired.
If maintainers are no longer wanted or the slack channel is not active we should remove this section from the README.

**Comment by Sam-Spencer** [comment]
Maintainers are definitely still wanted! If you're interested in helping, please click on the updated Slack link in the latest README commit!

Or, [join here](https://join.slack.com/t/swiftystorekit/shared_invite/enQtODY3OTYxOTExMzE5LWVkNGY4MzcwY2VjNGM4MGU4NDFhMGE5YmUxMGM3ZTQ4NjVjNTRkNTJhNDAyMWZmY2M5OWE5MDE0ODc3OGJjMmM).
