### ISSUE TITLE
New CocoaPods Release to fix Catalyst Issue 

### ISSUE THREAD

**Issue by mariohahn** [bizz84/SwiftyStoreKit#498]
Hi, 

I saw you already fixed the catalyst bug and already merged it to master, but you haven't uploaded a new version to CocoaPods. 

I know I can link to the master branch but I think it would be much better to just release a new version. 

Thanks (:

**Comment by exevil** [comment]
+1 here. @bizz84: 🙏

**Comment by filippozanfini** [comment]
I need this. @bizz84

**Comment by anonrig** [comment]
for the time being, you can use swift package manager and just use `master` branch.

**Comment by Sam-Spencer** [comment]
Please confirm if the latest release is available on CocoaPods and works as expected with Catalyst -- v0.15.1.
