### ISSUE TITLE
Do SwiftyStoreKit use location services?

### ISSUE THREAD

**Issue by KatkayApps** [bizz84/SwiftyStoreKit#504]
After adding SwiftyStoreKit to my macOS app now I see the location arrow at the menu bar while I am using SwiftyStoreKit to check a receipt.

Do SwiftyStoreKit use location services in any way?

If so, do I need to add some entitlement to my app, so it will not be rejected by the Mac App Store review?

thanks

**Comment by Sam-Spencer** [comment]
I'm not aware of SwiftyStoreKit using location services or any location / motion hardware at all. You don't need any location entitlements for your SwiftyStoreKit 👍 .

This is fairly curious though... you might want to check if some other process is running simultaneously.
