### ISSUE TITLE
App purchasing is extremely slow

### ISSUE THREAD

**Issue by krish23** [bizz84/SwiftyStoreKit#506]
### Platform

- [x] iOS
- [ ] macOS
- [ ] tvOS

### In-app purchase type

- [ ] Consumable
- [x] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [ ] Sandbox
- [x] Production

### Version
ℹ 0.15.0

### Related issues
ℹ 

### Issue summary
ℹ When the user executes the `SwiftyStoreKit.purchaseProduct` function, it takes long to time to show the next dialog box. For each step, it takes more than 10 seconds.

### What did you expect to happen
ℹ When executing `SwiftyStoreKit.purchaseProduct` it will execute faster and each step should be faster until the user makes the purchase. 

### What happened instead
ℹ Very slow.

**Comment by krish23** [comment]
Here is my sample code:

self.hud.textLabel.text = "Please wait..."
self.hud.show(in: self.view)

SwiftyStoreKit.purchaseProduct(purchase_product, quantity: 1, atomically: true) { result in
    switch result {
    case .success(let purchase):

        var receiptOutData = ""

        SwiftyStoreKit.fetchReceipt(forceRefresh: true) { result in
            switch result {
            case .success(let receiptData):
                //It's taking so much of time to come to this step

                let encryptedReceipt = receiptData.base64EncodedString(options: [])
                receiptOutData = encryptedReceipt
                print("Fetch receipt success:\n\(encryptedReceipt)")
                self.completePurchase(purchase_productId: purchase.productId, receipt_data: receiptOutData)
            case .error(let error):
                print("Fetch receipt failed: \(error)")
            }
        }
        print("Purchase Success: \(purchase.productId)")
    case .error(let error):
        self.hud.dismiss()
        switch error.code {
        case .unknown:
            print("Unknown error. Please contact support")
            SCLAlertView().showError("Payment Failed", subTitle: "Unknown error coming from payment response. Try again and if still fails please contact support.")
        case .clientInvalid:
            print("Not allowed to make the payment")
            SCLAlertView().showError("Payment Failed", subTitle: "From your account, you are not allowed to make the payment.")
        case .paymentCancelled:
            break
            SCLAlertView().showError("Payment Failed", subTitle: "You cancelled your payment!!!")
        case .paymentInvalid:
            print("The purchase identifier was invalid")
            SCLAlertView().showError("Payment Failed", subTitle: "The purchase identifier was invalid, Please contact support")
        case .paymentNotAllowed:
            print("The device is not allowed to make the payment")
            SCLAlertView().showError("Payment Failed", subTitle: "The device is not allowed to make the payment")
        case .storeProductNotAvailable:
            print("The product is not available in the current storefront")
            SCLAlertView().showError("Payment Failed", subTitle: "The product is not available in the current storefront. Please contact support.")
        case .cloudServicePermissionDenied:
            print("Access to cloud service information is not allowed")
             SCLAlertView().showError("Payment Failed", subTitle: "Access to cloud service information is not allowed")
        case .cloudServiceNetworkConnectionFailed:
            print("Could not connect to the network")
            SCLAlertView().showError("Payment Failed", subTitle: "Could not connect to the network, please check your internet.")
        case .cloudServiceRevoked:
            print("User has revoked permission to use this cloud service")
            SCLAlertView().showError("Payment Failed", subTitle: "User has revoked permission to use this cloud service. Contact support")
        default: print((error as NSError).localizedDescription)
        }
    }
}

**Comment by Sam-Spencer** [comment]
You have `forceRefresh` set to `true` here. This means that SwiftyStoreKit will go to the App Store to request the receipt. I think the delay you experience is because you're waiting to hear back from the network.

Consider updating your design so that you don't need to force a receipt refresh right away from the App Store. Or at least do something in your UI while you wait for this.
