### ISSUE TITLE
Where to get "shared secret"?

### ISSUE THREAD

**Issue by jln19** [bizz84/SwiftyStoreKit#507]
### Platform

- [ x] iOS
- [ ] macOS
- [ ] tvOS

### In app purchase type

- [ ] Consumable
- [ ] Non-consumable 
- [ x] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment

- [x ] Sandbox
- [x ] Production

There are a lot of references to "your-shared-secret" such as 

       ` let appleValidator = AppleReceiptValidator(service: .production, sharedSecret: "your-shared-secret")
`

What is this referring to and how do we obtain it?

**Comment by Gargo** [comment]
@jln19 how did you find that? It should be added to readme
