### ISSUE TITLE
Purchase Failed: Failed "Cannot connect to iTunes Store" changed from .Test to .Production

### ISSUE THREAD

**Issue by unittesting0** [bizz84/SwiftyStoreKit#51]
I changed yesterday from .Test to .Production but today i changed back to .Test and In-App purchases does not work i get this:

Purchase Failed: Failed(Error Domain=SKErrorDomain Code=0 "Cannot connect to iTunes Store" UserInfo={NSLocalizedDescription=Cannot connect to iTunes Store})

Can anyone help me what should i do?

**Comment by unittesting0** [comment]
I haven't change the code, don't know if it has to do with my apple developer account but these things are still working:
Getting the price of the products
I get the popup to buy it
But at the end it shows me Cannot connect to iTunes Store

What am I missing?

**Comment by unittesting0** [comment]
I was able to test with my regular apple ID until 6 days ago, after that i created a sandbox user and now it is ok.

**Comment by CavalcanteLeo** [comment]
@unittesting0 how did you solve it?
