### ISSUE TITLE
Please consider extending the interface that can implement subscription promotional offer.

### ISSUE THREAD

**Issue by YinChangDao** [bizz84/SwiftyStoreKit#519]
### Platform

- [ ] iOS

### In app purchase type
- [ ] Auto-Renewable Subscription

### Environment

- [ ] Sandbox
- [ ] Production

### Version
ℹ 0.15.0

### Related issues
ℹ nil

### Issue summary
ℹ Apple introducing subscription promotional offer in iOS 12.2, it would help us winning back lapsed subscribers or retaining current subscribers, but `SwiftyStoreKit` hasn't support it yet. I can't pass a parameter with the type of `SKPaymentDiscount` to the api `purchaseProduct(_ productId: String, quantity: Int = 1, atomically: Bool = true, applicationUsername: String = "", simulatesAskToBuyInSandbox: Bool = false, completion: @escaping (PurchaseResult) -> Void)`. I must realize another purchase process api via `StoreKit` to implement subscription promotional offer instead of apply the api in `SwiftyStoreKi`t, It is weird. 

### What did you expect to happen
ℹ Please append the parameter `paymentDiscount` in `purchaseProduct(_ productId:String, ...` api and make `subscription promotional offer` available.

**Comment by Sam-Spencer** [comment]
Thank you for your contribution! This enhancement was previously requested in issue #458, and fixed in PR #499. Closing as a duplicate -> stay tuned at the aforementioned issues for updates!
