### ISSUE TITLE
Downloadable content

### ISSUE THREAD

**Issue by Filterd** [bizz84/SwiftyStoreKit#53]
Can I use this for IAPs that use downloadable content? (Apple hosted content) I know there isn't any particular functionality for handling downloading, but can I handle downloading myself and just use this library for the purchase part?

**Comment by Rommanski** [comment]
Hi @Filterd 
Sure you can implement downloading by yourself and use this library same time. I did it before.

**Comment by bizz84** [comment]
@Rommanski @Filterd that's correct. Also for more context this issue about delivering the content asynchronously has been discussed: https://github.com/bizz84/SwiftyStoreKit/issues/50

**Comment by Rommanski** [comment]
Hello @bizz84 I am planning to add functionality for downloading remote content for this library. Not sure, it's already done or not? Will be happy to contribute.

**Comment by bizz84** [comment]
@Rommanski thank you for the proposal, however I believe that this library should be simply a **lightweight** layer on top of `StoreKit`, and it would be outside the scope of this framework to offer functionality to download remote content from an arbitrary 3rd party web service.

Also, I feel that for the problem you're describing there is no _one size fits all_ solution as different clients would need:
* Different services to connect to
* Different networking libraries

**Comment by Rommanski** [comment]
Thank you @bizz84  I just want to make own small contribution for this framework. Maybe there is some task that I can do?
With regards

**Comment by bizz84** [comment]
@Rommanski There are some outstanding requests that I have not had time to tackle so far, for example this one: https://github.com/bizz84/SwiftyStoreKit/issues/65

Some discussion here: http://stackoverflow.com/questions/19943183/a-complete-solution-to-locally-validate-an-in-app-receipts-and-bundle-receipts-o

Thanks for contributing! 🤗
