### ISSUE TITLE
Apple Watch Support? 

### ISSUE THREAD

**Issue by gesabo** [bizz84/SwiftyStoreKit#530]
## Platform
- [x] watchOS

### In-app purchase type
- [ ] Auto-Renewable Subscription

### Environment
- [x] Sandbox
- [x] Production

### Version
Current 

### Issue summary
Will SwiftyStoreKit work on the Apple Watch now that StoreKit is? Will the existing release of the library already work on Apple Watch?

**Comment by Sam-Spencer** [comment]
This is definitely something we can explore!

**Comment by 1234igor** [comment]
Any updates on this?

**Comment by 1234igor** [comment]
I tried with multiple apps app it outputs "No such module 'SwiftyStoreKit'" when importing, so looks like there is something missing inside the library or something is restricting it from importing. Couldn't fix this.

**Comment by Sam-Spencer** [comment]
Implemented 🎆!! Check out the `develop` branch to test the changes and ensure the framework is compatible with your watchOS project. You should see this percolate over to `master` in the next couple days.
