### ISSUE TITLE
Update CocoaPods podspec to 0.16.0

### ISSUE THREAD

**Issue by anatoliykant** [bizz84/SwiftyStoreKit#541]
Could you **update** the version of the latest pod to **0.16.0**?

The latest version of the framework from Cocoapods, **0.15.0**, when porting to **Catalyst** gives an error:

```swift
#if os (iOS)
func paymentQueue (_ queue: SKPaymentQueue, shouldAddStorePayment payment: SKPayment, for product: SKProduct) -> Bool {
       return shouldAddStorePaymentHandler? (payment, product) ?? false
}
#endif
```

When installing SwiftyStoreKit using Cocoapods, the previous version of 0.15.0 is installed.
Version 0.15.1 as far as I can see from the PR fixes the error and supports Catalyst.

### What did you expect to happen
It is expected that after updating the pod to version 0.15.1, the error with Catalyst will go away.

### What happened instead
When building the application under macOS Catalyst, an error appears:

```swift
#if os (iOS)
func paymentQueue (_ queue: SKPaymentQueue, shouldAddStorePayment payment: SKPayment, for product: SKProduct) -> Bool {
     return shouldAddStorePaymentHandler? (payment, product) ?? false
}
#endif
```

**Comment by Sam-Spencer** [comment]
Hi! I'm so sorry for the delay with this. I've reached out to @bizz84, the original CocoaPods owner / author for this repo so we can get the new spec pushed up to the trunk!

Hold tight! In the meantime, SPM integration should be working! 😬

**Comment by anatoliykant** [comment]
> Hi! I'm so sorry for the delay with this. I've reached out to @bizz84, the original CocoaPods owner / author for this repo so we can get the new spec pushed up to the trunk!
> 
> 
> 
> Hold tight! In the meantime, SPM integration should be working! 😬 

Thx, Sam.
We will be waiting for you and @bizz84

**Comment by bizz84** [comment]
@Sam-Spencer I sent you a message on Slack about this. There's a step you need to complete, then I can give you push access.

**Comment by Sam-Spencer** [comment]
> @Sam-Spencer I sent you a message on Slack about this. There's a step you need to complete, then I can give you push access.

It should be setup now! @bizz84

**Comment by Sam-Spencer** [comment]
@anatoliykant Huzzah! `0.16.0` is now available on CocoaPods!
