### ISSUE TITLE
Cannot use develop branch in an iOS project

### ISSUE THREAD

**Issue by RomanPodymov** [bizz84/SwiftyStoreKit#542]
## Platform
- [x] iOS
- [ ] macOS
- [ ] tvOS

### In-app purchase type
- [ ] Consumable
- [ ] Non-consumable 
- [ ] Auto-Renewable Subscription
- [ ] Non-Renewing Subscription

### Environment
- [ ] Sandbox
- [ ] Production

### Version
https://github.com/bizz84/SwiftyStoreKit/tree/develop

### Issue summary
Cannot use https://github.com/bizz84/SwiftyStoreKit/tree/develop in an iOS project.

1. Create an empty iOS project with Xcode.
2. Add CocoaPods to the project.
3. Add SwiftyStoreKit to Podfile.
4. Run `pod install`.
5. Try to build the project.

### What did you expect to happen
Successfully build the project without any errors.

### What happened instead
Getting errors in **SKProductDiscount+LocalizedPrice.swift** and **SKProduct+LocalizedPrice.swift**.

**Comment by Sam-Spencer** [comment]
Merged your PR! Thank you so much!
