### ISSUE TITLE
Buying pop-up

### ISSUE THREAD

**Issue by afern247** [bizz84/SwiftyStoreKit#553]
Why when I purchase atomically it appears a pop up to enter the user name and password of apple id? Shouldn't this display the apple pay popup like when you purchase an app in the app store?

**Comment by Sam-Spencer** [comment]
Not necessarily. If you're testing your in-app purchases in the *sandbox* environment then you can expect to see a popup asking for a *sandbox tester's* credentials. All such popups should say this at the bottom:

> [Environment: Sandbox]

iOS and macOS also both have bugs that cause these popups to enter an infinite loop. If you find this happening during testing, simply head to `iTunes and App Store` settings on iOS (or the App Store on macOS) and sign out of your sandbox account, then sign back in again.

By supplying sandbox credentials you won't be charged for purchases made during testing. You can set up sandbox credentials in App Store Connect under the `Users and Access` section.

<hr/>

That being said... if your app is in production and you're seeing this happen in a copy downloaded from the App Store, it's likely iTunes needs you to verify billing information. If that isn't the case, then this could be an issue with StoreKit, the library, or your implementation. More details would be needed at that point though.
