### ISSUE TITLE
Can't compile SwiftyStoreKit for watchOS

### ISSUE THREAD

**Issue by alamodey** [bizz84/SwiftyStoreKit#555]
Hi, I am trying to implement IAP in an independent watchOS app. I installed SwiftyStoreKit 0.16.0 via the preferred method in Xcode 12 beta.

All I've done so far is import SwiftyStoreKit, but as soon as I try to compile there are over 100 errors that say one of the following messages:
'SKProduct' is only available in watchOS 6.2 or newer
'SKReceiptRefreshRequest' is only available in watchOS 6.2 or newer
'canMakePayments()' is only available in watchOS 6.2 or newer

**Comment by Sam-Spencer** [comment]
This was an issue with the platforms specifications in the SPM file! It's been fixed and you can update your SPM to `0.16.1` now.
