### ISSUE TITLE
Is there something wrong with Swift Dependency Manager?

### ISSUE THREAD

**Issue by UzumakiAlfredo** [bizz84/SwiftyStoreKit#576]
## Question
Please explain your question in detail here.
When I want to add this library with Swift Dependency Manager, I get this error:

<img width="709" alt="Screen Shot 2020-09-09 at 5 43 08 PM" src="https://user-images.githubusercontent.com/29095193/92602872-f0293b80-f2c3-11ea-81a2-d9d021eb7cce.png">

I'm using Xcode 12 beta 6

**Comment by UzumakiAlfredo** [comment]
The issue was temporary.

**Comment by Sam-Spencer** [comment]
Phew. That's a relief! Thanks for updating!
