### ISSUE TITLE
'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

### ISSUE THREAD

**Issue by iTarek** [bizz84/SwiftyStoreKit#578]
## Bug Report
Get warning 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.
**To Reproduce**
Use Xcode 12

**Comment by Vanyaslav** [comment]
I got this one yesterday. You need to just to repair your Pods.xcodeproj. You can use the automatic conversion that xCode offers.

**Comment by iTarek** [comment]
> I got this one yesterday. You need to just to repair your Pods.xcodeproj. You can use the automatic conversion that xCode offers.

I am using SPM, how can I fix that with SPM?

**Comment by Sam-Spencer** [comment]
This issue is now fixed on both branches with SPM.

**Comment by Sam-Spencer** [comment]
Podspec is now up to date on the master branch as well. Look out for a CocoaPods release soon. Meanwhile, you can find a workaround in [this StackOverflow post](https://stackoverflow.com/q/63056454/814730).

**Comment by Kaspik** [comment]
@Sam-Spencer Hey! Any chance you could release new version not only to master, but also as a tag and proper release? We use SPM as well, and we don't want to point to master really - instead, stable release would be very welcome. :)

Thanks!

**Comment by Sam-Spencer** [comment]
Sure thing! Sorry for the oversight!

**Comment by pushchris** [comment]
Hello @Sam-Spencer maybe I'm missing something but not seeing a tag or release for these changes. The last release appears to be from July? Any chance we could get this added in?
