### ISSUE TITLE
independent watchOS application. In app purchases

### ISSUE THREAD

**Issue by WilliamAlexander** [bizz84/SwiftyStoreKit#581]
## Bug Report
The problem is when i call function buy the product, the WatchOS (both simulator and real device) always shows message: unable to purchase app sign in with your apple id from the apple watch app on your iphone.
The store info works fine,

**To Reproduce**
1. use pod to install SwiftyStorekit

**Expected behavior**
I expect to see the 'purchase' flow.
I feel the problem is with that fact it's an independent watchOS app (no iphone needed)

NB:
If we think this is a restriction with independent watchOS app then I will remove it.
(eg for in app purchases to work on watchOS app, a watchOS app needed a companion iPhone app)
I wanted to make sure. Thanks
 
## Platform Information
 - OS: watcOS 7.0
 - Purchase Type: non-consumable
 - Environment: device, sandbox, emulator (I expect to see a dialog popup, but not work in emulator)
 - SwiftyStoreKit: 0.16

## Additional context
Apple review sees same problem, app was rejected.

**Potentially Related Issues**

**Screenshots**
<img width="520" alt="Screenshot 2020-09-20 at 10 31 27" src="https://user-images.githubusercontent.com/4633818/93708322-1903c900-fb2d-11ea-90d2-e47135b1971a.png">

**Comment by WilliamAlexander** [comment]
This link says in app purchases should work on independent watchOS apps
https://developer.apple.com/news/?id=wl3gnk1h

**Comment by Reiszecke** [comment]
Hey @WilliamAlexander have you been able to solve it? Firstly it worked locally, now even via TestFlight there is no way to purchase due to this exact popup. What worries me the most is that you report to me that App Review also sees this problem :/

**Comment by WilliamAlexander** [comment]
> Hey @WilliamAlexander have you been able to solve it? Firstly it worked locally, now even via TestFlight there is no way to purchase due to this exact popup. What worries me the most is that you report to me that App Review also sees this problem :/

Hi thanks for chasing.
It would appear that watchOS app need a companion app to let the watch do in app purchases. The quote from Apple "app purchases should work on independent watchOS apps" is not correct. I emailed apple support about this.
Cheers

**Comment by Reiszecke** [comment]
Actually my app has a companion app and still reflects this wrong behavior. Did simply adding an iPhone app solve the issue for you or have you done other things along the way?

**Comment by Reiszecke** [comment]
I've now tried an earlier fork of my app and it's showing the same behavior. idk if the app store servers are just down

**Comment by WilliamAlexander** [comment]
> Actually my app has a companion app and still reflects this wrong behavior. Did simply adding an iPhone app solve the issue for you or have you done other things along the way?

Instead of now getting the prompt on phone (see black screen above), the app on phone prompts for creds.
Check you have the companion app setup properly
