### ISSUE TITLE
Cannot find type 'SKError' in scope

### ISSUE THREAD

**Issue by yositsa** [bizz84/SwiftyStoreKit#583]
After updating to XCode 12.0 and trying to compile, getting error: 'Cannot find type 'SKError' in scope' even though I am using it in another class and imported 'SwiftyStoreKit' in this class.

Also i'm getting a warning:
Module 'SwiftyStoreKit' was not compiled with library evolution support; using it means binary compatibility for 'ZoomQuiz' can't be guaranteed

When importing.

Ideas?

**Comment by Sam-Spencer** [comment]
These issues should be fixed in the latest releases. Make sure you're using at least v0.16.x.
