### ISSUE TITLE
How to trigger the lastest transaction UI

### ISSUE THREAD

**Issue by hidemaeda** [bizz84/SwiftyStoreKit#588]
How do you force to trigger the latest Apple's in-app purchase UI to enter the password or Touch ID like below instead of the old UI? For iOS 14, it automatically triggers the Apple's UI but iOS 13 triggers the old UI. Some reason with the latest UI purchase becomes success by the sandbox testing but with old UI, purchase always fails. Thanks.

![in-app-ui](https://user-images.githubusercontent.com/19158776/96548518-e13e8d00-1262-11eb-96be-1a45f282ff9a.png)

**Comment by hidemaeda** [comment]
Failed reason is "Cannot connect to iTunes Store"

purchase failed error(error: __C_Synthesized.related decl 'e' for SKErrorCode(_nsError: Error Domain=SKErrorDomain Code=0 "Cannot connect to iTunes Store" UserInfo={NSLocalizedDescription=Cannot connect to iTunes Store}))

**Comment by philmodin** [comment]
@hidemaeda 
Are you getting the double password prompt on iOS 13 when making a sandbox purchase?
Seems a lot of people are experiencing this issue right now. Found some discussion here:
https://developer.apple.com/forums/thread/98763

**Comment by philmodin** [comment]
The issue is gone for me today. Guessing Apple fixed it on their end.

**Comment by hidemaeda** [comment]
You are right. This issue is gone now! Thanks
