### ISSUE TITLE
Error Domain=SKErrorDomain Code=0 "无法连接到 iTunes Store"

### ISSUE THREAD

**Issue by jps2782316** [bizz84/SwiftyStoreKit#589]
目前在沙盒环境充值时，一直无法充值成功，iOS 14以下的系统都这样，推测是苹果要发布新系统，可能是调整东西搞出来的bug，不过还是希望有大神能给出一个准确的答案。错误信息如下:
<details>
<summary><i>Translated to English</i></summary>
<blockquote>At present, when restoring in the sandbox environment, has been unable to restore successfully, iOS 14 and below are like this, presumably Apple will release a new system and may be adjusting things to get out the bugs, but still hope that someone can give an accurate answer. The error message is as follows:</blockquote>
</details>

```llbd
(lldb) po purchaseResult
 ▿ PurchaseResult
   ▿ error : 1 element
     ▿ error : related decl 'e' for SKErrorCode
       - _nsError : Error Domain=SKErrorDomain Code=0 "无法连接到 iTunes Store" UserInfo={NSLocalizedDescription=无法连接到 iTunes Store}
```

**Comment by louiskabo** [comment]
你好, 我很抱歉我的中文不好。can you show your code that results in this error? Is this during a purchase? Or a verify receipt?

**Comment by tc976562936** [comment]
其实很简单，在SwiftyStoreKit.fetchReceipt(forceRefresh: true) 获取凭证，会走到error这里，在这里，再按照苹果官方文档那里的方法再次获取一次凭证。获取到了再处理后续问题。

case .error(let error): 方法里添加下面的方法再次获取一遍凭证

                                    if let appStoreReceiptURL = Bundle.main.appStoreReceiptURL, FileManager.default.fileExists(atPath: appStoreReceiptURL.path) {
                                        
                                        do {
                                            let receiptData = try Data(contentsOf: appStoreReceiptURL, options: .alwaysMapped)
                                            print(receiptData)

                                            let receiptString = receiptData.base64EncodedString(options: [])
                  
                                        }
                                        catch {
                                             print("Couldn't read receipt data with error: " + error.localizedDescription)
                                        }
