### ISSUE TITLE
iOS Demo app

### ISSUE THREAD

**Issue by goktugyil** [bizz84/SwiftyStoreKit#59]
Why is it giving me the alert:                             return alertWithTitle("Purchase failed", message: "Please check your Internet connection or try again later")

When I hit cancel instead of buying?

**Comment by bizz84** [comment]
That alert error message is displayed whenever an error is returned by StoreKit - any production code should probably check the error domain and error code and show the most appropriate message to the user. The demo app is for demonstration purposes only and just shows a generic error.

**Comment by bizz84** [comment]
@goktugyil Version [0.8.0](https://github.com/bizz84/SwiftyStoreKit/releases/tag/0.8.0) updates the error checking flows so that you can now check if the user has canceled the purchase.

Please update to the latest version.

Closing this issue as resolved.

**Comment by goktugyil** [comment]
Thanks
