### ISSUE TITLE
Redeem Promo Code to  enable the subscription

### ISSUE THREAD

**Issue by manishk9-bsft** [bizz84/SwiftyStoreKit#595]
## Bug Report
The normal way of Subscription is working fine, My problem is subscription using the Promo Code 

Note:- In didFinishLaunchingWithOptions I already added the 
```swift
SwiftyStoreKit.completeTransactions() { purchases in
    for purchase in purchases {
        switch purchase.transaction.transactionState {
        case .purchased, .restored:
            if purchase.needsFinishTransaction {
                 self.purchaseManagemnt.postcompleteTransactions(purchase)
            }
         case .failed, .purchasing, .deferred:
             break // do nothing
         }
    }
}
```

**To Reproduce**
1. Downloaded the App using the Promo Code
2. Opened the App Manually and complete transactions are not executed/called    

**Expected behavior**
Complete transactions should be called so I can continue my transaction by calling our server login.

## Platform Information
 - OS: iOS 13.4, iOS 14
 - Purchase Type: auto-renewable subscription
 - Environment: production
 - SwiftyStoreKit version: latest Version

Please help me on how to handle promo code if I am doing implementation wrong.

**Comment by louiskabo** [comment]
Without seeing all of your code, I would guess that you skipped a little bit of code that is set to listen for incoming purchases initiated in the app store, refer to the readme section, specifically this part:

> From Apple Docs:
> 
> This delegate method is called when the user has started an in-app purchase in the App Store, and is continuing the transaction in your app. Specifically, if your app is already installed, the method is called automatically. If your app is not yet installed when the user starts the in-app purchase in the App Store, the user gets a notification when the app installation is complete. This method is called when the user taps the notification. Otherwise, if the user opens the app manually, this method is called only if the app is opened soon after the purchase was started.
> SwiftyStoreKit supports this with a new handler, called like this:
> 

```
SwiftyStoreKit.shouldAddStorePaymentHandler = { payment, product in
    // return true if the content can be delivered by your app
    // return false otherwise
}
```

Hope this helps.
