### ISSUE TITLE
Purchase Flow succeeds and then restarts on FIRST purchase with new sandbox account.

### ISSUE THREAD

**Issue by louiskabo** [bizz84/SwiftyStoreKit#597]
## Bug Report
While testing some new features, I came across this bug and am able to reproduce it. It appears that when you make a first purchase in sandbox, you get the all clear from the apple side of the transaction, then the purchase confirmation window starts again and you have to go through the motions to select purchase a seconds time. This only happens on the very first purchase you make with a new sandbox account. Subsequent purchases and renewals do not cause such action. 

**To Reproduce**
1. Create a new sandbox account
2. uninstall and reinstall your app from your computer so as to delete all old data
3. attempt to make any In-App purchase

**Expected behavior**
You should go through the billing flow once, the purchase should complete and the product be made available. Yet this is not happening. As stated, on this first purchase, you are made to basically "start over" with the whole billing flow procedure like it hadn't;t happened before.

## Platform Information
 - OS: iOS 14.2 Xcode 12.2
 - Purchase Type: Testes with non-consumables and Auto-Renewing Subscriptions
 - Environment: Sandbox
 

Thank you.

**Comment by jjkaufman** [comment]
@louiskabo did you find a workaround? I'm seeing this too

**Comment by louiskabo** [comment]
I did not, and I am unable to confirm if it is the same in live with a new iCloud account...

**Comment by RockXeng** [comment]
I'm seeing this too, How to solve it？

**Comment by RockXeng** [comment]
@louiskabo did you find a workaround?

**Comment by louiskabo** [comment]
Unfortunately no, I did not. But I have submitted several updates since discovery and no issues have been raised by review. 

I’d be interested to know if this happens live with a new iCloud account.. 

If u find the glitch, please update this post.

**Comment by RockXeng** [comment]
@louiskabo Because of this problem, I was rejected by Apple several times, so I was confused how to solve it.

**Comment by louiskabo** [comment]
Are you sure it was because of this particular bug? There was another bug that made the test user continue to provide login credentials. Are you sure it is not that bug?

**Comment by louiskabo** [comment]
@RockXeng check out https://github.com/bizz84/SwiftyStoreKit/issues/397

Make sure this isn’t why your getting rejected. What was the specific rejection message they sent you?

**Comment by RockXeng** [comment]
@louiskabo We found that your in-app purchase products exhibited one or more bugs when reviewed on iPad running iOS 14.2 on Wi-Fi.

Specifically, the In-App Purchase (IAP) results in an error.

Below are the steps to reproduce the issue:

1. Launch the application
2. Navigate 开通会员 page
3. Proceed to purchase one of the IAP products
4. IAP confirmation window appears
5. Confirm Purchase
6. User is prompted with Purchase Successful message
7. IAP confirmation window appears again

**Comment by RockXeng** [comment]
I'm sure this isn’t #397 reject reason.

**Comment by louiskabo** [comment]
Interesting. I have not found the work around For this but if your getting rejected because of it, I’d say we need to.. if you figure it out, please update this post, I’ll do the same.

**Comment by RockXeng** [comment]
I just implemented the IAP function by myself, and I will also pop up the confirmation popup twice. I think this should be a bug in the iOS system.

let payment = SKPayment(product: skProduct)
SKPaymentQueue.default().add(self)
SKPaymentQueue.default().add(payment)

**Comment by louiskabo** [comment]
Excellent. I think we can close this report then. You should document your findings, report them to Apple and appeal your rejection. 

Thank you

**Comment by louiskabo** [comment]
@RockXeng, any luck? Please post your Apple bug report # here for others to reference. if they have similar rejections.

Btw 呢 说 汉语吗？我是数中文额生。我是不很好。 lol

**Comment by louiskabo** [comment]
I can also confirm this has nothing to do with swifty store kit and is an apple bug..

**Comment by KKKoTTT** [comment]
I am having the same issue. For me it happens when I'm using the release build configuration, but everything works good in the debug one. I'm not sure if this will work in the published app, could you please share how you eventually solved this problem?

**Comment by louiskabo** [comment]
as long as what you are experiencing is this specific bug:

This is an apple bug and does not have anything to do with swifty. I confirmed this by testing in another app that does not use swifty, but uses a simple consumable product IAP with plain StoreKit and the same thing happened. 

I have submitted a few updates to Apple since this and have not had issues with review. It seems that it does not happen in production. 

You could submit a bug report and then save that bug report number for repeal if your app gets rejected, would be my advice. 

To further verify, try just making a purchase using StoreKit to see if this bug still exists and is your problem, otherwise start a new bug report here as this question is closed/resolved.
