### ISSUE TITLE
Best practice: Do you check for subscription every time or do you cache the result?

### ISSUE THREAD

**Issue by tulssinep** [bizz84/SwiftyStoreKit#607]
To me it's mind-boggling how the IAP system can be so difficult so I'm very thankful for this library.

However, I am unsure about one thing: Should you verify the ID of the subscription each time the user launches the app or would you cache the result and only check like once a month? If so, I you didn't mind sharing some code I would be very thankful

**Comment by Sam-Spencer** [comment]
It's a serious headache for sure!

While you could check the receipt each time, the callback is asynchronous; so if you're trying to quickly determine if the user has access to a feature (i.e. they just tapped a button and you need to know *now*), I'd recommend caching the status of their subscription.

The way you do that depends on your app. Personally, what has worked for me is to store some subscription information in the device's keychain. The app periodically updates the keychain value in the background when checking the receipt. This implementation (for my use case) has allowed me to synchronously check if the user is subscribed, while also maintaining a fairly up-to-date record in the background.
