### ISSUE TITLE
Subscription: Should you verifyPurchase in completeTransactions block?

### ISSUE THREAD

**Issue by tulssinep** [bizz84/SwiftyStoreKit#608]
In the examples it says

```
case .purchased, .restored:
                        if purchase.needsFinishTransaction {
                            // Deliver content from server, then:
                            SwiftyStoreKit.finishTransaction(purchase.transaction)
                        }
                        // Unlock content
                        ..
```

However, it seems to also go in that block when a subscription is expired and the user restores purchases (at least in Xcode testing).

Should I instead of "unlock content" do verifyPurchase with my subscription IAP ID before actually unlocking content?

**Comment by shtalhaejaz** [comment]
Yes. This method returns all completed transactions irrespective of the state either expired or purchased. 
So, for subscriptions verifyReceipt should be called here.

**Comment by m-afham** [comment]
Yes. This method returns transactions irrespective of the state either expired or purchased.
So, you should always do verify the purchase with your IAP ID before unlocking. content.
