### ISSUE TITLE
Subscription Offer example / documentation 

### ISSUE THREAD

**Issue by Appinghouse** [bizz84/SwiftyStoreKit#618]
## Question
Please explain your question in detail here.

Hello,

it has been asked here before several times already, but no answers... Could someone please provide an example or a documentation on how to use SwiftyStoreKit with subscription offers / discounts please ? How to show, purchase and restore discounted subscriptions ?

Thanks

**Comment by Sam-Spencer** [comment]
Please see [this section of the Wiki about discounts](https://github.com/bizz84/SwiftyStoreKit/wiki/Discounts). Restoring works in exactly the same way - either the user has a subscription to restore or they don't, it doesn't matter if they had a discount or not. Purchasing works almost exactly the same too, from the wiki article:

> ...you can simply supply your discount object as a parameter in the call to `purchase(...)` on SwiftyStoreKit.

**Comment by bstillitano** [comment]
Why was this closed so abruptly? The documentation is woeful on this topic. You need to generate an SKProduct somehow which is not defined anywhere.
