### ISSUE TITLE
Unknown Error - payment successful

### ISSUE THREAD

**Issue by andrei-chis-zynk** [bizz84/SwiftyStoreKit#626]
## Question

We have experienced a case where a user purchases a consumable, **money was taken** but in code, an error was returned and we cannot unlock the content.

```
Error Domain = SKErrorDomain Code = 0 "An unknown error has occurred" 
UserInfo = {NSLocalizedDescription = An unknown error has occurred, 
{Error Domain = "ASDServerErrorDomain Code = 2024" Confirmation required 
"UserInfo = {NSLocalizedDescription = Confirmation required}}}) code: 0
```

### Code
- SwiftyStoreKit (0.16.1)

```
SwiftyStoreKit.purchaseProduct("consumableProductId", quantity: 1, atomically: false) { result in
            switch result {
            case .success(let product): ...
            case .error(let error): **<Error returned here>**
            }
}
```

- `CompleteTransactions` called in `AppDelegate` once and on reachability update.
```
SwiftyStoreKit.completeTransactions(atomically: true) { purchases in
            for purchase in purchases {
                switch purchase.transaction.transactionState {
                case .purchased, .restored:
                    if purchase.needsFinishTransaction {
                        SwiftyStoreKit.finishTransaction(purchase.transaction)
                    }
                case .failed, .purchasing, .deferred:
                    break
                @unknown default:
                    break
                }
            }
        }
```
### Questions
1. How should we handle this in order to avoid taking user money if an error is returned from StoreKit?
2. Based on the error "Confirmation required", is something wrong with the user's Apple Account?

Thank you in advance!

**Comment by NikKovIos** [comment]
If you call `SwiftyStoreKit.finishTransaction` in `completeTransactions` than the payment will be lost. In this method you need to verify server about this purchase. But I don't know how to manage additional data that need to be send to server.

**Comment by andrei-chis-zynk** [comment]
You're saying that even though `SwiftyStoreKit.purchaseProduct` returned an error and took user's money, `completeTransactions` will return a `.purchased` transaction?

I mean, it's a possibility, if the money was taken to still have a "purchased" transaction.

**Comment by NikKovIos** [comment]
Indeed, it would be `.purchased` and `needsFinishTransaction == true`
It means that apple returned that it's ok. Your server's validation is the other thing.

**Comment by andrei-chis-zynk** [comment]
I was able to test the "Interrupted Purchase" with a `.storekit` configuration file (sandbox environment doesn't work for this).

Thanks @NikKovIos for your help, really appreciated it.

**Comment by NikKovIos** [comment]
@andrei-chis-zynk if you find how to clearly verify `lost` purchases - tell me please.

**Comment by andrei-chis-zynk** [comment]
@NikKovIos haven't found a way to verify a user's receipt received from Apple. Maybe try to refund the users or contact Apple (technical question email) about this.

**Comment by NikKovIos** [comment]
We decided that the best way would be
1) Send to server that purchase is gonna start 
2) Start apple purchase
3) After success send the receipt and server would verify it and in callback finish the transaction
In fail - send to server that the purchase stopped
4) if crash or close, at next start in appdelegate ask server if there is pending transaction with id and get information from it and then verify receipt.

**Comment by andrei-chis-zynk** [comment]
Currently, I rely on the Apple payment queue to always deliver the `.purchased` transaction on app start until I `.finishTransaction()`.

Thinking about your solution, I think it's a good idea to rely on your own server:
- if you have multiple products under 1 consumable product, this way you know exactly which product you bought
- if you don't want to rely on Apple payment queue to deliver the in-progress purchase (not sure how long transaction remain on the Apple queue if they are not finished)
