### ISSUE TITLE
Can We Change the mode settings for this one?

### ISSUE THREAD

**Issue by QaiserAbbas** [bizz84/SwiftyStoreKit#639]
Can we change the dark mode to light mode? for popups like 
you're all set your purchase was successful in dark mode

??
I have an app which is only light mode, but SwiftyStorekit is using darkmode as well?

**Comment by Sam-Spencer** [comment]
SwiftyStoreKit does not present any custom UI, only minimal pieces of system UI. It isn't possible to force the system to adopt your application's light / dark appearance, unfortunately.
