### ISSUE TITLE
Resumption of non-renewable subscription by changing date

### ISSUE THREAD

**Issue by vkortunov** [bizz84/SwiftyStoreKit#68]
After the expiry of the subscription user can change the system date to the date prior expiration. I suggest using `request_date_ms` from receipt response in `InAppReceipt.verifySubscription`

maybe this function helps:
```
private class func getRequestDate(inReceipt receipt: ReceiptInfo) -> NSDate {
        guard let receiptInfo = receipt["receipt"] as? ReceiptInfo else {
            return NSDate()
        }
        let requestDateValue = receiptInfo["request_date_ms"]
        guard let doubleValue = requestDateValue?.doubleValue else { return NSDate() }
        let requestDateDouble = (doubleValue / 1000)
        return NSDate(timeIntervalSince1970: requestDateDouble)
    }
```

**Comment by bizz84** [comment]
@vkortunov Thank you for reporting this and apologies for the late reply.

So if I understand correctly you are suggesting that we remove the `validUntil` parameter from the `verifySubscription()` method:
```
SwiftyStoreKit.verifyReceipt() { result in
    if case .success(let receipt) = result {
        let purchaseResult = SwiftyStoreKit.verifySubscription(
            productId: "com.musevisions.SwiftyStoreKit.Subscription",
            inReceipt: receipt,
            validUntil: NSDate())
    }
}
```
and we extract the `"request_date_ms"` value from the receipt inside`verifySubscription()` and compare it with the receipt expiration date?

**Comment by bizz84** [comment]
Fixed here: https://github.com/bizz84/SwiftyStoreKit/commit/d61e30595a49ce6d34925b2ba0be9a3d0d272cbf
