### ISSUE TITLE
receiptInvalid(receipt: ["status": 21002], status: SwiftyStoreKit.ReceiptStatus.malformedOrMissingData)

### ISSUE THREAD

**Issue by VladyslavKozlovskyi** [bizz84/SwiftyStoreKit#687]
## Bug Report

Hi guys, 
today apple updated its requirements to receipt verification and I received an error `Receipt verification failed: receiptInvalid(receipt: ["status": 21002], status: SwiftyStoreKit.ReceiptStatus.malformedOrMissingData)`

when calling `SwiftyStoreKit.verifyReceipt(using: appleValidator) { result in`
<img width="989" alt="Screenshot 2023-02-07 at 23 28 20" src="https://user-images.githubusercontent.com/43851099/217369767-6fb6a10c-5d58-4e12-a3fb-ff0f1b913b8f.png">

yesterday and some days before all worked as expected and I didn't see any errors.

Thanks for your response, looks like an urgent critical issue!

**Comment by WangGouHei** [comment]
same question

**Comment by golikovartem404** [comment]
have the same issue

**Comment by petrykDima** [comment]
have the same question

**Comment by VladyslavKozlovskyi** [comment]
<img width="1477" alt="Screenshot 2023-02-08 at 11 48 19" src="https://user-images.githubusercontent.com/43851099/217494733-c2da62da-d059-435b-a148-7e704bad3122.png">
I pinged Maintainers in Slack so hope, it will be resolved in the nearest time

**Comment by staninprague** [comment]
Guys, was not there an outage in App Store receipt verification? I saw a post on it on twitter.

**Comment by VladyslavKozlovskyi** [comment]
<img width="718" alt="Screenshot 2023-02-08 at 12 13 28" src="https://user-images.githubusercontent.com/43851099/217500656-7289c618-5a85-4dce-9723-02a51205f3d4.png">


> Guys, was not there an outage in App Store receipt verification? I saw a post on it on twitter.

**Comment by hehawjq** [comment]
have the same question

**Comment by ShiratoriAoi** [comment]
I got same problem. 
In my app, sandbox test fails.
But the same app from app store still works properly.
I don't know if it's a certificate issue or an outage issue.

https://twitter.com/dueapp/status/1623135356022587393

**Comment by staninprague** [comment]
As of this moment, there is still an outage: https://developer.apple.com/system-status/
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/3834343/217504249-705d4931-e8b3-4062-8963-db3d299c7c2a.png">

**Comment by iKisliy** [comment]
Still outage, but looks better for now

**Comment by staninprague** [comment]
Looks like resolved
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/3834343/217610591-c78385d5-221b-4686-b64f-88f64437fc66.png">

**Comment by mohammed-salah-zidane** [comment]
The same issue here please your advice

**Comment by golikovartem404** [comment]
Method works well now. Who also?

**Comment by VladyslavKozlovskyi** [comment]
it's alive
