### ISSUE TITLE
receiptInvalid(receipt: ["status": 21002])

### ISSUE THREAD

**Issue by golikovartem404** [bizz84/SwiftyStoreKit#688]
Hello,

When calling SwiftyStoreKit.verifyReceipt(using: appleValidator) I received an error **Receipt verification failed: receiptInvalid(receipt: ["status": 21002], status: SwiftyStoreKit.ReceiptStatus.malformedOrMissingData)**

<img width="651" alt="Screenshot at Feb 08 10-25-10" src="https://user-images.githubusercontent.com/109585128/217451256-fba17f4f-7d41-42fc-900e-65bfb830a8a6.png">

Yesterday it worked well.

What could be the problem??

Thanks!

**Comment by petrykDima** [comment]
have the same issue

**Comment by hehawjq** [comment]
have the same issue

**Comment by Muneebaliarshad** [comment]
Facing the same issue.

**Comment by golikovartem404** [comment]
It working fine now
