### ISSUE TITLE
retrieveProductsInfo always showing dollars for different currency

### ISSUE THREAD

**Issue by goktugyil** [bizz84/SwiftyStoreKit#71]
The in app purchase dollar price is $4.99. It is showing the correct price and currency in the USA market. But in in other markets, for my experience the Turkish one, its showing $12.99. Which should have been 12,99 TL. 

How to fix this?

**Comment by C6silver** [comment]
You need to format for localized currency.  What code are you using to do that?

**Comment by goktugyil** [comment]
var inAppPurchasePrice = ""

    static func getRecipePartTabletInfo() {
        SwiftyStoreKit.retrieveProductsInfo([inAppPurchaseID]) { result in
            if let product = result.retrievedProducts.first {
                let priceString = NSNumberFormatter.localizedStringFromNumber(product.price, numberStyle: .CurrencyStyle)
                inAppPurchasePrice = priceString
            }            
        }
    }

**Comment by C6silver** [comment]
I have a post at top about how the code you are showing may not be the best way to handle.  However, if your phone's region is set to say Turkey, you should be getting the correct currency symbols.  

I think the better way to do this is to set the currency symbol based on what Apple returns as the locale for the amount.  Again I recently posted about this.  Here is the code I may suggest:

                ```
let numberFormatter = NSNumberFormatter()
                numberFormatter.locale = product.priceLocale
                numberFormatter.numberStyle = .CurrencyStyle
                let priceString = numberFormatter.stringFromNumber(product.price ?? 0)!
```

**Comment by goktugyil** [comment]
Thanks it works as expected
