### ISSUE TITLE
Transaction Id of purchase?

### ISSUE THREAD

**Issue by jlichti** [bizz84/SwiftyStoreKit#72]
I'm migrating my app to swift from obj-c and found this really nice library. We use google analytics to track purchases and currently pass in the transaction id. For the nice swift callbacks the only thing available is the product id and the transaction observer closure only seems to be called when there isn't an active purchase. 

Would it make sense to just always call that closure? Or alternatively pass the transaction details back with the purchase success?

**Comment by bizz84** [comment]
@jlichti Apologies for the late reply.

You can get the the transaction ID for your purchases by using `verifyReceipt()`, `verifySubscription()` and `verifyPurchase()` as explained in the README.

This has also been answered in #91 and #10.

**Comment by bizz84** [comment]
@jlichti Following recent changes to the purchase flows you now get access to the transaction identifier when a purchase succeeds.

I believe this should satisfy your requirements and I'm closing this issue.

Feel free to reopen if you need further details.
