### ISSUE TITLE
Product Price Example Should be Changed

### ISSUE THREAD

**Issue by C6silver** [bizz84/SwiftyStoreKit#73]
In the example used to get product details the approach uses the following to get price:

`let priceString = NSNumberFormatter.localizedStringFromNumber(product.price ?? 0, numberStyle: .CurrencyStyle)`

The problem I see with this is that it's using the device's region setting to set currency.  However, it is possible that the device's region settings are not aligned with the locale that Apple is sending with the product description.  In that case the above approach will incorrectly present a currency symbol for the amount given.  For example if region is set to France and Apple sends the amount in USD, the code above would put in a Euro symbol but with a USD amount.  

Rather than the above I think we should look at the locale of the price Apple sends.  This will ensure that the currency symbol always matches the amount.  Something like this:

```
                let numberFormatter = NSNumberFormatter()
                numberFormatter.locale = product.priceLocale
                numberFormatter.numberStyle = .CurrencyStyle
                let priceString = numberFormatter.stringFromNumber(product.price ?? 0)!
```

**Comment by goktugyil** [comment]
https://github.com/bizz84/SwiftyStoreKit/issues/71

I've also had this issue, I think you should send a pull request for this

**Comment by bizz84** [comment]
Thank you for suggesting the fix.

Updated: https://github.com/bizz84/SwiftyStoreKit/commit/e479b888a82f58b456df6df13e7ec260fbc3a726
