### ISSUE TITLE
Synchronously load receipt without verification.

### ISSUE THREAD

**Issue by joeycarmello** [bizz84/SwiftyStoreKit#74]
Right now the only way to read receipt data is by calling `verifyReceipt`, and getting access to the `ReceiptInfo` in the `VerifyReceiptResult`. 

The issue is that this always make a network call out to Apple, just to read receipt data in a format that I can pass into `verifyPurchase`. This makes it impossible provide an offline-enabled app with this framework alone. I'm happy to verify the receipt with apple using this technique immediately after purchase, but there is no reason to do it every time the app is launched.

Is it possible to provide an accessor to the current `ReceiptInfo` data?

**Comment by bizz84** [comment]
@joeycarmello Apologies for the late reply.

As the user can make multiple purchases over a time period, you may want to always have the most up to date receipt, which is done with a call to `verifyReceipt()`.

In simple cases where for example you have only one purchase available, you could call `verifyReceipt()` only the first time that the purchase has completed and store it locally. After that you can just get the receipt from your local storage and verify the purchase even if you are offline.

It is beyond the scope of SwiftyStoreKit to provide a way of storing receipt data in the app. You could do it yourself with the keychain for example.

**Comment by bizz84** [comment]
@joeycarmello version 0.5.4 adds a `SwiftyStoreKit.localReceiptData` value to access the local receipt.

Note that local receipt verification is not implemented yet. See #101

**Comment by bizz84** [comment]
@joeycarmello does the addition of `SwiftyStoreKit.localReceiptData` solve your problem?

If this issue is not updated in the next few weeks I will close it. Local receipt verification is tracked here: #101

**Comment by RiverbayChris** [comment]
It would be nice if we could get access to this localReceiptData as a Dictionary or ReceiptInfo (just like the AppleReceiptValidator does), so we can easily retrieve the properties in the local receipt. This would solve the need to store any productIds and other properties within the app itself, as we can just read directly from the receipt file using SwiftyStoreKit.

**Comment by bizz84** [comment]
@RiverbayChris as I said, this can be retrieved with `SwiftyStoreKit.localReceiptData`:

```swift
extension SwiftyStoreKit {

    // MARK: Public methods - Receipt verification

    /**
     * Return receipt data from the application bundle. This is read from Bundle.main.appStoreReceiptURL
     */
    public static var localReceiptData: Data?
}
```

You can see how this is used in [InAppReceipt.swift](https://github.com/bizz84/SwiftyStoreKit/blob/master/SwiftyStoreKit/InAppReceipt.swift) and [AppleReceiptValidator.swift](https://github.com/bizz84/SwiftyStoreKit/blob/master/SwiftyStoreKit/AppleReceiptValidator.swift).

Does this answer your question?

**Comment by bizz84** [comment]
@RiverbayChris @joeycarmello closing this for now. Feel free to reopen if my answer does not work for you.
