### ISSUE TITLE
How to getInfo in an orderly fashion?

### ISSUE THREAD

**Issue by nhantrivinh** [bizz84/SwiftyStoreKit#77]
So I have 1, 3, and 6 months subscription option. I am using the getInfo func in the demo with the products appended into an array. As of now the order in which the products appear are random, how do I control this so that it will load 1, 3, 6 months accordingly?

**Comment by jeremygibbs** [comment]
I have something similar. I store the returned products in an array of type SKProduct and then sort based on price:

`self.products!.sort { $0.price.compare($1.price) == .orderedAscending }`
