### ISSUE TITLE
Auto-renewable verification ~ Subscription group

### ISSUE THREAD

**Issue by jayvenn** [bizz84/SwiftyStoreKit#78]
I have 3 products under auto-renewable verification. All of them unlock a feature, but they are of different durations. Would I have to verify all three with SwiftyStoreKit? If not, how would I verify a group of subscription or something like that?

**Comment by androidcn** [comment]
yes
you can verify all three product with this kit

**Comment by nhantrivinh** [comment]
How would I verify a group of subscription? By individually checking all of them or is there a way to check a group of subscription is what I am asking :)

**Comment by bizz84** [comment]
@nhantrivinh Apologies for the late reply.

You can verify the subscriptions individually as explained here: https://github.com/bizz84/SwiftyStoreKit/issues/85

As for subscription groups, I need to read a bit more on the topic to understand how it works and if I need to change something on SwiftyStoreKit to enable it. Overview here:

https://developer.apple.com/app-store/subscriptions/

**Comment by bizz84** [comment]
@jayvenn you need to verify all three subscriptions individually with [verifySubscription()](https://github.com/bizz84/SwiftyStoreKit#verify-subscription).

There is no special support for groups in SwiftyStoreKit.

Closing this issue.
