### ISSUE TITLE
Invalid state returned when restoring purchases

### ISSUE THREAD

**Issue by filipmelik** [bizz84/SwiftyStoreKit#8]
Sometimes (I dont know how the users do it - i was not able to simulate it) when user is trying to restore purchases, payment queue returns invalid state .Purchased and the app crashes in the following line:

<img width="1353" alt="screen shot 2016-01-11 at 21 33 27" src="https://cloud.githubusercontent.com/assets/5735485/12246173/3e0adbfc-b8ad-11e5-93be-5f38adbb6f17.png">

any idea what is wrong?

**Comment by bizz84** [comment]
I did not expect that we could get a Purchased result type when restoring purchases via StoreKit, so I originally added an abort call for this scenario.

As this is happening for you, I have now fixed this case to return ```.Success(productId: productId)``` in the latest pod version 0.2.2. Please update your installation.

Also could you tell me how many purchases you made in your app prior to requesting restore purchases?  Are they consumable or non-consumable in app purchases?

**Comment by filipmelik** [comment]
Thanks Andrea.
It also seems strange to me that you can get Purchased result type for restore flow. And because of this reason, I am not quite sure if this is the right fix to the problem, because it seems like a StoreKit error. I would rather consider it as an error state that should be handled by application - i.e. tell the user to try again, because the expected sate is .Restored and not the . Purchased state. I think this fix could result in unlocking app content that the user did not pay for. What do you think?

My app has only one in app purchase available and it is non-consumable. When testing on my sandbox account, everything works as expected and restoring purchases always work with correct state. This case that happened was on some user's device from my app deployed on the AppStore, so I cannot really tell what the user did prior to this error but I suspect that they were just trying to restore purchases even they did not purchased any in the hope that it will unlock the app content (as I would do it :])

This case has happened to me for the second time by now.

**Comment by phimage** [comment]
Agree to transform into error.
And maybe never use `fatalError` - instead use some `assert`(so only for xcode dev/debug mode) for the non expected code and return errors

**Comment by bizz84** [comment]
Agree with the rationale for treating this as an error.
Consequently, the following three cases need to be addressed:

- When making a purchase ```Restored``` and ```NothingToRestore```
- When restoring purchases, ```Purchased```

These could be mapped into an ErrorType and passed back as an error to the outer completion block so that the calling code can present some 'Unknown error' message to the user.

Do you agree with this proposed solution?

**Comment by filipmelik** [comment]
Agree. This would be the approach I would take personally.

**Comment by bizz84** [comment]
This has now been fixed in version 0.2.3.
Decided to go for a standard NSError for the invalid flows, rather than introducing more ErrorType based enumerations as this would have just resulted in an extra level of nesting for errors reported to the calling code.

**Comment by filipmelik** [comment]
Thanks for the fix.
