### ISSUE TITLE
Verifitcation Purchase Error: ReceiptInvalid(["status": 21004, "environment": Sandbox], SwiftyStoreKit.ReceiptStatus.SecretNotMatching)

### ISSUE THREAD

**Issue by unittesting0** [bizz84/SwiftyStoreKit#89]
Accidentaly updated the pods and got updated from 0.2.10 to 0.5.1 and went back to 0.2.10 and now I'm getting this error :Verifitcation Purchase Error: ReceiptInvalid(["status": 21004, "environment": Sandbox], SwiftyStoreKit.ReceiptStatus.SecretNotMatching)

What should I fix?

**Comment by unittesting0** [comment]
Included SwiftyStoreKit.verifyReceipt(password:  "password here")
Now it's working, but still confused!

**Comment by bizz84** [comment]
As you said, you need to specify the secret key in the `password` parameter
