### ISSUE TITLE
SharedSecret - Where to add in the library?

### ISSUE THREAD

**Issue by Bizzi-Body** [bizz84/SwiftyStoreKit#9]
Not really an "issue"

Is there a central place I can place I can put my shared secret?

Or should I edit the SwiftyStoreKit.swift file directly?

**Comment by phimage** [comment]
You want to store somewhere your shared secret?
If yes there is many way, hard coded, keychain, nsuserdefault(crypted!!), crypted or not (CryptoSwift)
(for instance my framework can store data https://github.com/phimage/Prephirences )

ps: Do not edit third party files like SwiftyStoreKit.swift if you can make some `extension`
