### ISSUE TITLE
Works in Sandbox, but not on approved apple store app

### ISSUE THREAD

**Issue by DClark5218** [bizz84/SwiftyStoreKit#90]
Hey @bizz84 thanks for this awesome module! I've created an app with subscriptions and got approved on the app store. Unfortunately it seems like for some reason it doesn't work when a user tries to purchase things.

I get a "cannot connect to apple" error. Very confusing because things work in sandbox mode no problem. Any thoughts on this?

Thanks!

**Comment by moh1122** [comment]
same here on sandbox its working perfectly but in real id its not
anyone has a clue?

**Comment by DClark5218** [comment]
Glad im not the only one, but concerning that this module no longer works? Hopefully @bizz84 can chime in!

**Comment by moh1122** [comment]
can any one help us in this, how can users get the product with real IDS

**Comment by DClark5218** [comment]
@moh1122, I got it working. It seems like it takes time for things to propagate across apples servers. It takes 48 hours from when it appears to the apple store.

If things work in sandbox it should work in production after time.

Closing this issue.

**Comment by moh1122** [comment]
thanks @DClark5218
