### ISSUE TITLE
Receipt for purchaseProduct()

### ISSUE THREAD

**Issue by San-Jeevan** [bizz84/SwiftyStoreKit#91]
Why does it not return a receipt when you perform SwiftyStoreKit.purchaseProduct().

All I get back is productID which is useless if you are going to perform validation on a remote server (and not verification on client);

**Comment by mingyeow** [comment]
@San-Jeevan - did you ever figure this out?

**Comment by mingyeow** [comment]
i have the same problem as well

**Comment by San-Jeevan** [comment]
No but I found a workaround that works nicely.
When purchase is success, I call on this method:

```
   func triggerReceiptRefresh(){
        SwiftyStoreKit.verifyReceipt() { result in
            switch result {
            case .Success(let receipt):
                // Verify the purchase of Consumable or NonConsumable
                let purchaseResult = SwiftyStoreKit.verifyPurchase(
                    productId: "com.xxx.blblablab",
                    inReceipt: receipt
                );
                //RECEIPT IS THE RECEIPT OF THE LATEST PURCHASE!
                switch purchaseResult {
                case .Purchased(let expiresDate):
                    print("Product is purchased.")
                case .NotPurchased:
                    print("The user has never purchased this product")
                }
            case .Error(let error):
                print("Receipt verification failed: \(error)")
            }
        }
    }
```

**Comment by francisjervis** [comment]
I figured out the same solution, however I am unable to access the transaction ID or other values from the receipt here - did anyone manage to do that?

**Comment by San-Jeevan** [comment]
@francisjervis the receipt is a json object. in_app is a property of the receipt. in_app.transaction_id is what you are looking for.

**Comment by francisjervis** [comment]
@San-Jeevan Thank you for your reply! However, when I try to use
````let r = receipt.in_app.transaction_id
in my code, I get a "value of type ReceiptInfo has no member "in_app" - I looked at the SSK code and it looks like this property may not be exposed. Were you able to access this property in the callback from VerifyReceipt?

**Comment by San-Jeevan** [comment]
@francisjervis yes.
I think in_app is an array.

does this work?
`let r = receipt.in_app[0].transaction_id`

**Comment by francisjervis** [comment]
Thank you once again! Unfortunately no, it does not - the following code based on #10 does, though:
```
                if let receiptInfo: NSArray = receipt["latest_receipt_info"] as? NSArray {
                    let lastReceipt = receiptInfo.lastObject as! NSDictionary
                    let r = lastReceipt["original_transaction_id"] as! String
                    print (r)
                }
                else {
                    print("error")
                }
```

**Comment by bizz84** [comment]
@francisjervis That is correct.
So if you want to purchase a product and verify its receipt you can do this:
```
SwiftyStoreKit.purchaseProduct("your.product.id") { result in
  if case .success(let productId) = result {
     SwiftyStoreKit.verifyReceipt(password: "your-shared-secret") { result in
         // receipt is a [String: AnyObject]
         // check receipt["latest_receipt_info"] and lastReceipt["original_transaction_id"] as above
         // optionally validate purchase (example for a non-consumable purchase)
         let purchaseResult = SwiftyStoreKit.verifyPurchase(
                        productId: productId,
                        inReceipt: receipt)
         // purchaseResult is either .purchased or .notPurchased
     }
  }
```

**Comment by bizz84** [comment]
Also note that the receipt **does not contain only the latest receipt**. 
In other words, if you print `receipt["receipt"]` you'll see the info for all purchases completed so far.

**Comment by San-Jeevan** [comment]
Id like to ask for this issue to remain open a little longer because I just got a mail from a customer from Russian who used the in app purchase and i cannot see anything in my server log files!

There is something dodgy going on, im gonna test a little more.

**Comment by kurdyukovp** [comment]
@bizz84 @San-Jeevan What I should send to my server for validation? receipt["receipt"] ? I tried many options with base64, but got 21002 from Apple.

**Comment by San-Jeevan** [comment]
Well I have received more in-app purchases and the one case I was talking about appears to be a russian scam attempt. (claiming he bought, but didnt receive the purchased item, turns out it was fake receipt)

**Comment by San-Jeevan** [comment]
just wanted to give an update. 

I am receiving more complaints from people that they havent been credited for the purchase.
I check my server logs and I havent received anything but itunes store says I did get purchase.

this library is too unstable if you are going to use a 3rd party server to verify the receipt.
unreliable after refreshreceipt and on purchase.


sucks really.
I have yet to decide if I am gonna use that other swift library for store or implement a layer of additional check on top of this library.

**Comment by aehlke** [comment]
@San-Jeevan any progress updates on this?

**Comment by zsong** [comment]
Getting this error 

Receipt verification failed: receiptInvalid(receipt: ["status": 21002], status: SwiftyStoreKit.ReceiptStatus.malformedOrMissingData)
