### ISSUE TITLE
Compiler and Linker issue for xcode 8 - Swift 3.0

### ISSUE THREAD

**Issue by satishreddy17** [bizz84/SwiftyStoreKit#92]
I am trying to use SwiftStoreKit in my application which i was running in xcode 8 and in swift 3.0, I installed the Swiftystorekit through pods and my pods version is 1.1.0, when i build, it is getting following error, I even converted the framework to swift 3.0 in the project. I kept the Use Legacy in build settings to YES.

This is the error -- "ld: /Users/sgarlapti/Library/Developer/Xcode/DerivedData/iPhone-bukboczpvqrpdhfixueqtnasoqug/Build/Products/Debug-iphonesimulator/SwiftyStoreKit/SwiftyStoreKit.framework/SwiftyStoreKit compiled with newer version of Swift language (3.0) than previous files (2.0) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)"

Help me to fix this issue, Thanks in advance.

**Comment by aivars** [comment]
Had a similar problem after exiting project update to the Swift 3.
This one on the end of Podfile solved issue for me:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

**Comment by bizz84** [comment]
@satishreddy17 @aivars is the post install script still needed?

I believe this should no longer be necessary:
http://blog.cocoapods.org/CocoaPods-1.1.0/

**Comment by bizz84** [comment]
Looks like Xcode 8.2.1 still doesn't default `SWIFT_VERSION` to 3.0 so it looks like the change to the Podfile is till needed.

I'm closing this issue as it's not really specific to SwiftyStoreKit.
